<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.335">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Dr.&nbsp;D">
<meta name="dcterms.date" content="2023-03-20">
<meta name="description" content="A method to use additional information about the population in the survey design.">

<title>Sampling Methods - Stratified Sampling</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Sampling Methods</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../weekly_details.html">
 <span class="menu-text">Weekly Overview</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../notes.html">
 <span class="menu-text">Notes</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../assignments.html">
 <span class="menu-text">Assignments</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-hackmd" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">HackMD</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-hackmd">    
        <li>
    <a class="dropdown-item" href="https://hackmd.io/@norcalbiostat/sampling_r_resources">
 <span class="dropdown-text">R resources</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://hackmd.io/@norcalbiostat/458_intro_hackmd">
 <span class="dropdown-text">What is HackMD</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://hackmd.io/@norcalbiostat/cn02-intro_sampling">
 <span class="dropdown-text">Sampling Framework notes</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://hackmd.io/@norcalbiostat/cn03-statistical_foundations">
 <span class="dropdown-text">Foundations of Estimation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://hackmd.io/@norcalbiostat/cn06_stratified">
 <span class="dropdown-text">Stratified Sampling</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../syllabus.html">
 <span class="menu-text">Syllabus</span></a>
  </li>  
</ul>
              <div class="quarto-toggle-container">
                  <a href="" class="quarto-color-scheme-toggle nav-link" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
              </div>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#what-is-stratified-sampling-lohr-3.1" id="toc-what-is-stratified-sampling-lohr-3.1" class="nav-link active" data-scroll-target="#what-is-stratified-sampling-lohr-3.1">What is Stratified Sampling (Lohr 3.1)</a>
  <ul class="collapse">
  <li><a href="#estimating-population-parameters" id="toc-estimating-population-parameters" class="nav-link" data-scroll-target="#estimating-population-parameters">Estimating population parameters</a></li>
  <li><a href="#gain-from-stratification" id="toc-gain-from-stratification" class="nav-link" data-scroll-target="#gain-from-stratification">Gain from stratification</a></li>
  <li><a href="#closing-thoughts" id="toc-closing-thoughts" class="nav-link" data-scroll-target="#closing-thoughts">closing thoughts</a></li>
  </ul></li>
  <li><a href="#theory-of-stratified-sampling-lohr-3.2" id="toc-theory-of-stratified-sampling-lohr-3.2" class="nav-link" data-scroll-target="#theory-of-stratified-sampling-lohr-3.2">Theory of Stratified Sampling (Lohr 3.2)</a>
  <ul class="collapse">
  <li><a href="#notation" id="toc-notation" class="nav-link" data-scroll-target="#notation">Notation</a></li>
  <li><a href="#bias-and-variance-of-estimators" id="toc-bias-and-variance-of-estimators" class="nav-link" data-scroll-target="#bias-and-variance-of-estimators">Bias and variance of estimators</a></li>
  </ul></li>
  <li><a href="#sampling-weights-lohr-3.3" id="toc-sampling-weights-lohr-3.3" class="nav-link" data-scroll-target="#sampling-weights-lohr-3.3">Sampling Weights (Lohr 3.3)</a>
  <ul class="collapse">
  <li><a href="#call-svydesign" id="toc-call-svydesign" class="nav-link" data-scroll-target="#call-svydesign">Call <code>svydesign</code></a></li>
  <li><a href="#calculate-mean-se-and-ci" id="toc-calculate-mean-se-and-ci" class="nav-link" data-scroll-target="#calculate-mean-se-and-ci">Calculate mean, SE and CI</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Stratified Sampling</h1>
</div>

<div>
  <div class="description">
    A method to use additional information about the population in the survey design.
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Dr.&nbsp;D </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">March 20, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2); <span class="fu">library</span>(sampling); <span class="fu">library</span>(survey)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="what-is-stratified-sampling-lohr-3.1" class="level1">
<h1>What is Stratified Sampling (Lohr 3.1)</h1>
<div class="callout-tip callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Motivating Example
</div>
</div>
<div class="callout-body-container callout-body">
<p>Valuating bank assets is a time consuming but critical action needed in the case of a bank failure where the FDIC needs to take over. These assets can be described as 1 of 7 types such as real estate mortgages, commercial loans, and consumer loans.</p>
<p>If we were to take a SRS of all assets from a failed bank to estimate the total dollar amount the FDIC needs to acquire, we could run into a few problems.</p>
<ul>
<li>Consumer loans tend to be smaller on average compared to other types, so the variance of the total could be very large, leading to an imprecise estimate</li>
<li>A SRS won’t guarantee that items from each of the 7 types of asset categories will be sampled. This would result in undercoverage bias.</li>
</ul>
</div>
</div>
<p>It is desirable then to create a sampling design that uses information about the population to improve precision and would prevent a bad (heavily biased) estimate.</p>
<p>If the average value of a variable of interest is different for different subpopulations (e.g.&nbsp;average amount of loans in the 7 different types), then we may be able to obtain a more precise estimate by taking a <strong>stratified</strong> random sample.</p>
<div class="callout-important callout callout-style-default no-icon callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Definition: Stratified Random Sampling
</div>
</div>
<div class="callout-body-container callout-body">
<p>The word <em>stratify</em> means to “arrange or deposit in layers”. That is to divide the population into <span class="math inline">\(H\)</span> non-overlapping subpopulations called <strong>strata</strong>.</p>
<p>We then draw an independent probability sample (simple random sample) from each strata, then pool the information to obtain overall population estimates.</p>
</div>
</div>
<div class="callout-tip callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Example: Revisiting farmland size
</div>
</div>
<div class="callout-body-container callout-body">
<p>Let’s reconsider the estimate for the average number of acres devoted to farms in 1992. Recall that each row in the data set represents a county in the United States. In Example 2.6 we took a 10% SRS from the entire population and looked at the distribution of <code>farms92</code>.</p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>agpop <span class="ot">&lt;-</span> readr<span class="sc">::</span><span class="fu">read_csv</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"data"</span>, <span class="st">"agpop.csv"</span>))</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">8126834</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="fu">nrow</span>(agpop)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>index <span class="ot">&lt;-</span> <span class="fu">srswor</span>(<span class="dv">300</span>,N)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>agsrs <span class="ot">&lt;-</span> <span class="fu">getdata</span>(agpop,index)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(agsrs, <span class="fu">aes</span>(<span class="at">x=</span>acres92)) <span class="sc">+</span> <span class="fu">geom_histogram</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="cn06_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="384"></p>
<p></p><figcaption class="figure-caption">The number of acres devoted to farms in 1992 is very skewed. Most counties have fewer than 500k acres in farms, where some have more than 1.5M acres.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p><span class="emoji" data-emoji="question">❓</span> What if this large variance is because counties in the West are physically larger than those in the East? (e.g.&nbsp;LA County is HUGE). The frequency table below confirms that there are many more counties (rows in the data set) from the North Central and Southern compared to from the West or Northeast.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(agpop<span class="sc">$</span>region)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  NC   NE    S    W 
1054  220 1382  422 </code></pre>
</div>
</div>
<p>Instead of taking a 10% sample from the entire population, let’s stratify by region first, and then take a 10% sample within region. Review Table and Figure 3.1. What do you notice about the sampled proportion within region, and the sample average and variance within regions?</p>
<p><img src="../figs/table_3_1.png" class="img-fluid"></p>
<p><img src="../figs/fig3_1.jpg" class="img-fluid"></p>
<p>Things to notice:</p>
<ul>
<li>West has highest mean, and highest variance</li>
<li>Distribution of acerage is still skewed right within region</li>
</ul>
<section id="estimating-population-parameters" class="level2">
<h2 class="anchored" data-anchor-id="estimating-population-parameters">Estimating population parameters</h2>
<p>Since a SRS was taken from within each strata, we can use the <a href="https://sampling-458.netlify.app/notes/formulas.html#simple-random-sample">same equations</a> from SRS to estimate the population parameters for each stratum.</p>
<ul>
<li>Overall Total = sum of within strata totals</li>
<li>Variance of the overall total = sum of variances of totals</li>
</ul>
</section>
<section id="gain-from-stratification" class="level2">
<h2 class="anchored" data-anchor-id="gain-from-stratification">Gain from stratification</h2>
<ul>
<li>Observations within strata are more similar to each other, than they are to the population as a whole</li>
<li>reduction in variance in individual strata can lead to a reduced variance for the population estimate.</li>
</ul>
<div class="callout-important callout callout-style-default no-icon callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Definition: Relative gain from stratification
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math display">\[
\frac{\hat{Var_{strata}}}{\hat{Var_{SRS}}}
\]</span></p>
</div>
</div>
<p>From the Farm example, this ratio was calculated to be 0.75. That means we would only need 0.75*300 = 225 observations from a stratified sample to obtain the same precision as from a SRS of 300.</p>
<blockquote class="blockquote">
<p>By sampling within strata, we are “borrowing” information from other similar observations.</p>
</blockquote>
</section>
<section id="closing-thoughts" class="level2">
<h2 class="anchored" data-anchor-id="closing-thoughts">closing thoughts</h2>
<ul>
<li>Don’t have to sample the same % from each strata
<ul>
<li>Could see a greater reduction in variance with an increased sampling fraction from the West.</li>
</ul></li>
</ul>
</section>
</section>
<section id="theory-of-stratified-sampling-lohr-3.2" class="level1">
<h1>Theory of Stratified Sampling (Lohr 3.2)</h1>
<section id="notation" class="level2">
<h2 class="anchored" data-anchor-id="notation">Notation</h2>
<ul>
<li><span class="math inline">\(h=1 \ldots H\)</span> strata</li>
<li>strata membership of every unit in the population</li>
<li><span class="math inline">\(y_{hj}\)</span> value of the <span class="math inline">\(j\)</span>th unit in strata <span class="math inline">\(h\)</span></li>
<li><span class="math inline">\(\sum_{j=1}^{n_{h}}\)</span> sum of <em>all</em> units in strata <span class="math inline">\(h\)</span></li>
<li><span class="math inline">\(\sum_{j}\)</span> sum over the units that were sampled from in strata <span class="math inline">\(h\)</span></li>
</ul>
<table class="table">
<colgroup>
<col style="width: 23%">
<col style="width: 38%">
<col style="width: 38%">
</colgroup>
<thead>
<tr class="header">
<th>Measure</th>
<th>Population <span class="math inline">\((\theta)\)</span></th>
<th>Sample <span class="math inline">\((\hat{\theta})\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Sample size in strata <span class="math inline">\(h\)</span></td>
<td><span class="math inline">\(N_{h}\)</span></td>
<td><span class="math inline">\(n_{h}\)</span></td>
</tr>
<tr class="even">
<td>Overall sample size</td>
<td><span class="math inline">\(N = \sum^{H}_{h=1} N_{h}\)</span></td>
<td><span class="math inline">\(n = \sum^{H}_{h=1} n_{h}\)</span></td>
</tr>
<tr class="odd">
<td>Total in strata <span class="math inline">\(h\)</span></td>
<td><span class="math inline">\(\tau_{h} = \sum_{j=1}^{N_{h}} y_{hj}\)</span></td>
<td><span class="math inline">\(\hat{\tau}_{h} = N_{h}\bar{y_h}\)</span></td>
</tr>
<tr class="even">
<td>Overall total</td>
<td><span class="math inline">\(\tau = \sum_{h=1}^{H} \tau_{h}\)</span></td>
<td><span class="math inline">\(\hat{\tau}_{str} = \sum_{h=1}^{H}N_{h}\bar{y}_{h}\)</span></td>
</tr>
<tr class="odd">
<td>Mean in strata <span class="math inline">\(h\)</span></td>
<td><span class="math inline">\(\mu_{h} = \frac{\tau_{h}}{N_{h}}\)</span></td>
<td><span class="math inline">\(\bar{y}_{h} = \frac{1}{n_{h}}\sum_{j} y_{hj}\)</span></td>
</tr>
<tr class="even">
<td>Overall mean</td>
<td><span class="math inline">\(\mu = \frac{\tau}{N}\)</span></td>
<td><span class="math inline">\(\bar{y}_{str} = \sum_{h=1}^{H} \frac{N_{h}}{N}\bar{y}_{h}\)</span></td>
</tr>
<tr class="odd">
<td>Variance</td>
<td><span class="math inline">\(\sigma_{h}^2 = \frac{1}{N_{h}-1}\sum_{j=1}^{N_{h}}(y_{hj}-\mu_{h})^2\)</span></td>
<td><span class="math inline">\(s_{h}^2 = \frac{1}{n_{h}-1}\sum_{j}(y_{hj}-\bar{y}_{h})^2\)</span></td>
</tr>
<tr class="even">
<td>Proportion<span class="math inline">\(^*\)</span></td>
<td><span class="math inline">\(p = \mu\)</span></td>
<td><span class="math inline">\(\hat{p} = \bar{y}\)</span></td>
</tr>
</tbody>
</table>
<ul>
<li><span class="math inline">\(\bar{y}_{str}\)</span> is a weighted average of the sample stratum means.</li>
</ul>
</section>
<section id="bias-and-variance-of-estimators" class="level2">
<h2 class="anchored" data-anchor-id="bias-and-variance-of-estimators">Bias and variance of estimators</h2>
<ul>
<li><p>Both are unbiased estimators <span class="math inline">\(E[\bar{y}_{str}] = \mu; E[\hat{\tau}_{str}] = \tau\)</span></p></li>
<li><p>Variance of the estimator for the total: <span class="math display">\[
\hat{V}\big(\hat{\tau}_{str}\big) = \sum_{h=1}^{H} \Big(1 - \frac{n_{h}}{N_{h}}\Big)N^{2}_{h}\frac{s^{2}_{h}}{n_{h}}
\]</span></p></li>
<li><p>Variance of the estimator for the mean <span class="math display">\[
\hat{V}\big(\bar{y}_{str}\big) = \frac{1}{N^2}\hat{V}\big(\hat{\tau}_{str}\big)
\]</span></p></li>
<li><p>Confidence intervals can be calculated as</p></li>
</ul>
<p><span class="math display">\[
\bar{y}_{str} \pm t_{\alpha/2, n-H}\sqrt{\hat{V}\big(\bar{y}_{str}\big)}
\]</span></p>
<div class="callout-tip callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Example: Estimate the total number of farm acres in 1992 (Table 3.2)
</div>
</div>
<div class="callout-body-container callout-body">
<p>The best way to understand an equation, is to try to use it to calculate a number.</p>
</div>
</div>
<ol type="1">
<li>Import the population data, and the stratified sample that the book authors use.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(here); <span class="fu">library</span>(tidyverse)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>agpop <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="fu">here</span>(<span class="st">"data"</span>, <span class="st">"agpop.csv"</span>))</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>agstrat <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="fu">here</span>(<span class="st">"data"</span>, <span class="st">"agstrat.csv"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>To keep my data frame simple, I am going to create a new data set <code>farm92</code> that only contains the <span class="math inline">\(y\)</span> value of interest, <code>acres92</code>, and the stratification variable <code>region</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>farm92 <span class="ot">&lt;-</span> agstrat <span class="sc">%&gt;%</span> <span class="fu">select</span>(region, acres92)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol type="1">
<li>Calculate summary statistics for each region</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>(strata.summary.stats <span class="ot">&lt;-</span> farm92 <span class="sc">%&gt;%</span> </span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>   <span class="fu">group_by</span>(region) <span class="sc">%&gt;%</span> </span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>   <span class="fu">summarize</span>(<span class="at">y.bar.h =</span> <span class="fu">mean</span>(acres92),  </span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">s2.h    =</span> <span class="fu">var</span>(acres92),</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>             <span class="at">n.h     =</span> <span class="fu">n</span>()))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 4
  region y.bar.h          s2.h   n.h
  &lt;chr&gt;    &lt;dbl&gt;         &lt;dbl&gt; &lt;int&gt;
1 NC     300504.  29618183543.   103
2 NE      97630.   7647472708.    21
3 S      211315.  53587487856.   135
4 W      662296. 396185950266.    41</code></pre>
</div>
</div>
<ol start="2" type="1">
<li>Calculate Population region sizes, add this vector to the data frame created above.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>(region.size <span class="ot">&lt;-</span> agpop <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(region) <span class="sc">%&gt;%</span> <span class="fu">tally</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 2
  region     n
  &lt;chr&gt;  &lt;int&gt;
1 NC      1054
2 NE       220
3 S       1382
4 W        422</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>strata.summary.stats<span class="sc">$</span>N.h <span class="ot">&lt;-</span> region.size<span class="sc">$</span>n</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>strata.summary.stats</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 5
  region y.bar.h          s2.h   n.h   N.h
  &lt;chr&gt;    &lt;dbl&gt;         &lt;dbl&gt; &lt;int&gt; &lt;int&gt;
1 NC     300504.  29618183543.   103  1054
2 NE      97630.   7647472708.    21   220
3 S      211315.  53587487856.   135  1382
4 W      662296. 396185950266.    41   422</code></pre>
</div>
</div>
<ol start="3" type="1">
<li>Calculate the sample total <span class="math inline">\(\hat{\tau}_{h} = N_{h}\bar{y_h}\)</span>.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>strata.summary.stats<span class="sc">$</span>tau.hat.h <span class="ot">&lt;-</span> strata.summary.stats<span class="sc">$</span>y.bar.h <span class="sc">*</span> strata.summary.stats<span class="sc">$</span>N.h</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>strata.summary.stats</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 6
  region y.bar.h          s2.h   n.h   N.h  tau.hat.h
  &lt;chr&gt;    &lt;dbl&gt;         &lt;dbl&gt; &lt;int&gt; &lt;int&gt;      &lt;dbl&gt;
1 NC     300504.  29618183543.   103  1054 316731380.
2 NE      97630.   7647472708.    21   220  21478558.
3 S      211315.  53587487856.   135  1382 292037391.
4 W      662296. 396185950266.    41   422 279488706.</code></pre>
</div>
</div>
<ol start="4" type="1">
<li>Calculate the within-strata variance of this total <span class="math inline">\(\Big(1 - \frac{n_{h}}{N_{h}}\Big)N^{2}_{h}\frac{s^{2}_{h}}{n_{h}}\)</span>.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>strata.summary.stats <span class="ot">&lt;-</span> strata.summary.stats <span class="sc">%&gt;%</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">var.tau.hat.h =</span> </span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>           (<span class="dv">1</span> <span class="sc">-</span> n.h<span class="sc">/</span>N.h)<span class="sc">*</span>(N.h<span class="sc">^</span><span class="dv">2</span>)<span class="sc">*</span>(s2.h<span class="sc">/</span>n.h)</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>strata.summary.stats</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 7
  region y.bar.h          s2.h   n.h   N.h  tau.hat.h var.tau.hat.h
  &lt;chr&gt;    &lt;dbl&gt;         &lt;dbl&gt; &lt;int&gt; &lt;int&gt;      &lt;dbl&gt;         &lt;dbl&gt;
1 NC     300504.  29618183543.   103  1054 316731380.       2.88e14
2 NE      97630.   7647472708.    21   220  21478558.       1.59e13
3 S      211315.  53587487856.   135  1382 292037391.       6.84e14
4 W      662296. 396185950266.    41   422 279488706.       1.55e15</code></pre>
</div>
</div>
<ol start="5" type="1">
<li>Calculate the overall total <span class="math inline">\(\hat{\tau}_{str}\)</span> and variance <span class="math inline">\(\hat{V}\big(\hat{\tau}_{str}\big)\)</span> by summing these values across the strata.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>(tau.hat.str <span class="ot">&lt;-</span> <span class="fu">sum</span>(strata.summary.stats<span class="sc">$</span>tau.hat.h))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 909736035</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>(V.tau.hat.str <span class="ot">&lt;-</span> <span class="fu">sum</span>(strata.summary.stats<span class="sc">$</span>var.tau.hat.h))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.541899e+15</code></pre>
</div>
</div>
<p>The estimated total number of acres devoted to farming is 909,736,035, with standard error 50,417,248. These numbers match those found in Table 3.2.</p>
<p>We can then use these totals to get <span class="math inline">\(\bar{y}_{str}\)</span> and <span class="math inline">\(\hat{V}\big(\bar{y}_{str}\big)\)</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>(y.bar.str <span class="ot">&lt;-</span> tau.hat.str <span class="sc">/</span> <span class="fu">sum</span>(strata.summary.stats<span class="sc">$</span>N.h))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 295560.8</code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>(V.y.bar.str <span class="ot">&lt;-</span> V.tau.hat.str <span class="sc">/</span> (<span class="fu">sum</span>(strata.summary.stats<span class="sc">$</span>N.h)<span class="sc">^</span><span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 268300231</code></pre>
</div>
</div>
<p>We estimate the average number of acres devoted to farming per county as 295,560.8 with standard error 16,379.87. These numbers match those found in the text below Table 3.2.</p>
</section>
</section>
<section id="sampling-weights-lohr-3.3" class="level1">
<h1>Sampling Weights (Lohr 3.3)</h1>
<ul>
<li><p>Weights are still the inverse of the inclusion probability, but there may be different inclusion probabilities in different strata.</p>
<ul>
<li>So weights are not the same for all units</li>
</ul></li>
<li><p><span class="math inline">\(w_{hj} = \frac{N_h}{n_h}\)</span></p>
<ul>
<li>This makes sense because <span class="math inline">\(w_{i} = \frac{N}{n}\)</span> in a SRS, and in stratified sampling we do a SRS within each strata <span class="math inline">\(h\)</span>. So the weights are the ratio of pop/sample size within strata.</li>
</ul></li>
<li><p>Estimator for pop’n total can be written as: <span class="math display">\[
\hat{\tau}_{str} = \sum_{h=1}^{H}\sum_{j}w_{hj}y_{hj}
\]</span></p></li>
<li><p>Reminder: Sampling weights can be thought of as the number of units in the pop’n represented by each sample member.</p></li>
</ul>
<div class="callout-tip callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Example Figure 3.2
</div>
</div>
<div class="callout-body-container callout-body">
<p><img src="../figs/fig3_2.jpg" class="img-fluid"></p>
</div>
</div>
<ul>
<li>Stratum 1 has <span class="math inline">\(N_{1}=20\)</span> and <span class="math inline">\(n_{1} = 10\)</span>, so each sampled unit counts for 2 population units.</li>
<li>Stratum 3 has <span class="math inline">\(N_{3} = 420\)</span> and <span class="math inline">\(n_{3} = 20\)</span>, so each sampled unit counts for 21 population units.</li>
</ul>
<div class="callout-tip callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Example: Re-Estimate the total number of farm acres in 1992 using sample weights
</div>
</div>
<div class="callout-body-container callout-body">
<p>The weights need to be applied to the individual data points, <span class="math inline">\(y_{jh}\)</span>, then all the above calculations can occur again.</p>
<ol type="1">
<li>Calculate stratum weights</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>strat.weights <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">region =</span> <span class="fu">table</span>(agpop<span class="sc">$</span>region) <span class="sc">%&gt;%</span> <span class="fu">names</span>(),</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">N.h =</span> <span class="fu">table</span>(agpop<span class="sc">$</span>region) <span class="sc">%&gt;%</span> <span class="fu">as.vector</span>(), </span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">n.h =</span> <span class="fu">table</span>(agstrat<span class="sc">$</span>region) <span class="sc">%&gt;%</span> <span class="fu">as.vector</span>()</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>strat.weights<span class="sc">$</span>wt <span class="ot">&lt;-</span> strat.weights<span class="sc">$</span>N.h <span class="sc">/</span> strat.weights<span class="sc">$</span>n.h</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>strat.weights</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  region  N.h n.h       wt
1     NC 1054 103 10.23301
2     NE  220  21 10.47619
3      S 1382 135 10.23704
4      W  422  41 10.29268</code></pre>
</div>
</div>
<ol start="2" type="1">
<li>Merge those weights back onto the data, joining by region.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>agpop <span class="ot">&lt;-</span> agpop <span class="sc">%&gt;%</span> <span class="fu">left_join</span>(strat.weights)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(agpop<span class="sc">$</span>wt)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
10.2330097087379  10.237037037037 10.2926829268293 10.4761904761905 
            1054             1382              422              220 </code></pre>
</div>
</div>
<ol start="3" type="1">
<li>Calculate the weighted values <span class="math inline">\(w_{hj}y_{hj}\)</span></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>agpop<span class="sc">$</span>wtd.acres92 <span class="ot">&lt;-</span> agpop<span class="sc">$</span>acres92 <span class="sc">*</span> agpop<span class="sc">$</span>wt </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol start="4" type="1">
<li>Recalculate weighted mean and variances within strata. Also re-merge the <code>strat.weights</code> data back onto this summary so we can calculate the within strata variance.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>wt.str.sum.stats <span class="ot">&lt;-</span> agpop <span class="sc">%&gt;%</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>   <span class="fu">group_by</span>(region) <span class="sc">%&gt;%</span> </span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>   <span class="fu">summarize</span>(<span class="at">y.bar.h =</span> <span class="fu">mean</span>(wtd.acres92),  </span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">s2.h    =</span> <span class="fu">var</span>(wtd.acres92))</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>(wt.str.sum.stats <span class="ot">&lt;-</span> wt.str.sum.stats <span class="sc">%&gt;%</span> <span class="fu">left_join</span>(strat.weights) )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 6
  region  y.bar.h    s2.h   N.h   n.h    wt
  &lt;chr&gt;     &lt;dbl&gt;   &lt;dbl&gt; &lt;int&gt; &lt;int&gt; &lt;dbl&gt;
1 NC     3335459. 7.71e12  1054   103  10.2
2 NE      949342. 6.91e11   220    21  10.5
3 S      2038608. 6.24e12  1382   135  10.2
4 W      7445150. 7.40e13   422    41  10.3</code></pre>
</div>
</div>
<ol start="5" type="1">
<li>Re-calculate <span class="math inline">\(\hat{\tau}_{h}\)</span> and <span class="math inline">\(\hat{V}(\hat{\tau}_{h})\)</span>.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>wt.str.sum.stats <span class="ot">&lt;-</span> wt.str.sum.stats <span class="sc">%&gt;%</span> </span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">tau.hat.h =</span> y.bar.h <span class="sc">*</span> N.h, </span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">var.tau.hat.h =</span> (<span class="dv">1</span> <span class="sc">-</span> n.h<span class="sc">/</span>N.h)<span class="sc">*</span>(N.h<span class="sc">^</span><span class="dv">2</span>)<span class="sc">*</span>(s2.h<span class="sc">/</span>n.h))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol start="6" type="1">
<li>Re-calculate the overall total <span class="math inline">\(\hat{\tau}_{str}\)</span> and variance <span class="math inline">\(\hat{V}\big(\hat{\tau}_{str}\big)\)</span> by summing these values across the strata.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>(tau.hat.str <span class="ot">&lt;-</span> <span class="fu">sum</span>(wt.str.sum.stats<span class="sc">$</span>tau.hat.h))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 9683638877</code></pre>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>(V.tau.hat.str <span class="ot">&lt;-</span> <span class="fu">sum</span>(wt.str.sum.stats<span class="sc">$</span>var.tau.hat.h))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4.461667e+17</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>Hmmm….. something isn’t right here.</p>
</blockquote>
<div class="callout-warning callout callout-style-default no-icon callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
<span class="emoji" data-emoji="star">⭐</span> You try it.
</div>
</div>
<div class="callout-body-container callout-body">
<p>Calculate the strata weights for the caribou example from Table 3.4, and re-estimate the total number of caribou using these weights.</p>
</div>
</div>
<section id="selecting-a-stratified-random-sample" class="level1">
<h1>Selecting a Stratified Random Sample</h1>
<section id="using-base-r" class="level2">
<h2 class="anchored" data-anchor-id="using-base-r">Using Base R</h2>
</section>
<section id="using-the-strata-function-from-the-sampling-package" class="level2">
<h2 class="anchored" data-anchor-id="using-the-strata-function-from-the-sampling-package">Using the <code>strata</code> function from the <code>sampling</code> package</h2>
<ol type="1">
<li>Sort the data by the stratification variable</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>agpop.sorted <span class="ot">&lt;-</span> agpop <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(region)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol start="2" type="1">
<li>Specify the desired within-strata sample sizes <span class="math inline">\(n_{k}\)</span>. The different methods on how to allocate sample sizes to strata is covered in the next section.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>n.k <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">103</span>, <span class="dv">21</span>, <span class="dv">135</span>, <span class="dv">41</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol start="3" type="1">
<li>Create the sampling index of records to select using the <code>strata</code> function with arguments specifying the strata names, strata size, and sampling method within strata.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>strat.idx <span class="ot">&lt;-</span> sampling<span class="sc">::</span><span class="fu">strata</span>(<span class="at">data =</span> agpop.sorted, <span class="at">stratanames =</span> <span class="st">"region"</span>, </span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>                    <span class="at">size =</span> n.k, <span class="at">method =</span> <span class="st">"srswor"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><span class="emoji" data-emoji="warning">⚠️</span> Package conflicts can occur with the <code>strata</code> function. If it is not working for you, use the <code>sampling::strata</code> method of calling the function to ensure you are using the correct version of the <code>strata</code> function from the <code>sampling</code> package.</p>
<ol start="4" type="1">
<li>Extract the data records that correspond to the sampling index.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>ag.str <span class="ot">&lt;-</span> <span class="fu">getdata</span>(agpop.sorted, strat.idx)</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(ag.str)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             county state acres92 acres87 acres82 farms92 farms87 farms82
2      ADAMS COUNTY    IA  239800  243607  254071     643     688     737
6     BENTON COUNTY    IA  427215  419480  441810    1325    1434    1585
12    BUTLER COUNTY    IA  315448  328114  336000    1146    1294    1467
13   CALHOUN COUNTY    IA  345567  342160  351373     899     992    1164
28  DELAWARE COUNTY    IA  336131  353940  351861    1367    1452    1481
30 DICKINSON COUNTY    IA  202249  211002  227557     554     593     652
   largef92 largef87 largef82 smallf92 smallf87 smallf82  N.h n.h       wt
2        38       32       21       40       50       33 1054 103 10.23301
6        56       43       34      101      105      102 1054 103 10.23301
12       32       23       21      116      129      139 1054 103 10.23301
13       58       35       28       71       61       78 1054 103 10.23301
28       25       22       15      112      105       95 1054 103 10.23301
30       30       34       31       38       47       43 1054 103 10.23301
   wtd.acres92 region ID_unit       Prob Stratum
2      2453876     NC       2 0.09772296       1
6      4371695     NC       6 0.09772296       1
12     3227982     NC      12 0.09772296       1
13     3536190     NC      13 0.09772296       1
28     3439632     NC      28 0.09772296       1
30     2069616     NC      30 0.09772296       1</code></pre>
</div>
</div>
<ol start="5" type="1">
<li>Calculate the sampling weights using the inclusion probabilities (these were created as the variable <code>Prob</code> when you used the <code>strata</code> function)</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>ag.str<span class="sc">$</span>wt <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">/</span>ag.str<span class="sc">$</span>Prob</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(ag.str)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             county state acres92 acres87 acres82 farms92 farms87 farms82
2      ADAMS COUNTY    IA  239800  243607  254071     643     688     737
6     BENTON COUNTY    IA  427215  419480  441810    1325    1434    1585
12    BUTLER COUNTY    IA  315448  328114  336000    1146    1294    1467
13   CALHOUN COUNTY    IA  345567  342160  351373     899     992    1164
28  DELAWARE COUNTY    IA  336131  353940  351861    1367    1452    1481
30 DICKINSON COUNTY    IA  202249  211002  227557     554     593     652
   largef92 largef87 largef82 smallf92 smallf87 smallf82  N.h n.h       wt
2        38       32       21       40       50       33 1054 103 10.23301
6        56       43       34      101      105      102 1054 103 10.23301
12       32       23       21      116      129      139 1054 103 10.23301
13       58       35       28       71       61       78 1054 103 10.23301
28       25       22       15      112      105       95 1054 103 10.23301
30       30       34       31       38       47       43 1054 103 10.23301
   wtd.acres92 region ID_unit       Prob Stratum
2      2453876     NC       2 0.09772296       1
6      4371695     NC       6 0.09772296       1
12     3227982     NC      12 0.09772296       1
13     3536190     NC      13 0.09772296       1
28     3439632     NC      28 0.09772296       1
30     2069616     NC      30 0.09772296       1</code></pre>
</div>
</div>
<p>5b. Check that the sampling weights sum to the stratum population sizes.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>ag.str <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(region) <span class="sc">%&gt;%</span> <span class="fu">summarize</span>(<span class="at">sum.wts =</span> <span class="fu">sum</span>(wt))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 2
  region sum.wts
  &lt;chr&gt;    &lt;dbl&gt;
1 NC        1054
2 NE         220
3 S         1382
4 W          422</code></pre>
</div>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(agpop.sorted<span class="sc">$</span>region)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  NC   NE    S    W 
1054  220 1382  422 </code></pre>
</div>
</div>
<div class="callout-important callout callout-style-default no-icon callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body">
<p>If they do not sum to the stratum population sizes, you have made a mistake somewhere in the calculations for the weights or strata sizes.</p>
</div>
</div>
</section>
</section>
<section id="computing-statistics-from-a-stratified-random-sample" class="level1">
<h1>Computing Statistics from a Stratified Random Sample</h1>
<section id="setup-the-information-for-the-survey-design." class="level2">
<h2 class="anchored" data-anchor-id="setup-the-information-for-the-survey-design.">Setup the information for the survey design.</h2>
<section id="specify-weights" class="level3">
<h3 class="anchored" data-anchor-id="specify-weights">Specify weights</h3>
<p>We created the weights in the dataset in the the last step.</p>
</section>
<section id="specify-fpc" class="level3">
<h3 class="anchored" data-anchor-id="specify-fpc">Specify fpc</h3>
<p>We need to create a vector of fpc’s that are equal to the strata population size. In a SRS, we used <code>fpc = rep(N,n)</code>. This create a vector that contains the value <code>N</code>, repeated <code>n</code> times. In this case, we need to match the strata population size to each record from that strata.</p>
<p>Option 1: Create a vector that repeats the values in the vector <code>N.k</code>, each <code>n.k</code> times. :::{.callout-tip icon=true} #### Example</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>ex.N.k <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">10</span>,<span class="dv">25</span>,<span class="dv">50</span>) <span class="co"># example population sizes</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>ex.n.k <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">5</span>,<span class="dv">10</span>)   <span class="co"># example strata sizes</span></span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a><span class="fu">rep</span>(ex.N.k, ex.n.k)   </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 10 10 25 25 25 25 25 50 50 50 50 50 50 50 50 50 50</code></pre>
</div>
</div>
<p>The pop size for stratum 1 is repeated twice (the size of the sample from that stratum), the pop size for stratum 2 is repeated 5 times (the sample size for stat stratum) etc.</p>
</section>
</section>
</section>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>option1.fpc <span class="ot">&lt;-</span> <span class="fu">rep</span>(N.k, n.k)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-error">
<pre><code>Error in eval(expr, envir, enclos): object 'N.k' not found</code></pre>
</div>
</div>
<p>Option 2: Merge the pop sizes onto the sample data using <code>region</code> as a joining key</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>(pop.strata.sizes <span class="ot">&lt;-</span> <span class="fu">table</span>(agpop.sorted<span class="sc">$</span>region) <span class="sc">%&gt;%</span> <span class="fu">data.frame</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Var1 Freq
1   NC 1054
2   NE  220
3    S 1382
4    W  422</code></pre>
</div>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>pop.strata.sizes <span class="ot">&lt;-</span> <span class="fu">rename</span>(pop.strata.sizes, <span class="at">region =</span> Var1, <span class="at">popsize =</span> Freq)</span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>ag.str.opt2 <span class="ot">&lt;-</span> ag.str <span class="sc">%&gt;%</span> <span class="fu">left_join</span>(pop.strata.sizes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="call-svydesign" class="level3">
<h3 class="anchored" data-anchor-id="call-svydesign">Call <code>svydesign</code></h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>agpop.str.dsgn <span class="ot">&lt;-</span> <span class="fu">svydesign</span>(<span class="at">id =</span> <span class="sc">~</span><span class="dv">1</span>, <span class="at">strata =</span> <span class="sc">~</span>region, <span class="at">weights =</span> <span class="sc">~</span>wt, </span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>                            <span class="at">fpc =</span> <span class="sc">~</span>popsize, </span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>                            <span class="co"># fpc = option1.fpc # This would be Option 1</span></span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>                            <span class="at">data=</span> ag.str.opt2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="calculate-mean-se-and-ci" class="level2">
<h2 class="anchored" data-anchor-id="calculate-mean-se-and-ci">Calculate mean, SE and CI</h2>
<p>Note the degrees of freedom for a CI under a stratified sample is <span class="math inline">\(n-H\)</span>, which can be extracted from the <code>svydesign</code> object using the <code>degf</code> function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>(str.total <span class="ot">&lt;-</span> <span class="fu">svymean</span>(<span class="sc">~</span>acres92, agpop.str.dsgn))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          mean    SE
acres92 288357 17463</code></pre>
</div>
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(str.total, <span class="at">level =</span> .<span class="dv">95</span>, <span class="at">df =</span> <span class="fu">degf</span>(agpop.str.dsgn))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           2.5 %   97.5 %
acres92 253989.5 322724.7</code></pre>
</div>
</div>
<p>Compare these to our prior “hand” calculated values (and approximate 95% CI):</p>
<div class="cell">

</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">This site is built with <span class="emoji" data-emoji="heart">❤️</span>, and <a href="https://quarto.org/">Quarto</a> by <a href="www.norcalbiostat.com">Robin Donatello</a>.</div>   
  </div>
</footer>



</body></html>