project:
  type: website
  output-dir: _site
  preview:
    port: 4200
    browser: true

  
website:
  page-navigation: true
  title: "Sampling Methods"
  description: "Homepage for MATH 458 Spring 25"
  site-url: "https://sampling-458.netlify.app/"
 
  page-footer:
    #background: light
    left: "This site is built with :heart:, [R](https://posit.co/) and [Quarto](https://quarto.org/) by [Robin Donatello](www.norcalbiostat.com)"
      
  navbar: 
    pinned: true
    #background: "#654378"
    left: 
      - text: "Notes"
        file: notes.qmd
      - text: "Assignments"
        file: assignments.qmd
      - text: "HackMD Notes"
        menu: 
          # - text: "R resources"
          #   url: https://hackmd.io/@norcalbiostat/sampling_r_resources
          - text: "What is HackMD"
            url: https://hackmd.io/@norcalbiostat/458_intro_hackmd
          - text: "Ch 1. Sampling Framework"
            url: https://hackmd.io/@norcalbiostat/cn01-intro_sampling
          - text: "Foundations of Estimation"
            url: https://hackmd.io/@norcalbiostat/cn02-statistical_foundations
          # - text: "Stratified Sampling"
          #   url: https://hackmd.io/@norcalbiostat/cn06_stratified
          # - text: "Cluster Sampling"
          #   url: https://hackmd.io/@norcalbiostat/cn07_cluster
          # - text: "Ratio & Regression Estimation"
          #   url: https://hackmd.io/@norcalbiostat/cn08_ratio

        
    right: 
      - text: "Syllabus"
        file: syllabus.qmd



from: markdown+emoji
format:
  html:
    highlight-style: a11y
    theme: 
      light: sandstone
      dark: solar
    highlight: pygments
    toc: true
    code-copy: true
    code-overflow: scroll
    callout-icon: false

execute:
  freeze: auto # re-render only when source changes
  echo: true
  warning: false
  message: false
