project:
  type: website
  output-dir: _site
  preview:
    port: 4200
    browser: true

  
website:
  page-navigation: true
  title: "Sampling Methods"
  description: "Homepage for MATH 458 Spring 25"
  site-url: "https://sampling-458.netlify.app/"
 
  page-footer:
    #background: light
    left: "This site is built with :heart:, [R](https://posit.co/) and [Quarto](https://quarto.org/) by [Robin Donatello](www.norcalbiostat.com) and the Spring 2025 Math 458 class"
      
  navbar: 
    pinned: true
    #background: "#654378"
    left: 
      - text: "Notes"
        file: notes.qmd
      - text: "Assignments"
        file: assignments.qmd
      - text: "Project"
        file: project.qmd
      - text: "HackMD Notes"
        menu: 
          - text: "What is HackMD"
            url: https://hackmd.io/@norcalbiostat/458_intro_hackmd
          - text: "Ch 1. Sampling Framework"
            url: https://hackmd.io/@norcalbiostat/cn01-intro_sampling
          - text: "Ch 2. Foundations of Estimation"
            url: https://hackmd.io/@norcalbiostat/cn02-statistical_foundations
          - text: "Ch 3. Stratified Sampling"
            url: https://hackmd.io/@norcalbiostat/cn04_stratified
          - text: "Ch 5. Cluster Sampling"
            url: https://hackmd.io/@norcalbiostat/cn05_cluster
          # - text: "Ratio & Regression Estimation"
          #   url: https://hackmd.io/@norcalbiostat/cn08_ratio
      

    right: 
      - icon: google
        menu: 
          - text: Content creation group
            url: https://docs.google.com/spreadsheets/d/1Inj6xmMsoRcIHR5mpVShQisg5llXwesoDRuVRbvI5mY
          - text: Sechedule
            url: https://docs.google.com/spreadsheets/d/1f4ze0905zE4HbtEyqVrJv1ncMB4EdNZDd4QJH5wewS0
          - text: Project folder
            url: https://drive.google.com/drive/folders/13YG6_6exekRfJr2NngUCO465UosodQGA
      - file: formulas.qmd
      - text: "Syllabus"
        file: syllabus.qmd



from: markdown+emoji
format:
  html:
    highlight-style: a11y
    theme: 
      light: sandstone
      dark: solar
    highlight: pygments
    toc: true
    code-copy: true
    code-overflow: scroll
    callout-icon: false

execute:
  freeze: auto # re-render only when source changes
  echo: true
  warning: false
  message: false
