---
title: "Project"
format: 
  html: default
---

# Project Overview: Shaping the Future of Math & Data Science

This semester, you will go on a real-world project that will directly impact the future of the Mathematics and Data Science programs at Chico State. Working collaboratively as a class, you will design, implement, and analyze an alumni survey to gather valuable insights about their experiences and career paths. This is your chance to apply the sampling and statistical analysis methods you've learned in a practical and meaningful way.

This project isn't just about crunching numbers; it's about teamwork, communication, and project management. As a class you will be responsible for:

-   Defining Roles & Responsibilities: Assign yourselves specific roles within the project (e.g., survey design team, data analysis team, communication lead).
-   Task Management & Timelines: Establish clear timelines and track progress to ensure successful completion of each project phase.
-   Stakeholder Communication: Get stakeholder (Math Department faculty, Career center) input in the questions being asked.
-   Design & Implementing Multiple Sampling Frameworks: Implement multiple sampling methods (e.g., simple random, stratified, cluster) to select representative samples of alumni.
-   Data Collection & Analysis: Collect survey responses, clean the data, and perform appropriate statistical analyses to answer key research questions. You will also need to compare estimates obtained across the different sampling frameworks to assess their impact on the results.
-   Final Presentation: Present your findings and recommendations and insights to the Math Department or the assessment committee.

This is a full class collaborative effort, requiring everyone's active participation and contribution. Every student should take lead on at least one aspect or activity. Your collective efforts will provide valuable data to inform curriculum development, program improvements, and future initiatives within the Mathematics & Statistics departments. Embrace this opportunity to make a real difference!

# Milestones

1.  **Define Project Goals and Stakeholder Input:** Documented agreement on the survey's objectives and how the results will be used, based on input from stakeholders.
2.  **Literature Review and Best Practices Research:** Review of existing alumni surveys and research on best practices in survey design and implementation.
3.  **Create Sampling Frame:** A list of the target population from which the sample will be drawn.
4.  **Develop & Test Questionnaire:** Draft questionnaire, pilot testing, and revisions based on feedback.
5.  **Design Sampling Strategy:** Detailed plan for selecting the sample, including justification for the chosen method and sample size calculations.
6.  **Collect Data:** Completed survey responses. Include metrics on response rate and efforts to address non-response bias.
7.  **Data Cleaning:** Prepare the data for analysis. Screen for outliers, missing or invalid responses. Create necessary metrics. Create basic tables and summaries for each measures.
8.  **Data Analysis:** Create analysis plan, conduct analysis and compile results, create visualizations.
9.  **Final Presentation:** Presentation to stakeholders
10. **Final Report:** Comprehensive written report documenting all aspects of the project.

# Parameters to be Estimated

* Average salary expectations for 1, 2, and 5 years.
* Average time taken by alumni to secure their first job
* Proportion of alumni who found their degree valuable
* Proportion of alumni working in different career sectors
* Proportion of alumni who were accepted to or attended graduate school (mathematics oriented) or with a terminal degree
* Proportion of alumni who felt they were prepared


# Sample Size Determinations

Since most of the parameters to estimate are proportions we will determine the sample size under that framework. Our sampling frame (population size) is $N=300$. 

* We have no prior knowledge of the estimated proportions, so $\hat{p} = \hat{q} = .5$. We will use this for our estimate of $S$. 
* We will set our confidence to be 95%, thus $\alpha = .05$
* We will allow our margin of error to vary between 1% and 25%

I created a graph to plot the sample size under an SRS framework using equation 2.30, 2.31 as a function of the margin of error `e`. We can use this to make a determination of a general total sample size that we will aim for in each of the sampling designs. 

```{r}
srs.n <- function(e){
  n0 <- 1.96^2 / (4*e^2)
  n <- n0 / (1+n0/300)
  return(n)
}
e <- seq(.01, .25, by = .01)
plot(e, srs.n(e), type = "l")

srs.n(seq(.05, .25, by = .05))

```





