---
title: "Syllabus"
format: 
  html: default
  pdf: default
---


# Course Information

_The theory and application of survey sampling techniques. Topics include simple random sampling, stratified sampling, systematic sampling, and cluster sampling. Appropriate for mathematics, computer science, psychology, social science, agriculture, biology, and other majors. _


## Instructor
* **Name & pronouns:** Dr. Robin Donatello  (Dr. D, she/her)
* **Website:** [https://www.norcalbiostat.com/](https://www.norcalbiostat.com/)
* **Office Location:** Holt 202
* **E-mail:** rdonatello@csuchico.edu
* **Best Contact Method:** Discord
* **Student Office Hours:** TBD

## Logistics
* **Meeting Pattern:** MW 4-5:15, Holt 155
* **Prerequisites:** MATH 314, MATH 315, or MATH 351 (may be taken concurrently)  
* **Mode of Instruction:** In Person.   


# Schedule of Topics

We will tentatively cover the following sections and topics:

* Writing functions in R; Simulation; Sampling Distributions
* Introduction to Sampling 
* Statistical Estimation
* Simple Random Sampling 
* Stratified Random Sampling 
* Cluster Sampling 
* Ratio & Regression Estimation 


----

# Required materials and accounts

* **Class website**: https://sampling-458.netlify.app/
* **Textbook (Required)**: [Sampling, 3rd Edition. Sharon Lohr](https://www.sharonlohr.com/sampling-design-and-analysis-3e)
* **Laptop & Internet**: Expect to bring your laptop to class every day. Contact me if this poses a problem or concern for you. Contact ITSS for help with internet. 
* **Data Analysis software**: R & R Studio, Quarto
* **Canvas**: Module overview, assignments, gradebook, calendar. 
* **Discord**: A free discussion platform with a lot of collaborative functionality. 
* **Hack MD**: A markdown based method for real time collaborative notes

Instructions for signing up & obtaining materials are in HW 0

----

# Assignments / graded items 

Below is a summary of the graded items for the class and their weights towards the final grade. Automatic half credit will be applied to any graded assignment submitted after the solutions are posted.  I use a standard grade cutoff of 100-90%: A, 89-80%: B, 79-70%: C, 69-60%: D, 0-59%: F  


**Exams (20%)**

* 2 Exams (midterm/final, not cumulative). 
* Error Assessment available for the midterm. (Details TBD)

**Homework Assignments (20%)**

* Written homework assignments on the topics listed above. These may take multiple days to complete. 

**Worksheets (10%)**

* In class worksheets. The intent is to work together and finish them that day, but you'll have until the beginning of the next class period to turn it in. 

**Applied Project (20%)**

* Design a data collection tool & method, collect and analyze the desired data, and report your findings. 

**Notes (20%)**

* **Taking notes**
    - The course notes are available on the class website. What is presented in class will be incomplete, and we will work through them during class. 
    - I will provide you with an incomplete version of the course notes that we will go through in class together. You are responsible for filling out during and after class.
    - You will compile these notes to PDF and submit for review on a regular basis, typically a few days after the module is complete. 
    - After the note submission date I will update the online posted notes with the completed versions.
    - These are graded on completion status. 

* **Creating Notes**
    - The structure and format will be guided by me you will work collaboratively with the class to read the textbook and _create_ your own set of notes for certain topics. 
    - These require strong team based collaboration and accountability, and so will be subject to peer feedback. 
    - Once compiled together, these notes will go onto the course website

**Participation (10%)**
  - Self and peer evaluations
  - Discussion board posts
  - Generally being helpful over Discord to your classmates


----

# Class Policies and statements

## Everyone is welcome here

It is my intent that students from all diverse backgrounds and perspectives be well-served by this course, that students' learning needs be addressed both in and out of class, and that the diversity that the students bring to this class be viewed as a resource, strength and benefit. It is my intent to present materials and activities that are respectful of diversity: gender identity, sexuality, disability, age, socioeconomic status, ethnicity, race, nationality, religion, and culture. Your suggestions are encouraged and appreciated. Please let me know ways to improve the effectiveness of the course for you personally, or for other students or student groups.

I would like to create a learning environment that supports a diversity of thoughts, perspectives and experiences, and honors your identities (including race, gender, class, sexuality, religion, ability, etc.) To help accomplish this:

-  Let me know if you have a name and/or set of pronouns that differ from those that appear in your official Chico records. I make it a point to call on people by name, so please make sure that I know what you want to be called. 
        - I also want to try to pronounce your name as accurately as possible. The more you help and correct me the better I can do to honor your name. 
-   If you feel like your performance in the class is being impacted by your experiences outside of class, please don't hesitate to come and talk with me. I want to be a resource for you. Remember that you can also submit anonymous feedback using the feedback button on the schedule and help pages of the website (which will lead to me making a general announcement to the class, if necessary to address your concerns).
-   If you prefer to speak with someone outside of the course, the Office of Diversity and Inclusion is here to assist. Their number is 530-898-4764, and email [diversityoffice\@csuchico.edu](mailto:diversityoffice@csuchico.edu){.email}
-   I (like many people) am still in the process of learning about diverse perspectives and identities. If something was said in class (by anyone) that made you feel uncomfortable, please talk to me about it. (Again, anonymous feedback is always an option).

*Adapted from [Monica Linden at Brown University](https://www.brown.edu/sheridan/teaching-learning-resources/inclusive-teaching/statements)*.

Furthermore, I would like to acknowledge that Chico State stands on lands that were originally occupied by the first people of this area, the Mechoopda. I recognize their distinctive spiritual relationship with this land and the waters that run through campus. I am humbled that our campus resides upon sacred lands that once sustained the Mechoopda people for centuries.


## Attendance

All students are expected to attend class in person each session. 

Talk to me ahead of time if you need to miss a class for a planned reason. In the event of an unplanned reason, DM me in Discord and let's see if we can zoom you in for that day. 

* If you are not feeling well or are experiencing COVID symptoms **DO NOT COME TO CLASS**. DM me in Discord we'll make a backup plan. 



## Late work

Automatic half credit will be applied to any graded assignment submitted after the solutions are posted. 

I also prioritize on time submissions. If you submit an assignment after I'm done grading everyone elses, and we're moving on to the next topic then your assignment will have to wait a while before I get to it. 


## Collaboration 

### With people

* A big part of this class is collaborative note _creating_.
* We will talk more about being responsible and accountable to each other next week.  
* Collaboration on assignments is encouraged. People learn better when they have someone else to talk through concepts and debugging with. However your submitted work must represent **your personal effort** on all parts. 
* Collaboration on exams is not allowed.


### With AI

As an instructor I recognize there are a variety of AI programs available to assist in creating text and writing code. However, I want to stress that, AI programs are not a replacement for human creativity, originality, and critical thinking. Writing (text and code) is a skill that you must nurture over time in order to develop your own individual voice, style, and view.  

* You are not allowed to use AI to help you write text. 
* Don't immediately turn to Chat GPT to help you figure something out. Ask your classmates first. 
* You can use ChatGPT/AI tools **to help you learn**, but the work you submit must be your own. 
* You are expected to use the coding functions and style presented in the class. 
* There is no short cut to learning. You must put in effort. 
* I reserve the right to assign 0 points on any graded item that I suspect has been written or coded by AI


:::{.callout-important}
### Not allowed

* Working with or getting help from others on exams and individual quizzes 
* Copying code from another student's homework and presenting it as your own work.
* Copy/paste from AI tools or internet sources without customization, citation or explanation 
* Getting your sibling/friend/colleague to write code for you
* Submitting any assignment that is not your own personal effort. 
:::


:::{.callout-tip}
### Allowed
* Helping each other solve homework problems (concepts or code)
* Use AI to help explain a concept or an error message
* Copy/paste code from my course notes (this is actually encouraged!)
:::


If at any time I suspect that the work you are submitting is not reflective of your personal knowledge I may ask you to verbally explain a piece of code to me. If your explanation is insufficient may result in a 0 on that assignment. 

Any use outside of this permission constitutes a violation of Chico State's Integrity Policy and may result in you being reported to the Office of Students Rights and Responsibilities.

----

# Campus Resources

## Chico State Basic Needs Project

The **Hungry Wildcat Food Pantry** provides supplemental food, fresh produce, CalFresh application assistance and basic needs referral services for students experiencing food and housing insecurity.

All students are welcomed to visit the Pantry located in the Student Service Center 196, open Monday-Friday

Please visit the Chico State Basic Needs website [http://www.csuchico.edu/basic-needs](http://www.csuchico.edu/basic-needs) for more information.



## Americans with Disabilities Act

If you need course adaptations or accommodations because of a disability or chronic illness, or if you need to make special arrangements in case the building must be evacuated, please make an appointment with me as soon as possible, or see me during office hours. Please also contact Accessibility Resource Center (ARC) as they are the designated department responsible for approving and coordinating reasonable accommodations and services for students with disabilities. ARC will help you understand your rights and responsibilities under the Americans with Disabilities Act and provide you further assistance with requesting and arranging accommodations. We try our best to ensure equal access to materials in accessible formats. Reach out to your me if there is some aspect of the course materials that are inaccessible to you.

Accessibility Resource Center 530-898-5959 Student Services Center 170 [arcdept\@csuchico.edu](mailto:arcdept@csuchico.edu){.email} [http://www.csuchico.edu/arc](https://www.csuchico.edu/arc/)

----

# University Policies

## Adding and Dropping the course

You are responsible for understanding the policies and procedures about add/drops, academic renewal, etc., found in the [CSU Chico University Catalog](http://www.csuchico.edu/catalog/). You should be aware of the new deadlines and penalties for adding and dropping classes.

## Confidentiality and Mandatory Reoprting

As an instructor, one of my responsibilities is to help create a safe learning environment on our campus. I also have a mandatory reporting responsibility related to my role as a your instructor. I am required to share information regarding sexual misconduct with the University. Students may speak to someone confidentially by contacting the Counseling and Wellness Center (898-6345) or Safe Place (898-3030). Information on campus reporting obligations and other Title IX related resources are available here: www.csuchico.edu/title-ix.

## Academic Integrity

Academic integrity is defined as "a commitment, even in the face of adversity, to five fundamental values: honesty, trust, fairness, respect, and responsibility". From these values flow principles of behavior that enable academic communities to translate ideals to action. Academic integrity is expected and required. No forms of cheating or plagiarism will be tolerated. Please see your student handbook at https://www.csuchico.edu/scrr/integrity.shtml if you have questions about the meaning of these terms or the consequences of violating academic integrity.
    