<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.555">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2025-02-03">
<meta name="description" content="We cover the theoretical concepts of statistical estimation.">

<title>Sampling Methods - Foundations of Statistical Estimation</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Sampling Methods</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../notes.html"> 
<span class="menu-text">Notes</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../assignments.html"> 
<span class="menu-text">Assignments</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../project.html"> 
<span class="menu-text">Project</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-hackmd-notes" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">HackMD Notes</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-hackmd-notes">    
        <li>
    <a class="dropdown-item" href="https://hackmd.io/@norcalbiostat/458_intro_hackmd">
 <span class="dropdown-text">What is HackMD</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://hackmd.io/@norcalbiostat/cn01-intro_sampling">
 <span class="dropdown-text">Ch 1. Sampling Framework</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://hackmd.io/@norcalbiostat/cn02-statistical_foundations">
 <span class="dropdown-text">Ch 2. Foundations of Estimation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://hackmd.io/@norcalbiostat/cn04_stratified">
 <span class="dropdown-text">Ch 3. Stratified Sampling</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-bi-google" role="button" data-bs-toggle="dropdown" aria-expanded="false">
      <i class="bi bi-google" role="img">
</i> 
 <span class="menu-text"></span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-bi-google">    
        <li>
    <a class="dropdown-item" href="https://docs.google.com/spreadsheets/d/1Inj6xmMsoRcIHR5mpVShQisg5llXwesoDRuVRbvI5mY">
 <span class="dropdown-text">Content creation group</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://docs.google.com/spreadsheets/d/1f4ze0905zE4HbtEyqVrJv1ncMB4EdNZDd4QJH5wewS0">
 <span class="dropdown-text">Sechedule</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://drive.google.com/drive/folders/13YG6_6exekRfJr2NngUCO465UosodQGA">
 <span class="dropdown-text">Project folder</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../formulas.html"> 
<span class="menu-text">Formulas and Definitions</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../syllabus.html"> 
<span class="menu-text">Syllabus</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#expected-values" id="toc-expected-values" class="nav-link" data-scroll-target="#expected-values">Expected Values</a></li>
  <li><a href="#the-finite-population-case" id="toc-the-finite-population-case" class="nav-link" data-scroll-target="#the-finite-population-case">The Finite Population Case</a></li>
  <li><a href="#variability-of-estimates" id="toc-variability-of-estimates" class="nav-link" data-scroll-target="#variability-of-estimates">Variability of Estimates</a></li>
  <li><a href="#properties-of-estimators" id="toc-properties-of-estimators" class="nav-link" data-scroll-target="#properties-of-estimators">Properties of Estimators</a></li>
  <li><a href="#interval-estimation" id="toc-interval-estimation" class="nav-link" data-scroll-target="#interval-estimation">Interval Estimation</a>
  <ul class="collapse">
  <li><a href="#standard-error" id="toc-standard-error" class="nav-link" data-scroll-target="#standard-error">Standard Error</a></li>
  <li><a href="#confidence-intervals" id="toc-confidence-intervals" class="nav-link" data-scroll-target="#confidence-intervals">Confidence Intervals</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Foundations of Statistical Estimation</h1>
</div>

<div>
  <div class="description">
    We cover the theoretical concepts of statistical estimation.
  </div>
</div>


<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">February 3, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p><a href="../_blank_notes/cn03-SRS_blank.qmd">cn03 Blank notes file</a></p>
<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>In this section we review the basic concepts underlying the selection of an estimator of a population parameter, the method for evaluating its goodness, and the concepts involved in interval estimation. Because the bias and the variance of estimators determine their goodness, we need to review the basic ideas concerned with the expectation and variance of a random variable. This set of notes follows Lohr 2.2</p>
<div class="callout callout-style-simple callout-note no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p><em>Reminder: Most people come into this class with different pre-requisite classes and instructors. This recap helps ensure that we are all on the same page with concepts and notation that may be new for some.</em></p>
<p>These notes require the <code>StatisticsPhD.csv</code> data file. <span class="margin-aside">I don’t feel like loading packages in this file so I’m using the <code>::</code> shortcut method to access the <code>here</code> and <code>read_csv</code> functions to load in the data.</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>stat.phd <span class="ot">&lt;-</span> readr<span class="sc">::</span><span class="fu">read_csv</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"data"</span>, <span class="st">"StatisticsPhD.csv"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
<p>Statistical inference centers around using information from a sample to understand what might be true about the entire population of interest. If all we see are the data in the sample, what conclusions can we draw about the population? How sure are we about the accuracy of those conclusions?</p>
<p>On April 29, 2011, Prince William married Kate Middleton in London. The Pew Research Center reports that 34% of US adults watched some or all of the royal wedding. How do we know that 34% of all US adults watched? Did anyone ask <strong>you</strong> if you watched it? In order to know for sure what proportion of US adults watched the wedding, we would need to ask <strong>all</strong> US adults whether or not they watched. This would be very difficult to do. As we will see, however, we can estimate the <em>population</em> proportion <em>parameter</em> quite accurately with a <em>sample statistic</em>, as long as we use a random sample. In the case of the royal wedding, the estimate is based on a poll using a random sample of 1006 US adults.</p>
<ul>
<li><em>Statistical inference</em>: The process of drawing conclusions about the entire population based on the information in the sample.</li>
<li><em>Parameter</em>: A number that describes the entire population. <span class="math inline">\(\mu\)</span>, <span class="math inline">\(p\)</span>, <span class="math inline">\(\tau\)</span></li>
<li><em>Statistic</em>: A number calculated from a sample. <span class="math inline">\(\bar{x}\)</span>, <span class="math inline">\(\hat{p}\)</span>, <span class="math inline">\(\hat{\tau}\)</span>.</li>
</ul>
<p>Generally our goal is to know the value of the population parameter exactly but this usually isn’t possible since we usually cannot collect information from the entire population.</p>
<p>Instead we can select a sample from the population, calculate the quantity of interest for the sample, and use this sample statistic to estimate the value for the whole population.</p>
<div class="callout callout-style-default callout-warning no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
⭐ You try it
</div>
</div>
<div class="callout-body-container callout-body">
<p>The US Census states that 27.5% of US adults who are at least 25 years old have a college bachelor’s degree or higher. Suppose that in a random sample of <span class="math inline">\(n\)</span>=200 US residents who are 25 or older, 58 of them have a college bachelor’s degree or higher.</p>
<p>What is the population parameter? What is the sample statistic? Use correct notation for your answer.</p>
</div>
</div>
<div class="callout callout-style-simple callout-warning no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Population Parameter</strong>: <span class="math inline">\(p = .275\)</span><br>
<strong>Sample Statistic</strong>: <span class="math inline">\(\hat{p} = 58/200 = .29\)</span></p>
</div>
</div>
</div>
<p>The value of a statistic for a particular sample gives a <em>point estimate</em> of the population parameter. If we only have the one sample and don’t know the value of the population parameter, this point estimate is our best estimate of the true value of the population parameter.</p>
<p>After we have a little more mathematical terminology and foundation, we’ll come back to what we mean by “best estimate”, and examine how we can determine if something is a “good” estimate.</p>
<hr>
</section>
<section id="expected-values" class="level1">
<h1>Expected Values</h1>
<p>Generally we want to understand some measured characteristic <span class="math inline">\(y\)</span> about the units in the population.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Example: University parking garages
</div>
</div>
<div class="callout-body-container callout-body">
<p>Consider the population of 4 universities <span class="math inline">\(U\)</span> in the North State (Humboldt, Chico, Sac, Davis), and we are interested in knowing the total number of campus owned parking garages at these campuses.</p>
<p><span class="math display">\[
U = \{A, B, C, D\}
\]</span></p>
</div>
</div>
<p>The population total <span class="math inline">\(\tau\)</span> would then be calculated as</p>
<p><span class="math display">\[
\tau = \sum_{i=1}^{N}y_{i}
\]</span> where the <span class="math inline">\(\sum\)</span> symbols means to sum over all the values of <span class="math inline">\(y_{i}\)</span> for all <span class="math inline">\(i=1, \ldots, N\)</span> units in the population.</p>
<p>However the nature of sampling means that <span class="math inline">\(y_{i}\)</span> is not observed for every unit in the population. In this case, we are going to consider a sample <span class="math inline">\(S\)</span> of 2 campuses. There are six different ways 2 units could be chosen from <span class="math inline">\(U\)</span>. <span class="math display">\[
S_{1} = \{A,B\}, S_{2} = \{A,C\}, S_{3} = \{A,D\}, \\
S_{4} = \{B,C\}, S_{5} = \{B,D\}, S_{6} = \{C,D\}
\]</span></p>
<p>Then we estimate the population value <span class="math inline">\(\tau\)</span> using an estimate <span class="math inline">\(\hat{t}\)</span>, where we sum over all the values of <span class="math inline">\(y_{i}\)</span> when that <span class="math inline">\(i^{th}\)</span> campus is present in the chosen sample.</p>
<p><span class="math display">\[
\hat{t} = \sum_{i \in S}y_{i}
\]</span></p>
<p>Let’s assume we know the number of parking garages at each campus <span class="math inline">\(y_{A} = 2, y_{B} = 4, y_{C} = 1, y_{D} = 3\)</span>. We can build a <strong>sampling distribution</strong>, that is a distribution of all possible values for <span class="math inline">\(\hat{t}\)</span> based on this design. <span class="margin-aside">A <strong>sampling distribution</strong> is an example of a discrete probability distribution</span></p>
<p>The total from sample 1 <span class="math inline">\(\hat{t}_{1} = y_{A} + y_{B} = 6\)</span> is the total calculated from campus A and B, sample 2 total is <span class="math inline">\(\hat{t}_{2} = y_{A} + y_{C} = 3\)</span>, and so forth. Doing this for all 6 samples results in the following graph:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cn02-statistical_foundations_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<table class="caption-top table">
<caption>Sampling distribution for the estimated sample total <span class="math inline">\(\hat{t}\)</span> number of parking garages on two randomly selected college campuses in the north state.</caption>
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<tbody>
<tr class="odd">
<td>k</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">7</td>
</tr>
<tr class="even">
<td><span class="math inline">\(P(\hat{t} = k)\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\frac{1}{6}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\frac{1}{6}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\frac{1}{3}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\frac{1}{6}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\frac{1}{6}\)</span></td>
</tr>
</tbody>
</table>
<p>The only reason we can calculate these probabilities exactly is because we knew the full population and were able to enumerate all possible combinations of samples. In practice we use statistical theory such as the Central Limit theorem to describe the characteristics of sampling distributions so that we can use them to estimate quantities such as means and variances.</p>
<div class="callout callout-style-default callout-important no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Definition: Expected Value
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="margin-aside">The <strong>Expected Value</strong> is the mean of the <strong>sampling distribution</strong></span> The expected value of the statistic is the weighted average of the possible sample values of the statistic, weighted by the probability that particular value of the statistic would occur. <span class="math display">\[
E[y]=\sum_{y}y*p(y)
\]</span></p>
<p>where <span class="math inline">\(p(y)\)</span> is the probability of each value of <span class="math inline">\(y\)</span> occurring.</p>
</div>
</div>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Example calculation of <span class="math inline">\(E(y)\)</span> from a discrete probability distribution
</div>
</div>
<div class="callout-body-container callout-body">
<table class="caption-top table">
<thead>
<tr class="header">
<th>y</th>
<th>p(y)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>.1</td>
</tr>
<tr class="even">
<td>2</td>
<td>.5</td>
</tr>
<tr class="odd">
<td>3</td>
<td>.4</td>
</tr>
</tbody>
</table>
<p><span class="math inline">\(E[y]=\sum_{y}yp(y) = (1)(.1) + (2)(.5) + (3)(.4) = 2.3\)</span></p>
</div>
</div>
<p>We can use R to calculate this for us.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>)        <span class="co"># Define a vector y of data values</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>p.y <span class="ot">&lt;-</span> <span class="fu">c</span>(.<span class="dv">1</span>, .<span class="dv">5</span>, .<span class="dv">4</span>) <span class="co"># define a vector of probabilities</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>(E.y <span class="ot">&lt;-</span> <span class="fu">sum</span>(y<span class="sc">*</span>p.y))  <span class="co"># multiply the elements of y and p.y, then sum</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.3</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-important no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Definition: Population Mean
</div>
</div>
<div class="callout-body-container callout-body">
<p>The population mean <span class="math inline">\(\mu\)</span> is defined as the expected value of y.</p>
<p><span class="math display">\[E[y]=\mu\]</span></p>
</div>
</div>
<div class="callout callout-style-default callout-important no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Definition: Population Variance &amp; Standard Deviation
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math display">\[\sigma^{2} = V(y)=E[y-\mu]^{2}=\sum_{y}\left(y-\mu\right)^{2}*p(y)\]</span></p>
<p>The variability of measurements in a population can be measured by the <strong>variance</strong> which is defined as the average squared deviation from the mean between a randomly selected measurement <span class="math inline">\(y\)</span> and its mean value <span class="math inline">\(\mu\)</span>.</p>
<p>The standard deviation is defined as the square root of the variance, and is denoted <span class="math inline">\(\sigma\)</span>.</p>
<p>Often it’s more convenient to calculate the variance using this formulation:</p>
<p><span class="math display">\[V(y)=E[y^2] - E[y]^{2}\]</span></p>
</div>
</div>
<p>Using R on the probability distribution defined above this would look like;</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>y.sq <span class="ot">&lt;-</span> y<span class="sc">^</span><span class="dv">2</span>              <span class="co"># square y</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>E.y.sq <span class="ot">&lt;-</span> <span class="fu">sum</span>(y.sq<span class="sc">*</span>p.y)  <span class="co"># calculate E(y^2)</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>(Var.y <span class="ot">&lt;-</span> E.y.sq <span class="sc">-</span> E.y<span class="sc">^</span><span class="dv">2</span>)  <span class="co"># Calculate the variance of y</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.41</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-warning no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
⭐ You try it
</div>
</div>
<div class="callout-body-container callout-body">
<p>When a few data points are repeated in a data set, the results are often arrayed in a frequency table. For example, a quiz given to each of 25 students was graded on a four-point scale (0,1,2,3), 3 being a perfect score.</p>
<p>Consider the following results: 16 students scored a 3, 4 students scored a 2, 2 students scored a 1, and 3 scored a 0. Assume this distribution of scores is representative of the population distribution.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Score (Y)</th>
<th>Frequency</th>
<th>Proportion</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>3</td>
<td>16</td>
<td>.64</td>
</tr>
<tr class="even">
<td>2</td>
<td>4</td>
<td>.16</td>
</tr>
<tr class="odd">
<td>1</td>
<td>2</td>
<td>.08</td>
</tr>
<tr class="even">
<td>0</td>
<td>3</td>
<td>.12</td>
</tr>
</tbody>
</table>
<p>Calculate the population mean and standard deviation</p>
</div>
</div>
<div class="callout callout-style-simple callout-warning no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="dv">3</span><span class="sc">:</span><span class="dv">0</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">c</span>(.<span class="dv">64</span>, .<span class="dv">16</span>, .<span class="dv">08</span>, .<span class="dv">12</span>)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>(y.bar.p <span class="ot">&lt;-</span> <span class="fu">sum</span>(y<span class="sc">*</span>p))  <span class="co"># mean</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.32</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="fu">sum</span>(p<span class="sc">*</span>(y<span class="sc">-</span>y.bar.p)<span class="sc">^</span><span class="dv">2</span>)) <span class="co">#sd</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.047664</code></pre>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="the-finite-population-case" class="level1">
<h1>The Finite Population Case</h1>
<p>The previous section develops results for random sampling from a population considered to be infinite. In such situations, each sampled element has the same chance of being selected and the selections are independent of one another.</p>
<ul>
<li>Most sampling problems don’t live in an infinite world, but the population is usually finite although it may be quite large.</li>
<li>In addition, we may want to take into consideration varying the probabilities with which the units are sampled.</li>
</ul>
<p>In <em>probability sampling</em>, each possible sample <span class="math inline">\(S\)</span> has a known probability <span class="math inline">\(\delta\)</span> of being chosen. Let’s return to the university parking garage example and use <span class="math inline">\(\delta_{1} = P(\S_{1}) = 1/3, \delta_{2} = P(S_{2}) = 1/6, \delta_{6} = P(S_{6}) = 1/2\)</span> and the rest have probability 0.</p>
<p>Additionally, each unit <span class="math inline">\(i\)</span> within the universe <span class="math inline">\(U\)</span> has a <span class="math inline">\(\pi_{i} \gt 0\)</span> probability of appearing in the selected sample. These unit probabilities are a function of the probability of selecting that random sample.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 17%">
<col style="width: 54%">
<col style="width: 28%">
</colgroup>
<tbody>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(\pi_{A}\)</span> =</td>
<td style="text-align: center;"><span class="math inline">\(\delta_{1} + \delta_{2} + \delta_{3}\)</span></td>
<td style="text-align: center;">1/3 + 1/6 + 0 = 1/2</td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(\pi_{B}\)</span> =</td>
<td style="text-align: center;"><span class="math inline">\(\delta_{1} + \delta_{4} + \delta_{5}\)</span></td>
<td style="text-align: center;">1/3 + 0 + 0 = 1/3</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(\pi_{C}\)</span> =</td>
<td style="text-align: center;"><span class="math inline">\(\delta_{2} + \delta_{4} + \delta_{6}\)</span></td>
<td style="text-align: center;">1/6 + 0 + 1/2 = 2/3</td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(\pi_{D}\)</span> =</td>
<td style="text-align: center;"><span class="math inline">\(\delta_{3} + \delta_{5} + \delta_{6}\)</span></td>
<td style="text-align: center;">0 + 0 + 1/2 = 1/2</td>
</tr>
</tbody>
</table>
<p>So in this case, not all units (campuses) <span class="math inline">\(i\)</span> have the sa me probability of appearing in our sample.</p>
<div class="callout callout-style-default callout-warning no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
⭐ You try it
</div>
</div>
<div class="callout-body-container callout-body">
<p>Change the values of <span class="math inline">\(\delta\)</span> for each of the 6 possible samples of <span class="math inline">\(U\)</span> above, so that each sample has a non-zero probabilty of being chosen. Then recalculate the observational probabilities <span class="math inline">\(\pi_{A}-\pi_{D}\)</span>.</p>
</div>
</div>
<p>Probability sampling:</p>
<ul>
<li>is more difficult than some sampling methods such as convenience sample</li>
<li>is less prone to selection biases discussed earlier</li>
<li>guarantees each unit in the population has a chance of appearing in the sample</li>
<li>allows us to calculate the precision of statistics calculated from the sample</li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Example: Estimate total number of job openings.
</div>
</div>
<div class="callout-body-container callout-body">
<p>Suppose, for example, we want to estimate the total number of job openings in a city by sampling industrial companies from within that city.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Company</th>
<th>Jobs (<span class="math inline">\(y\)</span>)</th>
<th>Size of company</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>A</td>
<td>3</td>
<td>70</td>
</tr>
<tr class="even">
<td>B</td>
<td>10</td>
<td>90</td>
</tr>
<tr class="odd">
<td>C</td>
<td>25</td>
<td>120</td>
</tr>
<tr class="even">
<td>D</td>
<td>61</td>
<td>300</td>
</tr>
</tbody>
</table>
<p>The population total of job openings is <span class="math inline">\(\tau= 99\)</span>. But of course we don’t know this, so we want to take a sample of <span class="math inline">\(n=2\)</span> firms and count the number of jobs at each firm <span class="math inline">\(y\)</span> as a way to estimate this total.</p>
</div>
</div>
<p><span class="margin-aside">Note: The mathematical definition of unbiased is not the same thing as selection biased discussed earlier. The math definition of bias will be discussed below.</span> An <strong>unbiased estimator</strong> of the population total, <span class="math inline">\(\tau\)</span>, is given by</p>
<p><span class="math display">\[
\hat{t}=\frac{1}{n}\sum^{n}_{i=1}\frac{y_{i}}{\pi_{i}}
\]</span></p>
<p>If all companies have equal probability of being selected, then the subset of companies <span class="math inline">\(S = \{A, B\}\)</span> have the same chance of being selected as any other subset of two companies such as <span class="math inline">\(S = \{A, C\}\)</span>. This can occur when we sample one company out of the <span class="math inline">\(N\)</span> companies in the population randomly with replacement, which means <span class="math inline">\(\pi_{i} = 1/N\)</span>. This allows us to rewrite this equation as</p>
<p><span class="math display">\[
\hat{t} = \frac{1}{n}\sum^{n}_{i=1}\frac{y_{i}}{(1/N)} = \frac{N}{n} \sum^{n}_{i=1}y_{i} = N\bar{y}
\]</span></p>
<p>Thus the estimate of the total job openings based on the <span class="math inline">\(S = \{A, B\}\)</span> sample would be:</p>
<p><span class="math display">\[
\hat{t} = N\bar{y} = 4*(13/2) = 26
\]</span></p>
<p>Note that the size of these companies vary quite a lot, and the number of job openings will likely be directly dependent on the size of the company Thus, we might improve the sample if large companies are more likely to be included in the sample. One practical way to choose the <span class="math inline">\(\pi_{i}\)</span>, is to choose them proportional to a known measurement that is highly correlated with <span class="math inline">\(y_{i}\)</span>. In this case, that would be the company size.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Company</th>
<th>Jobs (<span class="math inline">\(y\)</span>)</th>
<th>Size of company</th>
<th><span class="math inline">\(\pi_{i}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>A</td>
<td>3</td>
<td>70</td>
<td>70/580</td>
</tr>
<tr class="even">
<td>B</td>
<td>10</td>
<td>90</td>
<td>90/580</td>
</tr>
<tr class="odd">
<td>C</td>
<td>25</td>
<td>120</td>
<td>120/580</td>
</tr>
<tr class="even">
<td>D</td>
<td>61</td>
<td>300</td>
<td>300/580</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>If we adjust <span class="math inline">\(y_{i}\)</span> based on the probability of selecting firms A and B,</p>
<p><span class="math display">\[
\hat{t}=\frac{1}{n}\sum^{n}_{i=1}\frac{y_{i}}{\pi_{i}} = \frac{1}{2}\Big[\frac{3}{70/580} + \frac{10}{90/580}\Big]  = 44.7
\]</span></p>
<p>❓ Was this a good estimate of <span class="math inline">\(\tau\)</span>? Why or why not?</p>
<blockquote class="blockquote">
<p>No! The population total <span class="math inline">\(\tau\)</span> is nearly double that of the estimate. However, the weighted mean is much closer to the true value than the unweighted mean is.</p>
</blockquote>
</section>
<section id="variability-of-estimates" class="level1">
<h1>Variability of Estimates</h1>
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
❓👥Turn and talk
</div>
</div>
<div class="callout-body-container callout-body">
<p>Why do we usually think of a parameter <span class="math inline">\(\mu\)</span> or <span class="math inline">\(p\)</span> as a fixed value, while the sample statistic <span class="math inline">\(\bar{x}\)</span> or <span class="math inline">\(\hat{p}\)</span> as a random variable?</p>
</div>
</div>
<blockquote class="blockquote">
<p>write your answer in HackMD.</p>
</blockquote>
<p>Along with the point estimate we also want to know how accurate we can expect the point estimate to be. In other words, if we took another random sample of the same size from the population, is the point estimate from this new sample likely to be similar to the first point estimate or are they likely to be far apart.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Example: Enrollment in Graduate Programs in Statistics
</div>
</div>
<div class="callout-body-container callout-body">
<p>Graduate programs in statistics sometimes pay their graduate students, which means that many graduate students in statistics are able to attend graduate school tuition free with an assistantship or fellowship. There are 82 US statistics doctoral programs for which enrollment data were available. The data set <code>StatisticsPhD</code> lists all these schools together with the total enrollment of full-time graduate students in each program in 2009.</p>
<p>❓ What is the average full-time graduate student enrollment in US statistics doctoral programs in 2009?</p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(stat.phd) <span class="co">#always look at your imported data to check for import errors</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
  University                      Department    FTGradEnrollment
  &lt;chr&gt;                           &lt;chr&gt;                    &lt;dbl&gt;
1 Baylor University               Statistics                  26
2 Boston University               Biostatistics               39
3 Brown University                Biostatistics               21
4 Carnegie Mellon University      Statistics                  39
5 Case Western Reserve University Statistics                  11
6 Colorado State University       Statistics                  14</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(stat.phd<span class="sc">$</span>FTGradEnrollment)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 53.53659</code></pre>
</div>
</div>
<p>Based on the data set, the mean enrollment in 2009 is 53.54 full-time graduate students. Because this is the mean for the entire population of all US statistics doctoral programs for which data were available that year, we have that <span class="math inline">\(\mu=53.54\)</span> students.</p>
<p>⭐ Use the code below take a random sample of 10 programs from the data file then calculate the mean.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>my.sample.programs <span class="ot">&lt;-</span> <span class="fu">sample</span>(stat.phd<span class="sc">$</span>FTGradEnrollment, <span class="at">size=</span><span class="dv">10</span>)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(my.sample.programs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 31.4</code></pre>
</div>
</div>
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
❓👥Turn to your neighbor and discuss the following questions
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Did everyone get the same sample mean?</li>
<li>Does your sample mean exactly equal the population mean?</li>
<li>If you took another sample of 10, would you get the same sample mean? Why?</li>
<li>If we created a histogram of all our sample means, what would it look like? Where would it be centered at? What is the spread of the histogram?</li>
</ul>
<p>Summarize your findings in HackMD and compare your answer to other groups.</p>
</div>
</div>
<p>Knowing the behavior of of repeated sample statistics (like the mean in the prior example) is critically important. Let’s dig into this a little more by repeating this sampling experiment many times.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>many.means <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="at">n=</span><span class="dv">100</span>, {</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  my.sample.programs <span class="ot">&lt;-</span> <span class="fu">sample</span>(stat.phd<span class="sc">$</span>FTGradEnrollment, <span class="at">size=</span><span class="dv">10</span>)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mean</span>(my.sample.programs)</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>})</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s visualize the distribution of all those sample means.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(many.means)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="cn02-statistical_foundations_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(many.means)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  24.90   45.98   51.95   53.48   58.88   83.10 </code></pre>
</div>
</div>
<p>Characteristics of this distribution:</p>
<ul>
<li><em>Shape</em>: The distribution of average enrollment isn’t quite normal, there seems to perhaps be two peaks?</li>
<li><em>Center</em>: The average enrollment is 53.48</li>
<li><em>Spread</em>: Average enrollment ranges from 24.9, 83.1.</li>
</ul>
<p>🎉 We have just created a <em>sampling distribution</em> of the sample mean.</p>
<p><span class="margin-aside">The proof of the CLT is generally seen in a first graduate Statistics class that uses convergence in distribution concepts from MATH 420.</span> In elementary statistics you were introduced to the “Central Limit Theorem” (CLT). The CLT states that the sampling distribution of <span class="math inline">\(\bar{y}\)</span> should be centered at <span class="math inline">\(\mu\)</span> (<span class="math inline">\(E(\bar{y}) = \mu)\)</span>) with a variance of <span class="math inline">\(\sigma^{2}/n\)</span>. It also states that the shape of the distribution should be approximately Normal for a large <span class="math inline">\(n\)</span>.</p>
</section>
<section id="properties-of-estimators" class="level1">
<h1>Properties of Estimators</h1>
<p>In general, suppose that <span class="math inline">\(\hat{\theta}\)</span> is an estimator of the parameter <span class="math inline">\(\theta\)</span>. Two properties that we would like <span class="math inline">\(\hat{\theta}\)</span> to have are <span class="margin-aside">The symbol <span class="math inline">\(\theta\)</span> is used as a generic parameter, like how <span class="math inline">\(x\)</span> tends to be used for a generic unknown value or variable.</span></p>
<ol type="1">
<li>The estimate is <strong>unbiased</strong>: <span class="math inline">\(E(\hat{\theta}) = \theta\)</span>.</li>
<li>The estimate is <strong>precise</strong>: <span class="math inline">\(Var(\hat{\theta})\)</span> is small.</li>
</ol>
<p>To clarify:</p>
<ul>
<li><strong>Measurement bias</strong> means that the <span class="math inline">\(y\)</span>’s are measured inaccurately.
<ul>
<li>That means an estimator of a total <span class="math inline">\(\tau\)</span> calculated as <span class="math inline">\(\hat{t} = \sum_{i \in U} y_{i}\)</span> where <span class="math inline">\(U\)</span> is the entire universe, then <span class="math inline">\(\hat{t}\)</span> itself would not be the true total of interest.</li>
<li>Trying to estimate heights of students, but your ruler is always off 3 cm</li>
</ul></li>
<li><strong>Estimation bias</strong> means that the estimator chosen resulted in a bias.
<ul>
<li>If we calculated the total as <span class="math inline">\(t' = \sum_{i \in L} y_{i}\)</span> from a random sample of <span class="math inline">\(L\)</span> units in the universe, <span class="math inline">\(\hat{t'}\)</span> would be biased.</li>
<li>Trying to estimate heights of students by taking a sample of the shorter students only.</li>
</ul></li>
</ul>
<p>If two unbiased estimators are available for <span class="math inline">\(\theta\)</span> we generally prefer the one with the smaller variance.</p>
<p>Because sometimes we use biased estimators, we often use the <strong>Mean Squared Error (MSE)</strong> instead of the variance to estimate the <strong>accuracy</strong>.</p>
<div class="callout callout-style-default callout-important no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Definition: Bias, Variance, Accuracy
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math display">\[\mbox{Bias}(\hat{\theta}) = E(\hat{\theta}) - \theta\]</span></p>
<p><span class="math display">\[V(\hat{\theta})  = E \Big[(\hat{\theta} - E[\hat{\theta}])^2\Big]\]</span></p>
<p><span class="math display">\[\mbox{MSE}(\hat{\theta}) = V(\hat{\theta}) + [Bias(\hat{\theta})]^2\]</span></p>
</div>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figs/fig2_3.jpg" class="img-fluid figure-img"></p>
<figcaption>Textbook Figure 2.3. Unbiased, precise and accurate archers.</figcaption>
</figure>
</div>
<ul>
<li>A is <strong>unbiased</strong>. The average position of all arrows is at the center of the target.</li>
<li>B is <strong>precise</strong> but not unbiased. All arrows are close together but systematically away from the center.</li>
<li>C is <strong>accurate</strong>. All arrows are close together and near the center of the target.</li>
</ul>
</section>
<section id="interval-estimation" class="level1">
<h1>Interval Estimation</h1>
<p>In general, it is usually not enough to just give a point estimate when estimating a population parameter. Why?</p>
<section id="standard-error" class="level2">
<h2 class="anchored" data-anchor-id="standard-error">Standard Error</h2>
<div class="callout callout-style-default callout-important no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Definition: Standard Error
</div>
</div>
<div class="callout-body-container callout-body">
<p>The <em>standard error</em> of a statistic is the standard deviation of the sample statistic. In other words, the standard deviation of the sampling distribution.</p>
</div>
</div>
<p>The standard error of a statistic tells us how much the sample statistic will vary from sample to sample. In situations like above where we can examine the distribution of the sample statistic using simulation, we can estimate the standard error by taking the sample standard deviation of the sampling distribution. In other situations we can use closed form mathematical formulas to calculate the standard error.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Example Grad program example cont.
</div>
</div>
<div class="callout-body-container callout-body">
<p>Estimate the standard error for the mean enrollment in statistics PhD programs for a sample size of 10 and also a sample size of 20.</p>
</div>
</div>
<p><span class="margin-aside">I used the base pipe <code>|&gt;</code> here to pass the results of the replicate function into the <code>sd()</code> function</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(many.means) <span class="co">#because the example above already had n=10</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 12.1839</code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">replicate</span>(<span class="at">n=</span><span class="dv">100</span>, {</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  my.sample.programs <span class="ot">&lt;-</span> <span class="fu">sample</span>(stat.phd<span class="sc">$</span>FTGradEnrollment, <span class="at">size=</span><span class="dv">20</span>)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mean</span>(my.sample.programs)</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>}) <span class="sc">|&gt;</span> <span class="fu">sd</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 7.492231</code></pre>
</div>
</div>
</section>
<section id="confidence-intervals" class="level2">
<h2 class="anchored" data-anchor-id="confidence-intervals">Confidence Intervals</h2>
<p>When the distributions are relatively symmetric and bell-shaped, the 95% rule tells us that approximately 95% of the data values fall within two standard deviations of the mean. Applying the 95% rule to sampling distributions, we see that about 95% of the sample statistics will fall within two standard errors of the mean. We use this rule many times to form what we call an approximate 95% confidence interval which gives us a range for which which we are quite confident that captures the true parameter we are trying to estimate.</p>
<p>When using a formula to calculate an approximate 95% confidence interval, use <span class="math inline">\(2*SE\)</span> as the margin of error.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
CI for PhD program enrollment
</div>
</div>
<div class="callout-body-container callout-body">
<p>Based on our example, what would be a 95% confidence interval for <span class="math inline">\(\mu\)</span> the true mean total enrollment for PhD programs in statistics. Interpret this confidence interval in context of the problem.</p>
</div>
</div>
<p><span class="margin-aside">Wrapping the entire line of code in <code>()</code> will execute that code AND print out the results. This lets me see the results in the rendered document AND store the results in an object to call later, like in my sentence response below.</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>(LCL <span class="ot">&lt;-</span> <span class="fu">mean</span>(many.means) <span class="sc">-</span> <span class="dv">2</span><span class="sc">*</span><span class="fu">sd</span>(many.means))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 29.10819</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>(UCL <span class="ot">&lt;-</span> <span class="fu">mean</span>(many.means) <span class="sc">+</span> <span class="dv">2</span><span class="sc">*</span><span class="fu">sd</span>(many.means))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 77.84381</code></pre>
</div>
</div>
<p><span class="margin-aside">Every time I compile these notes, I draw a different sample and will get a different numbers. To avoid conflicts in my written response, and what the code shows, I use <em>inline R code</em> here. See the RStudio <em>Help –&gt; Markdown Quick Reference</em> for more information.</span></p>
<blockquote class="blockquote">
<p>We can be 95% confident that the true mean total enrollment for PhD programs in statistics is covered by the interval (29.1 , 77.8).</p>
</blockquote>
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
❓👥 Turn &amp; talk
</div>
</div>
<div class="callout-body-container callout-body">
<p>Consider the following interpretation of the above confidence interval.</p>
<blockquote class="blockquote">
<p>We can be 95% confident that PhD programs in Statistics have a total enrollment of between 29.1 and 77.8 students.</p>
</blockquote>
<p>Why is this an incorrect interpretation?</p>
</div>
</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/sampling-458\.netlify\.app\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>This site is built with <span class="emoji" data-emoji="heart">❤️</span>, <a href="https://posit.co/">R</a> and <a href="https://quarto.org/">Quarto</a> by <a href="www.norcalbiostat.com">Robin Donatello</a></p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>