<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.335">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="COMPLETE">
<meta name="dcterms.date" content="2023-02-06">
<meta name="description" content="We review some of the introductory concepts of statistics that will be a pre-requisite for the remainder of the course.">

<title>Sampling Methods - Foundations of Statistical Estimation</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Sampling Methods</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../weekly_details.html">
 <span class="menu-text">Weekly Overview</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../notes.html">
 <span class="menu-text">Notes</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../assignments.html">
 <span class="menu-text">Assignments</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-hackmd" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">HackMD</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-hackmd">    
        <li>
    <a class="dropdown-item" href="https://hackmd.io/@norcalbiostat/sampling_r_resources">
 <span class="dropdown-text">R resources</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://hackmd.io/@norcalbiostat/458_intro_hackmd">
 <span class="dropdown-text">What is HackMD</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://hackmd.io/@norcalbiostat/cn02-intro_sampling">
 <span class="dropdown-text">Sampling Framework notes</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://hackmd.io/@norcalbiostat/cn03-statistical_foundations">
 <span class="dropdown-text">Foundations of Estimation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://hackmd.io/@norcalbiostat/cn06_stratified">
 <span class="dropdown-text">Stratified Sampling</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://hackmd.io/@norcalbiostat/cn07_cluster">
 <span class="dropdown-text">Cluster Sampling</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../syllabus.html">
 <span class="menu-text">Syllabus</span></a>
  </li>  
</ul>
              <div class="quarto-toggle-container">
                  <a href="" class="quarto-color-scheme-toggle nav-link" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
              </div>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a>
  <ul class="collapse">
  <li><a href="#populations-and-samples" id="toc-populations-and-samples" class="nav-link" data-scroll-target="#populations-and-samples">Populations and Samples</a></li>
  </ul></li>
  <li><a href="#numerical-summaries" id="toc-numerical-summaries" class="nav-link" data-scroll-target="#numerical-summaries">Numerical Summaries</a>
  <ul class="collapse">
  <li><a href="#the-finite-population-case-lohr-ch-2.2" id="toc-the-finite-population-case-lohr-ch-2.2" class="nav-link" data-scroll-target="#the-finite-population-case-lohr-ch-2.2">The Finite Population Case (Lohr Ch 2.2)</a></li>
  </ul></li>
  <li><a href="#variability-of-estimates" id="toc-variability-of-estimates" class="nav-link" data-scroll-target="#variability-of-estimates">Variability of Estimates</a>
  <ul class="collapse">
  <li><a href="#sampling-distribution" id="toc-sampling-distribution" class="nav-link" data-scroll-target="#sampling-distribution">Sampling Distribution</a></li>
  </ul></li>
  <li><a href="#properties-of-estimators" id="toc-properties-of-estimators" class="nav-link" data-scroll-target="#properties-of-estimators">Properties of Estimators</a></li>
  <li><a href="#interval-estimation" id="toc-interval-estimation" class="nav-link" data-scroll-target="#interval-estimation">Interval Estimation</a>
  <ul class="collapse">
  <li><a href="#bounds-on-estimators" id="toc-bounds-on-estimators" class="nav-link" data-scroll-target="#bounds-on-estimators">Bounds on Estimators</a></li>
  <li><a href="#standard-error" id="toc-standard-error" class="nav-link" data-scroll-target="#standard-error">Standard Error</a></li>
  <li><a href="#confidence-intervals" id="toc-confidence-intervals" class="nav-link" data-scroll-target="#confidence-intervals">Confidence Intervals</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Foundations of Statistical Estimation</h1>
</div>

<div>
  <div class="description">
    We review some of the introductory concepts of statistics that will be a pre-requisite for the remainder of the course.
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>COMPLETE </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">February 6, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>In this section we review the basic concepts underlying the selection of an estimator of a population parameter, the method for evaluating its goodness, and the concepts involved in interval estimation. Because the bias and the variance of estimators determine their goodness, we need to review the basic ideas concerned with the expectation and variance of a random variable.</p>
<div class="callout-note callout callout-style-simple no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p><em>Reminder: Most people come into this class with different pre-requisite classes and instructors. This recap helps ensure that we are all on the same page with concepts and notation that may be new for some.</em></p>
</div>
</div>
</div>
<section id="populations-and-samples" class="level2">
<h2 class="anchored" data-anchor-id="populations-and-samples">Populations and Samples</h2>
<p>Statistical inference centers around using information from a sample to understand what might be true about the entire population of interest. If all we see are the data in the sample, what conclusions can we draw about the population? How sure are we about the accuracy of those conclusions?</p>
<p>On April 29, 2011, Prince William married Kate Middleton in London. The Pew Research Center reports that 34% of US adults watched some or all of the royal wedding. How do we know that 34% of all US adults watched? Did anyone ask <strong>you</strong> if you watched it? In order to know for sure what proportion of US adults watched the wedding, we would need to ask <strong>all</strong> US adults whether or not they watched. This would be very difficult to do. As we will see, however, we can estimate the <em>population</em> proportion <em>parameter</em> quite accurately with a <em>sample statistic</em>, as long as we use a random sample. In the case of the royal wedding, the estimate is based on a poll using a random sample of 1006 US adults.</p>
<ul>
<li><em>Statistical inference</em>: The process of drawing conclusions about the entire population based on the information in the sample.</li>
<li><em>Parameter</em>: A number that describes the entire population. <span class="math inline">\(\mu\)</span>, <span class="math inline">\(p\)</span>, <span class="math inline">\(\tau\)</span></li>
<li><em>Statistic</em>: A number calculated from a sample. <span class="math inline">\(\bar{x}\)</span>, <span class="math inline">\(\hat{p}\)</span>, <span class="math inline">\(\hat{\tau}\)</span>.</li>
</ul>
<p>Generally our goal is to know the value of the population parameter exactly but this usually isn’t possible since we usually cannot collect information from the entire population.</p>
<p>Instead we can select a sample from the population, calculate the quantity of interest for the sample, and use this sample statistic to estimate the value for the whole population.</p>
<div class="callout-warning callout callout-style-default no-icon callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
<span class="emoji" data-emoji="star">⭐</span> You try it
</div>
</div>
<div class="callout-body-container callout-body">
<p>The US Census states that 27.5% of US adults who are at least 25 years old have a college bachelor’s degree or higher. Suppose that in a random sample of <span class="math inline">\(n\)</span>=200 US residents who are 25 or older, 58 of them have a college bachelor’s degree or higher.</p>
<p>What is the population parameter? What is the sample statistic? Use correct notation for your answer.</p>
</div>
</div>
<div class="callout-warning callout callout-style-simple no-icon callout-captioned">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Population Parameter</strong>: <span class="math inline">\(p = .275\)</span><br>
<strong>Sample Statistic</strong>: <span class="math inline">\(\hat{p} = 58/200 = .29\)</span></p>
</div>
</div>
</div>
<p>The value of a statistic for a particular sample gives a <em>point estimate</em> of the population parameter. If we only have the one sample and don’t know the value of the population parameter, this point estimate is our best estimate of the true value of the population parameter.</p>
<p>After we have a little more mathematical terminology and foundation, we’ll come back to what we mean by “best estimate”, and examine how we can determine if something is a “good” estimate.</p>
<hr>
</section>
</section>
<section id="numerical-summaries" class="level1 page-columns page-full">
<h1>Numerical Summaries</h1>
<div class="page-columns page-full"><p>The first thing that we do with data is to summarize it with graphs and numbers. </p><div class="no-row-height column-margin column-container"><span class=""><em>Empirical</em>: Relying on or derived from observation or experiment.</span></div></div>
<ul>
<li>Histograms or relative frequency tables can be used to try to make an empirical estimation of the shape of the distribution.</li>
<li>Once a relative frequency distribution has been established for a population, we can use probability arguments to calculate numerical summary measures such as the mean, variance, and standard deviation.</li>
<li>The numerical measures used to summarize the characteristics of a population are defined as <strong>expected values</strong> of <span class="math inline">\(y\)</span>.</li>
</ul>
<div class="callout-important callout callout-style-default no-icon callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Definition: Expected Value
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math display">\[
E(y)=\sum_{y}y*p(y)
\]</span> where the summation is over all the values of <span class="math inline">\(y\)</span> for which <span class="math inline">\(p(y)&gt;0\)</span>.<br>
<span class="math inline">\(p(y)\)</span> is the probability of each value of <span class="math inline">\(y\)</span>.</p>
</div>
</div>
<div class="callout-tip callout callout-style-default no-icon callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Example calculation of <span class="math inline">\(E(y)\)</span> from a discrete probability distribution
</div>
</div>
<div class="callout-body-container callout-body">
<table class="table">
<thead>
<tr class="header">
<th>y</th>
<th>p(y)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>.1</td>
</tr>
<tr class="even">
<td>2</td>
<td>.5</td>
</tr>
<tr class="odd">
<td>3</td>
<td>.4</td>
</tr>
</tbody>
</table>
<p><span class="math inline">\(E(y)=\sum_{y}yp(y) = (1)(.1) + (2)(.5) + (3)(.4) = 2.3\)</span></p>
</div>
</div>
<div class="callout-important callout callout-style-default no-icon callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Definition: Population Mean
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math display">\[E(y)=\mu\]</span> where <span class="math inline">\(y\)</span> is a value of a single measurement chosen at random from the population.</p>
</div>
</div>
<div class="callout-important callout callout-style-default no-icon callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Definition: Population Variance &amp; Standard Deviation
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math display">\[\sigma^{2} = V(y)=E(y-\mu)^{2}=\sum_{y}\left(y-\mu\right)^{2}*p(y)\]</span></p>
<p>The variability of measurements in a population can be measured by the <strong>variance</strong> which is defined as the average squared deviation from the mean between a randomly selected measurement <span class="math inline">\(y\)</span> and its mean value <span class="math inline">\(\mu\)</span>.</p>
<p>The standard deviation is defined as the square root of the variance, and is denoted <span class="math inline">\(\sigma\)</span>.</p>
<p>Sometimes it’s may be convenient to calculate the variance using this formulation:</p>
<p><span class="math display">\[V(y)=E(y^2) - E(y)^{2}\]</span></p>
</div>
</div>
<p>We can also calculate these measurements directly from the sample measurements.</p>
<p>In statistical studies, the population of interest consists of <em>unknown</em> measurements; hence, we can only speculate on the relative frequencies (<span class="math inline">\(p(y)\)</span>). In order to gain information about a population we take a sample of <span class="math inline">\(n\)</span>, <span class="math inline">\(y_{1},y_{2},...,y_{n}\)</span>. We can then infer characteristics about the population. Given our sample data, <span class="math inline">\(y_{1},y_{2},...,y_{n}\)</span>, we can calculate the mean and variance:</p>
<p><span class="math display">\[\bar{y} = \frac{1}{n}\sum_{i=1}^{n}y_{i}\]</span> <span class="math display">\[s^{2} = \frac{1}{n-1}\sum^{n}_{i=1}\left(y_{i}-\bar{y}\right)^{2}\]</span></p>
<p><span class="emoji" data-emoji="question">❓</span> Why do we have <span class="math inline">\(n-1\)</span> in the denominator for <span class="math inline">\(s^2\)</span>, but only <span class="math inline">\(n\)</span> in the denominator for <span class="math inline">\(\bar{y}\)</span>?</p>
<div class="callout-warning callout callout-style-default no-icon callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
<span class="emoji" data-emoji="star">⭐</span> You try it
</div>
</div>
<div class="callout-body-container callout-body">
<p>When a few data points are repeated in a data set, the results are often arrayed in a frequency table. For example, a quiz given to each of 25 students was graded on a four-point scale (0,1,2,3), 3 being a perfect score.</p>
<p>Consider the following results: 16 students scored a 3, 4 students scored a 2, 2 students scored a 1, and 3 scored a 0. Assume this distribution of scores is representative of the population distribution.</p>
<p>Calculate both the sample and population values of the average and standard deviation.</p>
</div>
</div>
<div class="callout-warning callout callout-style-simple no-icon callout-captioned">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<table class="table">
<thead>
<tr class="header">
<th>Score (Y)</th>
<th>Frequency</th>
<th>Proportion</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>3</td>
<td>16</td>
<td>.64</td>
</tr>
<tr class="even">
<td>2</td>
<td>4</td>
<td>.16</td>
</tr>
<tr class="odd">
<td>1</td>
<td>2</td>
<td>.08</td>
</tr>
<tr class="even">
<td>0</td>
<td>3</td>
<td>.12</td>
</tr>
</tbody>
</table>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="dv">3</span><span class="sc">:</span><span class="dv">0</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>f <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">16</span>, <span class="dv">4</span>, <span class="dv">2</span>, <span class="dv">3</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">c</span>(.<span class="dv">64</span>, .<span class="dv">16</span>, .<span class="dv">08</span>, .<span class="dv">12</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Sample</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>(dta <span class="ot">&lt;-</span> <span class="fu">rep</span>(y, f)) <span class="co"># expand out the data</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 2 2 2 2 1 1 0 0 0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">length</span>(dta)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>(y.bar <span class="ot">&lt;-</span> <span class="fu">sum</span>(dta)<span class="sc">/</span>n)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.32</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="fu">sum</span>((dta<span class="sc">-</span>y.bar)<span class="sc">^</span><span class="dv">2</span>)<span class="sc">/</span>(n<span class="dv">-1</span>)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.069268</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Population</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>(y.bar.p <span class="ot">&lt;-</span> <span class="fu">sum</span>(y<span class="sc">*</span>p))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.32</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="fu">sum</span>(p<span class="sc">*</span>(y<span class="sc">-</span>y.bar.p)<span class="sc">^</span><span class="dv">2</span>)) <span class="co">#</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.047664</code></pre>
</div>
</div>
</div>
</div>
</div>
<section id="the-finite-population-case-lohr-ch-2.2" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="the-finite-population-case-lohr-ch-2.2">The Finite Population Case (Lohr Ch 2.2)</h2>
<p>The previous section develops results for random sampling from a population considered to be infinite. In such situations, each sampled element has the same chance of being selected and the selections are independent of one another.</p>
<ul>
<li>Most sampling problems don’t live in an infinite world, but the population is usually finite although it may be quite large.</li>
<li>In addition, we may want to take into consideration varying the probabilities with which the units are sampled.</li>
</ul>
<div class="callout-tip callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Example: Estimate total number of job openings.
</div>
</div>
<div class="callout-body-container callout-body">
<p>Suppose, for example, we want to estimate the total number of job openings in a city by sampling industrial firms from within that city. Many of these firms will be small and a few firms will be large. In a random sample <em>of firms</em>, the size of the firm is not taken into account. However, the number of job openings will be directly dependent on the size of the firm. Thus, we might improve the sample if large firms are more likely to be included in the sample.</p>
</div>
</div>
<ul>
<li>Suppose the population consists of the set of elements <span class="math inline">\(\{u_{1},u_{2},...,u_{N}\}\)</span> and a sample of <span class="math inline">\(n\)</span> elements is to be selected with replacement independently of one another.</li>
<li>Let <span class="math inline">\(\{\delta_{1},\delta_{2},...,\delta_{N}\}\)</span> represent the respective probabilities of selection for the population elements.
<ul>
<li><span class="math inline">\(\delta_{i}\)</span> is the probability that <span class="math inline">\(u_{i}\)</span> is selected on any one draw.</li>
<li>for the case of random sampling with replacement, each <span class="math inline">\(\delta_{i} = 1/N\)</span></li>
</ul></li>
</ul>
<div class="page-columns page-full"><p> An <strong>unbiased estimator</strong> of the population total, <span class="math inline">\(\tau\)</span>, is given by</p><div class="no-row-height column-margin column-container"><span class="">Note: The mathematical definition of unbiased is not the same thing as selection biased discussed earlier. The math definition of bias will be discussed below.</span></div></div>
<p><span class="math display">\[
\hat{\tau}=\frac{1}{n}\sum^{n}_{i=1}\frac{y_{i}}{\delta_{i}}
\]</span></p>
<p>When <span class="math inline">\(\delta_{i} = 1/N\)</span>, we can rewrite this as</p>
<p><span class="math display">\[
\hat{\tau} = \frac{1}{n}\sum^{n}_{i=1}\frac{y_{i}}{(1/N)} = \frac{N}{n} \sum^{n}_{i=1}y_{i} = N\bar{y}
\]</span></p>
<p>It is in the best interest to select the <span class="math inline">\(\delta_{i}\)</span> values in such a way that the variance is as small as possible. The best practical way to choose the <span class="math inline">\(\delta_{i}\)</span> is to choose them proportional to a known measurement that is highly correlated with <span class="math inline">\(y_{i}\)</span>.</p>
<div class="callout-tip callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Example: Job openings cont.
</div>
</div>
<div class="callout-body-container callout-body">
<p>Our universe only consists of these <span class="math inline">\(N=4\)</span> firms: A, B, C and D.</p>
<table class="table">
<thead>
<tr class="header">
<th>Firm</th>
<th>Jobs (<span class="math inline">\(x\)</span>)</th>
<th>Size of firm</th>
<th><span class="math inline">\(\delta_{i}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>A</td>
<td>3</td>
<td>70</td>
<td>70/580</td>
</tr>
<tr class="even">
<td>B</td>
<td>10</td>
<td>90</td>
<td>90/580</td>
</tr>
<tr class="odd">
<td>C</td>
<td>25</td>
<td>120</td>
<td>120/580</td>
</tr>
<tr class="even">
<td>D</td>
<td>61</td>
<td>300</td>
<td>300/580</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The population total of job openings is <span class="math inline">\(\tau= 99\)</span>. But of course we don’t know this, so we want to take a sample of <span class="math inline">\(n=2\)</span> firms and count the nubmer of jobs at each firm <span class="math inline">\(x\)</span> as a way to estimate this total.</p>
<p>If all firms have equal probability of being selected, then the subset of firms <span class="math inline">\(\{A, B\}\)</span> have the same chance of being selected as any other subset of two firms such as <span class="math inline">\(\{A, C\}\)</span>. However, we may want to select firms with probabilities in proportion to their workforce (<span class="math inline">\(\delta_{i}\)</span>).</p>
<p>Without adjustment the estimate of the total job openings based on the <span class="math inline">\(\{A, B\}\)</span> sample would be: <span class="math display">\[
\hat{\tau} = N\bar{X} = 4*(13/2) = 26
\]</span></p>
<p>If we adjust <span class="math inline">\(y_{i}\)</span> based on the probability of selecting firms A and B, <span class="math display">\[
\hat{\tau} = \frac{1}{2}\Big[\frac{3}{70/580} + \frac{10}{90/580}\Big]  = 44.7
\]</span></p>
<p><span class="emoji" data-emoji="question">❓</span> Was this a good estimate of <span class="math inline">\(\tau\)</span>? Why or why not?</p>
<blockquote class="blockquote">
<p>No! The population total <span class="math inline">\(\tau\)</span> is nearly double that of the estimate. However, the weighted mean is much closer to the true value than the unweighted mean is.</p>
</blockquote>
</section>
</section>
<section id="variability-of-estimates" class="level1 page-columns page-full">
<h1>Variability of Estimates</h1>
<div class="callout-note callout callout-style-simple no-icon callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
<span class="emoji" data-emoji="question">❓</span> <span class="emoji" data-emoji="busts_in_silhouette">👥</span> Turn and talk
</div>
</div>
<div class="callout-body-container callout-body">
<p>Why do we usually think of a parameter <span class="math inline">\(\mu\)</span> or <span class="math inline">\(p\)</span> as a fixed value, while the sample statistic <span class="math inline">\(\bar{x}\)</span> or <span class="math inline">\(\hat{p}\)</span> as a random variable?</p>
</div>
</div>
<blockquote class="blockquote">
<p>write your answer in HackMD.</p>
</blockquote>
<p>Along with the point estimate we also want to know how accurate we can expect the point estimate to be. In other words, if we took another random sample of the same size from the population, is the point estimate from this new sample likely to be similar to the first point estimate or are they likely to be far apart.</p>
<div class="callout-tip callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Example: Enrollment in Graduate Programs in Statistics
</div>
</div>
<div class="callout-body-container callout-body">
<p>Graduate programs in statistics often pay their graduate students, which means that many graduate students in statistics are able to attend graduate school tuition free with an assistantship or fellowship. There are 82 US statistics doctoral programs for which enrollment data were available. The data set <code>StatisticsPhD</code> lists all these schools together with the total enrollment of full-time graduate students in each program in 2009.</p>
<p><span class="emoji" data-emoji="question">❓</span> What is the average full-time graduate student enrollment in US statistics doctoral programs in 2009?</p>
</div>
</div>
<div class="page-columns page-full"><p></p><div class="no-row-height column-margin column-container"><span class="">I don’t feel like loading packages in this file so I’m using the <code>::</code> shortcut method to access the <code>here</code> and <code>read_csv</code> functions to load in the data.</span></div></div>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>stat.phd <span class="ot">&lt;-</span> readr<span class="sc">::</span><span class="fu">read_csv</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"data"</span>, <span class="st">"StatisticsPhD.csv"</span>))</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(stat.phd) <span class="co">#always look at your imported data to check for import errors</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
  University                      Department    FTGradEnrollment
  &lt;chr&gt;                           &lt;chr&gt;                    &lt;dbl&gt;
1 Baylor University               Statistics                  26
2 Boston University               Biostatistics               39
3 Brown University                Biostatistics               21
4 Carnegie Mellon University      Statistics                  39
5 Case Western Reserve University Statistics                  11
6 Colorado State University       Statistics                  14</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(stat.phd<span class="sc">$</span>FTGradEnrollment)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 53.53659</code></pre>
</div>
</div>
<p>Based on the data set, the mean enrollment in 2009 is 53.54 full-time graduate students. Because this is the mean for the entire population of all US statistics doctoral programs for which data were available that year, we have that <span class="math inline">\(\mu=53.54\)</span> students.</p>
<p><span class="emoji" data-emoji="star">⭐</span> Use the code below take a random sample of 10 programs from the data file and calculate the mean.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>my.sample.programs <span class="ot">&lt;-</span> <span class="fu">sample</span>(stat.phd<span class="sc">$</span>FTGradEnrollment, <span class="at">size=</span><span class="dv">10</span>)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(my.sample.programs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 48.5</code></pre>
</div>
</div>
<div class="callout-note callout callout-style-simple no-icon callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
<span class="emoji" data-emoji="question">❓</span> <span class="emoji" data-emoji="busts_in_silhouette">👥</span> Turn to your neighbor and discuss the following questions
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Did everyone get the same sample mean?</li>
<li>Does your sample mean exactly equal the population mean?</li>
<li>If you took another sample of 10, would you get the same sample mean? Why?</li>
<li>If we created a histogram of all our sample means, what would it look like? Where would it be centered at? What is the spread of the histogram?</li>
</ul>
</div>
</div>
<p>Knowing the behavior of of repeated sample statistics (like the mean in the prior example) is critically important. Let’s dig into this a little more by repeating this sampling experiment many times.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>many.means <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="at">n=</span><span class="dv">100</span>, {</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  my.sample.programs <span class="ot">&lt;-</span> <span class="fu">sample</span>(stat.phd<span class="sc">$</span>FTGradEnrollment, <span class="at">size=</span><span class="dv">10</span>)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mean</span>(my.sample.programs)</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>})</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="page-columns page-full"><p></p><div class="no-row-height column-margin column-container"><span class=""><span class="emoji" data-emoji="cry">😢</span> Getting an error with replicate? Take a step back and first make sure the internal code is working. Then add replicate with n=5, and DONT assign it to an object. Visually see with your eyes what the result of the <code>replicate</code> function gives you. Then once that is working, you can increase the number of replications, assign it as an object and explore the object.</span></div></div>
<p>Let’s visualize the distribution of all those sample means.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(many.means)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="cn03-statistical_foundations_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(many.means)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  30.90   46.95   52.65   53.91   60.83   83.50 </code></pre>
</div>
</div>
<p>Characteristics of this distribution:</p>
<ul>
<li><em>Shape</em>: The distribution of average enrollment isn’t quite normal, there seems to perhaps be two peaks?</li>
<li><em>Center</em>: The average enrollment is 53.91</li>
<li><em>Spread</em>: Average enrollment ranges from 30.9, 83.5.</li>
</ul>
<p><span class="emoji" data-emoji="tada">🎉</span> We have just created a <em>sampling distribution</em> of the sample mean.</p>
<section id="sampling-distribution" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="sampling-distribution">Sampling Distribution</h2>
<p>A <em>sampling distribution</em> is the distribution of sample statistics computed for different samples of the same size from the same population.</p>
<div class="callout-note callout callout-style-simple no-icon callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
<span class="emoji" data-emoji="question">❓</span> <span class="emoji" data-emoji="busts_in_silhouette">👥</span> Turn to your neighbor and discuss the following questions
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>What information might be important to get from a sampling distribution?</li>
<li>What would happen if we increased our sample size (<em>not the number of replicates</em>) to <span class="math inline">\(n=20\)</span> rather than <span class="math inline">\(n=10\)</span>. What about the sampling distribution would change?</li>
<li>What would happen if we increased the number of replications (holding <span class="math inline">\(n\)</span> constant) to 1000 instead of 100? What about the sampling distribution would change?</li>
</ul>
</div>
</div>
<div class="page-columns page-full"><p> In elementary statistics you were introduced to the “Central Limit Theorem” (CLT). The CLT states that the sampling distribution of <span class="math inline">\(\bar{y}\)</span> should be centered at <span class="math inline">\(\mu\)</span> with a standard deviation of <span class="math inline">\(\sigma/n\)</span>. It also states that the shape of the distribution should be approximately Normal for a large <span class="math inline">\(n\)</span>.</p><div class="no-row-height column-margin column-container"><span class="">The proof of the CLT is generally seen in a first graduate Statistics class that uses convergence in distribution concepts from MATH 420.</span></div></div>
</section>
</section>
<section id="properties-of-estimators" class="level1 page-columns page-full">
<h1>Properties of Estimators</h1>
<p>In general, suppose that <span class="math inline">\(\hat{\theta}\)</span> is an estimator of the parameter <span class="math inline">\(\theta\)</span>. Two properties that we would like <span class="math inline">\(\hat{\theta}\)</span> to have are</p>
<ol type="1">
<li>The estimate is <strong>unbiased</strong>: <span class="math inline">\(E(\hat{\theta}) = \theta\)</span>.</li>
<li>The estimate is <strong>precise</strong>: <span class="math inline">\(Var(\hat{\theta})\)</span> is small.</li>
</ol>
<p>To clarify:</p>
<ul>
<li><strong>Measurement bias</strong> means that the <span class="math inline">\(y\)</span>’s are measured inaccurately.
<ul>
<li>That means an estimator of a total <span class="math inline">\(t\)</span> calculated as <span class="math inline">\(\hat{t} = \sum_{i \in U} y_{i}\)</span> where <span class="math inline">\(U\)</span> is the entire universe, then <span class="math inline">\(\hat{t}\)</span> itself would not be the true total of interest.</li>
<li>Trying to estimate heights of students, but your ruler is always off 3 cm</li>
</ul></li>
<li><strong>Estimation bias</strong> means that the estimator chosen resulted in a bias.
<ul>
<li>If we calculated the total as <span class="math inline">\(t' = \sum_{i \in L} y_{i}\)</span> from a random sample of <span class="math inline">\(L\)</span> units in the universe, <span class="math inline">\(\hat{t'}\)</span> would be biased.</li>
<li>Trying to estimate heights of students by taking a sample of the shorter students only.</li>
</ul></li>
</ul>
<p>If two unbiased estimators are available for <span class="math inline">\(\theta\)</span> we generally prefer the one with the smaller variance.</p>
<p>Because sometimes we use biased estimators, we often use the <strong>Mean Squared Error (MSE)</strong> instead of the variance to estimate the <strong>accuracy</strong>.</p>
<div class="callout-important callout callout-style-default no-icon callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Definition: Bias, Variance, Accuracy
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math display">\[\mbox{Bias}(\hat{\theta}) = E(\hat{\theta}) - \theta\]</span></p>
<p><span class="math display">\[V(\hat{\theta})  = E \Big[(\hat{\theta} - E[\hat{\theta}])^2\Big]\]</span></p>
<p><span class="math display">\[\mbox{MSE}(\hat{\theta}) = V(\hat{\theta}) + [Bias(\hat{\theta})]^2\]</span></p>
</div>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figs/fig2_3.jpg" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Textbook Figure 2.3. Unbiased, precise and accurate archers.</figcaption><p></p>
</figure>
</div>
<ul>
<li>A is <strong>unbiased</strong>. The average position of all arrows is at the center of the target.</li>
<li>B is <strong>precise</strong> but not unbiased. All arrows are close together but systematically away from the center.</li>
<li>C is <strong>accurate</strong>. All arrows are close together and near the center of the target.</li>
</ul>
<div class="callout-tip callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Example
</div>
</div>
<div class="callout-body-container callout-body">
<p>Suppose probability samples of size <span class="math inline">\(n=2\)</span> are selected from the list <code>c(1,2,3,4)</code>, with <span class="math inline">\(\delta_{i}\)</span> probabilities <code>c(.4, .4, .1, .1)</code>. Demonstrate that <span class="math inline">\(\hat{\tau}\)</span> is an unbiased estimator of the population total <span class="math inline">\(\tau\)</span>, but its variance is 81.25.</p>
</div>
</div>
<div class="page-columns page-full"><p></p><div class="no-row-height column-margin column-container"><span class="">If you are not familiar with working with vectors and matrices in R, check out this <a href="https://www.youtube.com/watch?v=2TcPAZOyV0U">YouTube tutorial by MarinStats</a></span></div></div>
<p>Initial problem setup: Define data/sample/known values as objects in R.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">4</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>deltas <span class="ot">&lt;-</span> <span class="fu">c</span>(.<span class="dv">4</span>,.<span class="dv">4</span>,.<span class="dv">1</span>,.<span class="dv">1</span>)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>(tau <span class="ot">&lt;-</span> <span class="fu">sum</span>(x))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 10</code></pre>
</div>
</div>
<p>Create all possible samples of size <span class="math inline">\(n=2\)</span>, and add the probability of selection for that sample.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create all possible samples of size 2</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>universe <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(x, x)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(universe)[<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>] <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"x1"</span>, <span class="st">"x2"</span>) <span class="co"># rename first two columns for ease of reference</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Add the selection probabilities </span></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>universe<span class="sc">$</span>d1 <span class="ot">&lt;-</span> <span class="fu">rep</span>(deltas,<span class="dv">4</span>)</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>universe<span class="sc">$</span>d2 <span class="ot">&lt;-</span> <span class="fu">rep</span>(deltas, <span class="at">each=</span><span class="dv">4</span>)</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>universe</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   x1 x2  d1  d2
1   1  1 0.4 0.4
2   2  1 0.4 0.4
3   3  1 0.1 0.4
4   4  1 0.1 0.4
5   1  2 0.4 0.4
6   2  2 0.4 0.4
7   3  2 0.1 0.4
8   4  2 0.1 0.4
9   1  3 0.4 0.1
10  2  3 0.4 0.1
11  3  3 0.1 0.1
12  4  3 0.1 0.1
13  1  4 0.4 0.1
14  2  4 0.4 0.1
15  3  4 0.1 0.1
16  4  4 0.1 0.1</code></pre>
</div>
</div>
<div class="page-columns page-full"><p> Note the resulting object is a table/matrix with 16 rows and 4 columns, where each row is a possible sample of <span class="math inline">\(n=2\)</span> from the universe.</p><div class="no-row-height column-margin column-container"><span class="">An alternative method of creating the universe is to create separate vectors <code>x1 &lt;- rep(x,4); x2 &lt;- rep(x, each=4)</code>.</span></div></div>
<p>Now calculate <span class="math inline">\(\hat{\tau} = \frac{1}{2}\Big[\frac{x_1}{\delta_1} + \frac{x_2}{\delta_2}\Big]\)</span>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>universe<span class="sc">$</span>tau.hat <span class="ot">&lt;-</span> .<span class="dv">5</span><span class="sc">*</span>(universe<span class="sc">$</span>x1<span class="sc">/</span>universe<span class="sc">$</span>d1 <span class="sc">+</span> universe<span class="sc">$</span>x2<span class="sc">/</span>universe<span class="sc">$</span>d2)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(universe)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  x1 x2  d1  d2 tau.hat
1  1  1 0.4 0.4    2.50
2  2  1 0.4 0.4    3.75
3  3  1 0.1 0.4   16.25
4  4  1 0.1 0.4   21.25
5  1  2 0.4 0.4    3.75
6  2  2 0.4 0.4    5.00</code></pre>
</div>
</div>
<p><em>manually verify calculation</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>.<span class="dv">5</span><span class="sc">*</span>(<span class="dv">1</span><span class="sc">/</span>.<span class="dv">4</span> <span class="sc">+</span> <span class="dv">1</span><span class="sc">/</span>.<span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.5</code></pre>
</div>
</div>
<p>Now calculate <span class="math inline">\(E[\hat{\tau}] = \sum \hat{\tau}*p(\hat{\tau})\)</span> and <span class="math inline">\(V[\hat{\tau}] = E[\hat{\tau}] - E[\hat{\tau}]^2]\)</span>, where <span class="math inline">\(p(\hat{\tau}) = \delta_1*\delta_2\)</span> is the probability that sample is chosen.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate selection probability </span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>universe<span class="sc">$</span>p.hat.tau <span class="ot">&lt;-</span> universe<span class="sc">$</span>d1<span class="sc">*</span>universe<span class="sc">$</span>d2</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>(E.tau.hat <span class="ot">&lt;-</span> <span class="fu">sum</span>(universe<span class="sc">$</span>tau.hat <span class="sc">*</span> universe<span class="sc">$</span>p.hat.tau))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 10</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>(Var.tau.hat <span class="ot">&lt;-</span> <span class="fu">sum</span>(universe<span class="sc">$</span>tau.hat<span class="sc">^</span><span class="dv">2</span> <span class="sc">*</span> universe<span class="sc">$</span>p.hat.tau) <span class="sc">-</span> E.tau.hat<span class="sc">^</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 81.25</code></pre>
</div>
</div>
<div class="callout-warning callout callout-style-default no-icon callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
<span class="emoji" data-emoji="star">⭐</span> You try it
</div>
</div>
<div class="callout-body-container callout-body">
<p>Lohr Ch 2 exercises, #1.</p>
</div>
</div>
</section>
<section id="interval-estimation" class="level1 page-columns page-full">
<h1>Interval Estimation</h1>
<p>In general, it is usually not enough to just give a point estimate when estimating a population parameter. Why?</p>
<section id="bounds-on-estimators" class="level2">
<h2 class="anchored" data-anchor-id="bounds-on-estimators">Bounds on Estimators</h2>
<p>The objective of sampling is to estimate the population parameters, such as the mean or the total of a population from information contained in the sample. The experimenter controls the quantity of information by choosing an appropriate sample size. How can we determine how many sampling units to select?</p>
<blockquote class="blockquote">
<p>It depends on the magnitude of the error that we find acceptable.</p>
</blockquote>
<p>Suppose that we are trying to estimate some parameter <span class="math inline">\(\theta\)</span> using the sample estimator <span class="math inline">\(\hat{\theta}\)</span>. We want the value of <span class="math inline">\(\theta-\hat{\theta}\)</span> to be small. We refer to the value of <span class="math inline">\(\theta-\hat{\theta}\)</span> as the error because it is the difference between the estimated value and the true value.</p>
<div class="callout-note callout callout-style-simple no-icon callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
<span class="emoji" data-emoji="question">❓</span> <span class="emoji" data-emoji="busts_in_silhouette">👥</span> Turn &amp; talk
</div>
</div>
<div class="callout-body-container callout-body">
<p>What is the difference between the <em>error</em> and <em>bias</em>?</p>
</div>
</div>
<blockquote class="blockquote">
<ul>
<li>The <em>error</em> is the difference between the estimated value and the true value. *The <em>bias</em> is the difference in <em>expected value</em> of the estimator and the true value</li>
</ul>
</blockquote>
<p>We might want to specify that the absolute value of the error is less than some number, say <span class="math inline">\(B\)</span>. Thus, <span class="math display">\[
\mbox{Error of Estimation}=|\theta-\hat{\theta}|&lt;B
\]</span></p>
<p>We should also define a probability (<span class="math inline">\(1-\alpha\)</span>) such that our error is less than <span class="math inline">\(B\)</span> if we were to take repeated samples. <span class="math display">\[
P\left(|\theta-\hat{\theta}|&lt;B\right)=1-\alpha
\]</span></p>
<p>We will often select <span class="math inline">\(B\)</span> to be approximately 2 times the standard deviation of <span class="math inline">\(\hat{\theta}\)</span>, <span class="math inline">\(B=2\hat{\sigma}_{\hat{\theta}}\)</span>. As we saw earlier in <span class="citation" data-cites="ref">@ref</span>(#sampling-distribution), many of the statistics that we will discuss exhibit a normal sampling distribution even when the population distribution is skewed.</p>
</section>
<section id="standard-error" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="standard-error">Standard Error</h2>
<div class="callout-important callout callout-style-default no-icon callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Definition: Standard Error
</div>
</div>
<div class="callout-body-container callout-body">
<p>The <em>standard error</em> of a statistic is the standard deviation of the sample statistic. In other words, the standard deviation of the sampling distribution.</p>
</div>
</div>
<p>The standard error of a statistic tells us how much the sample statistic will vary from sample to sample. In situations like above where we can examine the distribution of the sample statistic using simulation, we can estimate the standard error by taking the sample standard deviation of the sampling distribution. In other situations we can use closed form mathematical formulas to calculate the standard error.</p>
<div class="callout-tip callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Example Grad program example cont.
</div>
</div>
<div class="callout-body-container callout-body">
<p>Estimate the standard error for the mean enrollment in statistics PhD programs for a sample size of 10 and also a sample size of 20.</p>
</div>
</div>
<div class="page-columns page-full"><p></p><div class="no-row-height column-margin column-container"><span class="">I used the base pipe <code>|&gt;</code> here to pass the results of the replicate function into the <code>sd()</code> function</span></div></div>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(many.means) <span class="co">#because the example above already had n=10</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 10.85981</code></pre>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">replicate</span>(<span class="at">n=</span><span class="dv">100</span>, {</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>  my.sample.programs <span class="ot">&lt;-</span> <span class="fu">sample</span>(stat.phd<span class="sc">$</span>FTGradEnrollment, <span class="at">size=</span><span class="dv">20</span>)</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mean</span>(my.sample.programs)</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>}) <span class="sc">|&gt;</span> <span class="fu">sd</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 6.451297</code></pre>
</div>
</div>
</section>
<section id="confidence-intervals" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="confidence-intervals">Confidence Intervals</h2>
<p>When the distributions are relatively symmetric and bell-shaped, the 95% rule tells us that approximately 95% of the data values fall within two standard deviations of the mean. Applying the 95% rule to sampling distributions, we see that about 95% of the sample statistics will fall within two standard errors of the mean. We use this rule many times to form what we call an approximate 95% confidence interval which gives us a range for which which we are quite confident that captures the true parameter we are trying to estimate.</p>
<p>When using a formula to calculate an approximate 95% confidence interval, use <span class="math inline">\(2*SE\)</span> as the margin of error.</p>
<div class="callout-tip callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
CI for PhD program enrollment
</div>
</div>
<div class="callout-body-container callout-body">
<p>Based on our example, what would be a 95% confidence interval for <span class="math inline">\(\mu\)</span> the true mean total enrollment for PhD programs in statistics. Interpret this confidence interval in context of the problem.</p>
</div>
</div>
<div class="page-columns page-full"><p></p><div class="no-row-height column-margin column-container"><span class="">Wrapping the entire line of code in <code>()</code> will execute that code AND print out the results. This lets me see the results in the rendered document AND store the results in an object to call later, like in my sentence response below.</span></div></div>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>(LCL <span class="ot">&lt;-</span> <span class="fu">mean</span>(many.means) <span class="sc">-</span> <span class="dv">2</span><span class="sc">*</span><span class="fu">sd</span>(many.means))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 32.19437</code></pre>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>(UCL <span class="ot">&lt;-</span> <span class="fu">mean</span>(many.means) <span class="sc">+</span> <span class="dv">2</span><span class="sc">*</span><span class="fu">sd</span>(many.means))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 75.63363</code></pre>
</div>
</div>
<div class="page-columns page-full"><p></p><div class="no-row-height column-margin column-container"><span class="">Every time I compile these notes, I draw a different sample and will get a different numbers. To avoid conflicts in my written response, and what the code shows, I use <em>inline R code</em> here. See the RStudio <em>Help –&gt; Markdown Quick Reference</em> for more information.</span></div></div>
<blockquote class="blockquote">
<p>We can be 95% confident that the true mean total enrollment for PhD programs in statistics is covered by the interval (32.2 , 75.6).</p>
</blockquote>
<div class="callout-note callout callout-style-simple no-icon callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
<span class="emoji" data-emoji="question">❓</span> <span class="emoji" data-emoji="busts_in_silhouette">👥</span> Turn &amp; talk
</div>
</div>
<div class="callout-body-container callout-body">
<p>Consider the following interpretation of the above confidence interval.</p>
<blockquote class="blockquote">
<p>We can be 95% confident that PhD programs in Statistics have a total enrollment of between 32.2 and 75.6 students.</p>
</blockquote>
<p>Why is this an incorrect interpretation?</p>
</div>
</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">This site is built with <span class="emoji" data-emoji="heart">❤️</span>, and <a href="https://quarto.org/">Quarto</a> by <a href="www.norcalbiostat.com">Robin Donatello</a>.</div>   
  </div>
</footer>



</body></html>