<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.319">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="DRAFT">
<meta name="dcterms.date" content="2025-04-01">
<meta name="description" content="When units are not necessarily nicely defined, even when the population is.">

<title>Sampling Methods - Cluster Sampling</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Sampling Methods</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../notes.html" rel="" target="">
 <span class="menu-text">Notes</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../assignments.html" rel="" target="">
 <span class="menu-text">Assignments</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../project.html" rel="" target="">
 <span class="menu-text">Project</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-hackmd-notes" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">HackMD Notes</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-hackmd-notes">    
        <li>
    <a class="dropdown-item" href="https://hackmd.io/@norcalbiostat/458_intro_hackmd" rel="" target="">
 <span class="dropdown-text">What is HackMD</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://hackmd.io/@norcalbiostat/cn01-intro_sampling" rel="" target="">
 <span class="dropdown-text">Ch 1. Sampling Framework</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://hackmd.io/@norcalbiostat/cn02-statistical_foundations" rel="" target="">
 <span class="dropdown-text">Ch 2. Foundations of Estimation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://hackmd.io/@norcalbiostat/cn04_stratified" rel="" target="">
 <span class="dropdown-text">Ch 3. Stratified Sampling</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://hackmd.io/@norcalbiostat/cn05_cluster" rel="" target="">
 <span class="dropdown-text">Ch 5. Cluster Sampling</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-bi-google" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
      <i class="bi bi-google" role="img">
</i> 
 <span class="menu-text"></span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-bi-google">    
        <li>
    <a class="dropdown-item" href="https://docs.google.com/spreadsheets/d/1Inj6xmMsoRcIHR5mpVShQisg5llXwesoDRuVRbvI5mY" rel="" target="">
 <span class="dropdown-text">Content creation group</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://docs.google.com/spreadsheets/d/1f4ze0905zE4HbtEyqVrJv1ncMB4EdNZDd4QJH5wewS0" rel="" target="">
 <span class="dropdown-text">Sechedule</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://drive.google.com/drive/folders/13YG6_6exekRfJr2NngUCO465UosodQGA" rel="" target="">
 <span class="dropdown-text">Project folder</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../formulas.html" rel="" target="">
 <span class="menu-text">Formulas and Definitions</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../syllabus.html" rel="" target="">
 <span class="menu-text">Syllabus</span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a>
  <ul class="collapse">
  <li><a href="#example-of-clustering" id="toc-example-of-clustering" class="nav-link" data-scroll-target="#example-of-clustering">Example of Clustering:</a></li>
  <li><a href="#why-use-cluster-sampling" id="toc-why-use-cluster-sampling" class="nav-link" data-scroll-target="#why-use-cluster-sampling">Why use Cluster Sampling?</a></li>
  <li><a href="#when-clusters-are-ignored" id="toc-when-clusters-are-ignored" class="nav-link" data-scroll-target="#when-clusters-are-ignored">When clusters are Ignored</a></li>
  </ul></li>
  <li><a href="#notation-formulas" id="toc-notation-formulas" class="nav-link" data-scroll-target="#notation-formulas">Notation &amp; Formulas</a></li>
  <li><a href="#one-stage-clustering-sampling" id="toc-one-stage-clustering-sampling" class="nav-link" data-scroll-target="#one-stage-clustering-sampling">One-Stage Clustering Sampling</a>
  <ul class="collapse">
  <li><a href="#equal-size-clusters-estimation" id="toc-equal-size-clusters-estimation" class="nav-link" data-scroll-target="#equal-size-clusters-estimation">Equal size clusters: Estimation</a>
  <ul class="collapse">
  <li><a href="#sampling-weights" id="toc-sampling-weights" class="nav-link" data-scroll-target="#sampling-weights">Sampling Weights</a></li>
  </ul></li>
  <li><a href="#equal-size-clusters-theory" id="toc-equal-size-clusters-theory" class="nav-link" data-scroll-target="#equal-size-clusters-theory">Equal size clusters: Theory</a>
  <ul class="collapse">
  <li><a href="#comparing-a-cluster-sample-with-an-srs-of-the-same-size" id="toc-comparing-a-cluster-sample-with-an-srs-of-the-same-size" class="nav-link" data-scroll-target="#comparing-a-cluster-sample-with-an-srs-of-the-same-size">Comparing a cluster sample with an SRS of the same size</a></li>
  </ul></li>
  <li><a href="#unequal-size-clusters" id="toc-unequal-size-clusters" class="nav-link" data-scroll-target="#unequal-size-clusters">Unequal size clusters</a>
  <ul class="collapse">
  <li><a href="#ratio-estimation" id="toc-ratio-estimation" class="nav-link" data-scroll-target="#ratio-estimation">Ratio Estimation</a></li>
  <li><a href="#estimation-using-weights" id="toc-estimation-using-weights" class="nav-link" data-scroll-target="#estimation-using-weights">Estimation using weights</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#two-stage-clustering-sampling" id="toc-two-stage-clustering-sampling" class="nav-link" data-scroll-target="#two-stage-clustering-sampling">Two-Stage Clustering Sampling</a>
  <ul class="collapse">
  <li><a href="#unbiased-estimator-of-population-total." id="toc-unbiased-estimator-of-population-total." class="nav-link" data-scroll-target="#unbiased-estimator-of-population-total.">Unbiased estimator of population total.</a></li>
  <li><a href="#survey-weights" id="toc-survey-weights" class="nav-link" data-scroll-target="#survey-weights">Survey weights</a></li>
  <li><a href="#variance-estimation-for-two-stage-cluster-samples." id="toc-variance-estimation-for-two-stage-cluster-samples." class="nav-link" data-scroll-target="#variance-estimation-for-two-stage-cluster-samples.">Variance estimation for two-stage cluster samples.</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Cluster Sampling</h1>
</div>

<div>
  <div class="description">
    When units are not necessarily nicely defined, even when the population is.
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>DRAFT </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">April 1, 2025</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse);<span class="fu">library</span>(knitr)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sampling); <span class="fu">library</span>(survey)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="introduction" class="level1">
<h1>Introduction</h1>
<div class="callout callout-style-default callout-important no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Sampling Units
</div>
</div>
<div class="callout-body-container callout-body">
<p>A <strong>psu</strong> or <strong>psus</strong> (plural) is the shortening of the term, primary sampling unit(s). These are the sampling units in a cluster sample. An alternate term is <strong>cluster</strong>.</p>
<p>A <strong>ssu</strong> or <strong>ssus</strong> (plural) is the shortening of the term, secondary sampling unit(s). These are the observation units observed within our clusters.</p>
</div>
</div>
<section id="example-of-clustering" class="level3">
<h3 class="anchored" data-anchor-id="example-of-clustering">Example of Clustering:</h3>
<p>When taking a survey of a community, rather than do an SRS of households, you might break up the community into blocks and take an SRS of blocks and sample all or some of the households that fall within those blocks. The blocks are your psus, and the households are your ssus. This method might be less costly if you were doing an in person survey, but might also be less accurate.</p>
</section>
<section id="why-use-cluster-sampling" class="level2">
<h2 class="anchored" data-anchor-id="why-use-cluster-sampling">Why use Cluster Sampling?</h2>
<p>Clustering is most common for its application.The purpose of stratifying a sample before was to better your prediction or accuracy when the variance varied quite differently among the population. It is not quite the same for Cluster Sampling, for it actually decreases in precision due to some positive correlation between unmeasurable factors that effect certain specific clusters.</p>
<p>We use Cluster Sampling when: 1. It may be unfeasible or expensive to construct a sampling frame of the population, and breaking into groups may make sampling doable. 2. In some populations, it’s less costly to sample in clusters, in terms of travel and time.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figs/fig5_1.jpg" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Textbook Figure 5.1. Contrasting stratified sampling with one-stage cluster sampling.</figcaption><p></p>
</figure>
</div>
</section>
<section id="when-clusters-are-ignored" class="level2">
<h2 class="anchored" data-anchor-id="when-clusters-are-ignored">When clusters are Ignored</h2>
<p>When clusters are ignored in the design or analysis phase, the sample can mistakenly be treated as if it were using the simple random sampling design. When they are ignored they can lead to incorrect formulas that have inaccurate conclusions. For example, when we analyze our sample as an SRS the variability can be underestimated on account of the clusters being designed to be more similar and homogeneous compared to an SRS and stratified sample. This will lead to values that are too small and confidence intervals that can be too narrow.</p>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Example: Studies in education
</div>
</div>
<div class="callout-body-container callout-body">
<p>Many studies in education (either involving teachers, students, other faculty, etc.) use cluster sampling for data collection. Clusters can include entire schools or even just individual classrooms. This is much more cost effective and logistically simpler than taking an SRS of individuals (students, staff, etc.).</p>
<p>One known example [conducted by Basow and Silberg (1987) and Basow and Martin (2012)] examined whether students rated professors differently based on gender (female vs male professors).</p>
</div>
</div>
<ul>
<li>In this study they took 16 female and 16 male professors and matched them by their subjects, experience, and tenure status.</li>
<li>They then sampled each of their classrooms full of students for data collection.</li>
<li>They, in total, collected 1029 individual student responses but since we are using cluster sampling the sample size will be n = 32 as there are 32 total clusters. The analysis would be wrong if we ignored that it was a cluster sample and treated it as an SRS of size 1029.</li>
</ul>
<p>This is a great real world example of how cluster sampling can streamline collecting important data while still gaining valuable insight.</p>
</section>
</section>
<section id="notation-formulas" class="level1">
<h1>Notation &amp; Formulas</h1>
<p>In SRS, each individual element is the sampling unit, and has an equal chance to be sampled. In stratified sampling, the population is divided into <span class="math inline">\(H\)</span> known strata, and a sample is taken from each. Our sampling unit in the cluster design is the entire cluster, or primary sampling unit <span class="math inline">\(psus\)</span>, and not the individual elements.</p>
<p>In stratified sampling we have our entire population being <span class="math inline">\(N\)</span> total population of each individual element, whereas our entire universe in cluster sampling is the number of clusters, that is <span class="math inline">\(N\)</span> is the number of <span class="math inline">\(psus\)</span>.</p>
<p>⚠️ Note notation change!</p>
<ul>
<li><span class="math inline">\(y_{ij}\)</span>: measurement for the <span class="math inline">\(j\)</span>th element in <span class="math inline">\(i\)</span>th psu</li>
<li><span class="math inline">\(N\)</span>: the number of clusters (psus) in the population
<ul>
<li><span class="math inline">\(n\)</span>: the number of psus from the sample</li>
</ul></li>
<li><span class="math inline">\(M_{i}\)</span>: number of ssus in psu <span class="math inline">\(i\)</span> in the population
<ul>
<li><span class="math inline">\(m_i\)</span>: the number of ssu’s in psu <span class="math inline">\(i\)</span> from the sample</li>
</ul></li>
<li><span class="math inline">\(M_{0}\)</span>: total number of ssus in the population</li>
</ul>
<table class="table">
<colgroup>
<col style="width: 29%">
<col style="width: 30%">
<col style="width: 40%">
</colgroup>
<thead>
<tr class="header">
<th>Population Quantity</th>
<th>Estimator <span class="math inline">\((\hat{\theta})\)</span></th>
<th>Estimated variance of <span class="math inline">\((\hat{\theta})\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Total in psu <span class="math inline">\(i\)</span>: <span class="math inline">\(t_{i}=\sum_{j} y_{ij}\)</span></td>
<td><span class="math inline">\(\hat{t}_{i} = \frac{M_{i}}{m_i}\sum_{j} y_{ij}\)</span></td>
<td>-</td>
</tr>
<tr class="even">
<td>Variance of psu totals : <span class="math inline">\(S_t^2 = \frac{1}{N-1} \sum_{i} \left( t_i - \frac{t}{N} \right)^2\)</span></td>
<td><span class="math inline">\(s_t^2 = \frac{1}{n-1} \sum_{i} \left( t_i - \frac{\hat{t}}{N} \right)^2\)</span></td>
<td><em>AKA variance between psu</em></td>
</tr>
<tr class="odd">
<td>Overall Total: <span class="math inline">\(t = \sum_{i} t_i\)</span></td>
<td><span class="math inline">\(\hat{t} = \frac{N}{n}\sum_{i} \hat{t}_i\)</span></td>
<td><span class="math inline">\(N^2 \left(1 - \frac{n}{N}\right) \frac{s_t^2}{n}\)</span></td>
</tr>
<tr class="even">
<td>mean in psu <span class="math inline">\(i\)</span>: <span class="math inline">\(\mu_{i} = \frac{1}{M_i} \sum_{j} y_{ij}\)</span></td>
<td><span class="math inline">\(\bar{y}_{i} = \frac{1}{m_i} \sum_{j} y_{ij}\)</span></td>
<td><span class="math inline">\(s_{i}^{2} = \frac{1}{m_i-1} \sum_{j} (y_{ij}-\bar{y}_{i})^2\)</span> (<em>AKA variance within psu</em>)</td>
</tr>
<tr class="odd">
<td>Overall mean: <span class="math inline">\(\mu = \frac{1}{M_0} \sum_{i} \sum_{j} y_{ij}\)</span></td>
<td><span class="math inline">\(\bar{y} = \frac{\hat{t}}{NM}\)</span></td>
<td><span class="math inline">\(\left( 1 - \frac{n}{N} \right) \frac{s_t^2}{nM^2}\)</span></td>
</tr>
</tbody>
</table>
<p>Overall there are many differences between clustering, stratification, and SRS, that are important to note.</p>
<hr>
</section>
<section id="one-stage-clustering-sampling" class="level1">
<h1>One-Stage Clustering Sampling</h1>
<section id="equal-size-clusters-estimation" class="level2">
<h2 class="anchored" data-anchor-id="equal-size-clusters-estimation">Equal size clusters: Estimation</h2>
<p>One-stage clustering is the type of clustering you’re probably already familiar with - either all (or none) of the observations inside of a cluster (psu) are sampled.</p>
<p>While this is an unrealistic scenario for most statistical work in the social sciences, agricultural or industrial surveys may be able to take advantage of the much simpler process that equal size clustering brings.</p>
<p>Because the psus are selected through an SRS, we can use the per-cluster estimates as single observations in an SRS. There’s no need to consider the individual ssus within each cluster. <strong>Important distinction: we treat this as an SRS of <span class="math inline">\(n\)</span> psus, not an SRS of <span class="math inline">\(nM\)</span> observational units.</strong></p>
<p>In this setup, we typically aim to estimate the population total or mean of a variable of interest based on the totals from each sampled cluster.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Example 5.2: Average GPA in a dorm
</div>
</div>
<div class="callout-body-container callout-body">
<p>Perhaps we want to estimate the average GPA in a college dormitory with a one-stage cluster design. The dorm consists of 100 units, each with 4 students. Here’s the process:</p>
<ol type="1">
<li>An SRS is conducted to select 5 clusters.<br>
</li>
<li>All 4 students (ssus) per dormitory unit (psus) have their GPAs measured</li>
<li>Calculate your estimates based on your <em>psu</em> statistics, not your ssu measurements.</li>
</ol>
<p><em>(Slightly modified version of Example 5.2 from Lohr’s R Companion to Sampling 3rd ed.&nbsp;Page 57. DOI: 10.1201/9781003228196-5)</em></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>gpa <span class="ot">&lt;-</span> readr<span class="sc">::</span><span class="fu">read_csv</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"data"</span>, <span class="st">"gpa.csv"</span>))</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="dv">100</span> <span class="co"># total dorm population (this won't be NROW(gpa)!)</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">5</span>   <span class="co"># total number of clusters/psus selected</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>M <span class="ot">&lt;-</span> <span class="dv">4</span>   <span class="co"># observational units/ssus selected per psu</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
<section id="using-equations" class="level4">
<h4 class="anchored" data-anchor-id="using-equations">Using equations</h4>
<p>To estimate the mean, we first estimate the total (because it’s easier math).</p>
<p>The estimated total is calculated by a weighted sum of the cluster totals. <span class="math display">\[
\hat{t} = \frac{N}{n} \sum_{i \in S} t_i
\]</span></p>
<p>We can use the <code>tapply</code> function to calculate the sum of <code>gpa</code> across each <code>suite</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>(suitesum <span class="ot">&lt;-</span> <span class="fu">tapply</span>(gpa<span class="sc">$</span>gpa, gpa<span class="sc">$</span>suite, sum))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    1     2     3     4     5 
12.16 11.36  8.96 12.96 11.08 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># gpa %&gt;% group_by(suite) %&gt;% summarize(t_i = sum(gpa)) # alternative method</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The variance across these totals can be found using the standard variance formula: <span class="math display">\[
s_t^2 = \frac{1}{n-1} \sum_{i \in S} \left( t_i - \frac{\hat{t}}{N} \right)^2
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>(st2 <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">var</span>(suitesum), <span class="at">digits =</span> <span class="dv">3</span>)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.256</code></pre>
</div>
</div>
<p>Now we can convert these estimates of the total to estimates of the mean using:</p>
<p><span class="math display">\[
\hat{y} = \frac{\hat{t}}{NM} \qquad \mbox{ and } \qquad \text{SE}(\hat{y}) = \frac{1}{M} \sqrt{\left(1 - \frac{n}{N}\right) \frac{s_t^2}{n}}
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>t.hat <span class="ot">&lt;-</span> <span class="fu">sum</span>(suitesum)<span class="sc">*</span>(N<span class="sc">/</span>n)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>(y.bar.hat <span class="ot">&lt;-</span> t.hat<span class="sc">/</span>(M<span class="sc">*</span>N))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.826</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>(se.ybar.yat <span class="ot">&lt;-</span> (<span class="dv">1</span><span class="sc">/</span>M)<span class="sc">*</span><span class="fu">sqrt</span>((<span class="dv">1</span><span class="sc">-</span>n<span class="sc">/</span>N)<span class="sc">*</span>(st2<span class="sc">/</span>n)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1636765</code></pre>
</div>
</div>
</section>
<section id="using-the-survey-package" class="level4">
<h4 class="anchored" data-anchor-id="using-the-survey-package">Using the <code>survey</code> package</h4>
<p>Create a survey design for one-stage clustering</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>OSC_gpa <span class="ot">&lt;-</span> <span class="fu">svydesign</span>(<span class="at">id =</span> <span class="sc">~</span>suite,</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>                     <span class="at">weights =</span> <span class="sc">~</span>wt,<span class="co">#already on the data set</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>                     <span class="at">fpc =</span> <span class="sc">~</span><span class="fu">rep</span>(<span class="dv">100</span>,<span class="dv">20</span>),</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>                     <span class="at">data =</span> gpa)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>calculate the mean GPA with SE</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">svymean</span>(<span class="sc">~</span>gpa, OSC_gpa)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     mean     SE
gpa 2.826 0.1637</code></pre>
</div>
</div>
</section>
<section id="section" class="level4">
<h4 class="anchored" data-anchor-id="section"></h4>
</section>
<section id="sampling-weights" class="level3">
<h3 class="anchored" data-anchor-id="sampling-weights">Sampling Weights</h3>
<p>In one-stage cluster sampling with equal-sized clusters, each cluster is treated as a single observation. The sampling weight for each observation unit <span class="math inline">\(j\)</span> in PSU <span class="math inline">\(i\)</span> is based on the inverse probability of that PSU being selected. This results in a <strong>self-weighting sample</strong>, meaning every sampled element gets the same weight.</p>
<p><span class="math display">\[
w_{ij} = \frac{N}{n}
\]</span></p>
<p>The total sampling weight across all sampled units equals the total number of units in the population (<span class="math inline">\(NM\)</span>). Make sure to always verify that the sum of your weights matches the population size. Population total and mean can also be estimated using these weights by summing the weighted values or averaging them appropriately.</p>
<p>This weighting approach allows you to use one-stage cluster sampling estimates similarly to how you’d handle stratified or SRS data, despite the cluster structure.</p>
<hr>
</section>
</section>
<section id="equal-size-clusters-theory" class="level2">
<h2 class="anchored" data-anchor-id="equal-size-clusters-theory">Equal size clusters: Theory</h2>
<section id="comparing-a-cluster-sample-with-an-srs-of-the-same-size" class="level3">
<h3 class="anchored" data-anchor-id="comparing-a-cluster-sample-with-an-srs-of-the-same-size">Comparing a cluster sample with an SRS of the same size</h3>
<div class="callout callout-style-default callout-important no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
ANalysis Of VAriance
</div>
</div>
<div class="callout-body-container callout-body">
<p>Don’t recall how ANOVA works to break up the variance into components? See <a href="https://www.youtube.com/watch?v=W36DMVJ4Ibo&amp;list=PLkIselvEzpM5G3IO1tzQ-DUThsJKQzQCD">this great video</a> from the Open Intro Statistics author, Mine Cetinkaya-Rundel</p>
</div>
</div>
<div class="callout callout-style-default callout-important no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
MSB (Mean Squared Between psus)
</div>
</div>
<div class="callout-body-container callout-body">
<p>The sum of squares between psus (SSB) measures the variability across the psu means. The mean squared between psus (MSB) is the SSB divided by the number of psus -1.</p>
<p><span class="math display">\[
SSB =  \sum_{i} \left( \bar{y}_i - \bar{y} \right)^2  \qquad  MSB = \frac{SSB}{N - 1}
\]</span></p>
<p>If MSB is relatively large, it means that there is more of a difference between data points in different clusters than within the same clusters</p>
</div>
</div>
<p>For cluster sampling, the variability of the unbiased estimator of <span class="math inline">\(t\)</span> depends entirely on between the psus rather than within psus.</p>
<p><span class="math display">\[V(\hat t_{cluster}) = N^2 (1 - \frac{n}{N}) \Big( \frac{M(MSB)}{n}\Big)\]</span></p>
<div class="callout callout-style-default callout-important no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
MSW (Mean Squared Within psus)
</div>
</div>
<div class="callout-body-container callout-body">
<p>The sum of squares within psus (SSB) measures the variability within the psus. The MSW is the SSW divided by the total number of ssus minus the number of psus.</p>
<p><span class="math display">\[
SSW = \sum_{i} \sum_{j} \left( y_{ij} - \bar{y}_i \right)^2 \qquad
MSW = \frac{SSW}{N(M-1)}
\]</span></p>
</div>
</div>
<p>The MSW is not used for calculating the variance in cluster sampling like it is in stratified sampling. While stratified sampling is best when there is a lot of variance within strata, cluster sampling is less effective if there’s a lot of variance within psus.</p>
<p>If the ratio of MSB/MSW is large, it means that stratified sampling will be more precise and cluster sampling will be less precise.</p>
<div class="callout callout-style-default callout-important no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
ICC (Intraclass Correlation Coefficient)
</div>
</div>
<div class="callout-body-container callout-body">
<p>The ICC measures how similar items are within the same group or cluster. It helps determine the usefulness of cluster sampling for a specific sample.</p>
</div>
</div>
<p>A high ICC means that items in the same cluster are very similar, indicating a high level of homogeneity. A low ICC means that items within the cluster are more different from each other.</p>
<p>The higher the ICC, the less efficient the sample is compared to simple random sampling (SRS). This is because high ICC indicates redundancy within clusters. The loss in precision due to clustering can be estimated by comparing the variance of cluster sampling over the variance of the SRS.</p>
<p>ICC is typically positive in naturally occurring clusters. For example, wealthy families living in the same neighborhood, or crops in a field exposed to the same pesticide levels, are likely to show positive ICC due to environmental or social factors.</p>
<p>In contrast, ICC can be negative in artificially constructed or systematic clusters. A negative ICC indicates that items within a cluster are more dispersed than in a randomly selected group. This often results in cluster means being roughly equal, and in such cases, cluster sampling can actually be more efficient than SRS.</p>
<div class="callout callout-style-default callout-important no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Adjusted R Squared
</div>
</div>
<div class="callout-body-container callout-body">
<p>Adjusted R^2 can be used as an alternative measure of homogeneity due to it being very close to the ICC in many populations. The adj R^2 can only be used as a replacement in cases where all primary sampling units (psus) are the same size.</p>
<p><span class="math display">\[ 1 - \frac{MSW}{S^2} \]</span></p>
</div>
</div>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Example 5.3. Consider two artificial populations
</div>
</div>
<div class="callout-body-container callout-body">
<p>Refer to the textbook for numeric specifics</p>
<ul>
<li>A &amp; B both come from the same population, and when sampled each has 3 clusters and 3 elements (ssus) inside each cluster.</li>
<li>Even though they share the same <span class="math inline">\(S^2\)</span> and <span class="math inline">\(\bar{y}\)</span> there variances differ in a real specific way.
<ul>
<li>Population A has a large variance within each cluster which is reflected in the negative ICC and <span class="math inline">\(R^2\)</span>.</li>
<li>Whereas, in Population B the variance occurs mostly between clusters.</li>
</ul></li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Example 5.5. When is a cluster not a cluster?
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>When it’s the whole population!</strong></p>
<p>In Example 4.5 (in Chapter 4), we look at data from a study evaluating the effects of feral pig activity and drought on the native vegetation in Santa Cruz Island in California.</p>
</div>
</div>
<p>In that example, the <em>sampling unit</em> was a single tree, the <em>observational unit</em> was a single seedling by the tree, and the <em>population of interest</em> was all the trees on Santa Cruz Island. Then, an SRS was conducted!</p>
<p>But we’re doing cluster sampling right now. So, suppose that the researcher was instead interested in seedling survival across all of California. The researcher would have divided the regions into equal-sized areas, randomly-selected some of those areas to study, and recorded the measurements.</p>
<p><strong>The sampling unit is no longer a tree, it’s an area!</strong></p>
<p>So, if Santa Cruz Island was selected as one of those <em>areas</em> in our study about all of California, then we could no longer treat the trees from Santa Cruz Island as though they were part of an SRS from all trees in California. They’re all similar trees, from the same island, that experience identical climates, in almost the same soil. We would expect all ten trees on Santa Cruz Island to experience, as a group, different environmental factors (such as weather conditions and numbers of seedling eaters) than the ten trees selected in the Santa Ynez Valley on the mainland. Thus the ICC within each cluster (area) would likely be positive.</p>
<p><strong>But…</strong></p>
<p>What if we were only interested in the seedlings <em>from</em> the 10th tree on Santa Cruz Island? Then, the population is <em>all seedlings from the 10th tree</em> and the psu is the <em>seedling</em>. At this point, we’re not doing cluster sampling, we’re doing a census of the population!</p>
</section>
</section>
<section id="unequal-size-clusters" class="level2">
<h2 class="anchored" data-anchor-id="unequal-size-clusters">Unequal size clusters</h2>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Motivating Example: Census of 1937
</div>
</div>
<div class="callout-body-container callout-body">
<p>In the Enumerative Check Census of 1937, they took a 2% sample of postal routes (psus), and questionnaires were give to every household(ssus) on each chosen postal routes. Since not all postal routes had the same number of households, this survey was a clustered sample with clusters of unequal sizes. The variable they were investigating, the total number of unemployed people, was impacted within each cluster by the size of the cluster. The more people on a route, the more unemployed people on the postal route. This means that the between variance of the cluster totals would be higher. Something else to note about this survey is that they only knew the number of houses in each of the <em>selected</em> groups.</p>
</div>
</div>
<p>The <strong>unbiased estimator(s)</strong> for the total are: <span class="math display">\[\hat t_{unb} = \frac{N}{n}\sum_{i \in S}t_i \qquad \mbox{ with } \qquad SE(\hat t_{unb}) = N \sqrt{(1-\frac{n}{N})(\frac{s_t^2}{n})}\]</span></p>
<ul>
<li>Note that the error of the estimator is dependent on the variance of the cluster totals (<span class="math inline">\(s_t^2\)</span>)</li>
<li>The variation among the individual cluster totals <span class="math inline">\(t_i\)</span> is likely to be large when clusters have different sizes.</li>
</ul>
<p><span class="math display">\[M_0 = \sum_{i}^N M_i\]</span></p>
<p><span class="math display">\[\hat{\bar{y}}_{unb} = \hat t_{unb}/M_0\]</span></p>
<p><span class="math display">\[SE(\hat{\bar{y}}_{unb}) = SE(\hat t_{unb})/M_0\]</span></p>
<ul>
<li>The size of every psu is needed to be known for this formula.</li>
<li>The unbiased estimator for the mean can be inefficient when values of M_i’s are unequal for the same reasons the unbiased estimate of the total can be inefficient</li>
<li>A ratio estimator of the mean often has smaller variance.</li>
</ul>
<section id="ratio-estimation" class="level3">
<h3 class="anchored" data-anchor-id="ratio-estimation">Ratio Estimation</h3>
<p>We usually expect <span class="math inline">\(t_i\)</span> to be positively correlated with <span class="math inline">\(M_i\)</span>.</p>
<ul>
<li>Example: If the primary sampling units (PSUs) are counties, we would expect the total number of households living in poverty in county <span class="math inline">\(i(t_i)\)</span> to be roughly proportional to the total number of households in the country <span class="math inline">\(i(M_i)\)</span></li>
</ul>
<p>Therefore our population mean is a ratio where <span class="math inline">\(t_i\)</span> and <span class="math inline">\(m_i\)</span> are positively correlated. We define that now as:</p>
<p><span class="math display">\[
\widehat{\bar{y_r}} = \frac{\hat{t}_{umb}}{\widehat{M_0}} = \frac{\frac{N}{n} \sum_{i \in S} t_i}{\frac{N}{n} \sum_{i \in S} M_i} = \frac{\sum_{i \in S} M_i \bar{y_i} }{\sum_{i \in S} M_i}
\]</span></p>
<ul>
<li>The estimator <span class="math inline">\(\widehat{\bar{y_r}}\)</span> is the quantity <span class="math inline">\(B\)</span> in 4.1. (Our sample’s ratio mean.)</li>
</ul>
<p>The denominator is a random quantity that depends on which particular clusters are included in the sample. If the <span class="math inline">\(M_i\)</span> are unequal and a different cluster sample of size <span class="math inline">\(n\)</span> is taken, the denominator will likely be different. From taking <span class="math inline">\(e_i = t_i - M_i \widehat{ \bar{y_r}} = M_i (\bar{y}_i - \widehat{\bar{y_i}})\)</span> we have:</p>
<p><span class="math display">\[\text{SE}(\widehat{\bar{y_r}}) = \sqrt{\left(1 - \frac{n}{N}\right) \frac{s_r^2}{nM^2}}\]</span></p>
<p>and,</p>
<p><span class="math display">\[
s_r^2 = \frac{1}{n-1} \sum_{i \in S} M_i^2 \left( \bar{y}_i - \widehat{\bar{y_i}}\right)^2
\]</span></p>
<ul>
<li><span class="math inline">\(\bar{M} = \frac{\widehat{M_0}}{N}\)</span> represents the average size of the PSUs in the sample.</li>
<li>The variance of the ratio estimator depends on the variability of the means per element in the PSUs and can be much smaller than that of the unbiased estimator <span class="math inline">\(\hat{\bar{y}}_{unb}\)</span>.</li>
<li>This can also be done when we know our cluster sizes.</li>
</ul>
</section>
<section id="estimation-using-weights" class="level3">
<h3 class="anchored" data-anchor-id="estimation-using-weights">Estimation using weights</h3>
<p><span class="math display">\[
w_{ij} = \frac{1}{\mbox{probability of w_{ij} being in the sample}} = \frac{N}{n}
\]</span></p>
<ul>
<li>One stage clustering has self-weighting samples no matter whether the clusters are equal sizes or not</li>
<li>In clusters of equal sizes, the weights sum to the population size but in clusters of unequal sizes the sum of the weights <em>estimates</em> the population size.</li>
</ul>
<p><span class="math display">\[\hat M_0=\sum_{i\in S}\sum_{j \in S_i}w_{ij} = \frac{N}{n}\sum_{i \in S}\]</span></p>
<ul>
<li><span class="math inline">\(\hat M_0\)</span> is a random variable, different for every sample.</li>
</ul>
<p>Using weights:</p>
<p><span class="math display">\[\hat t_{unb} = \sum_{i\in S}\sum_{j \in S_i}w_{ij}y_{ij}\]</span></p>
<p><span class="math display">\[\hat{\bar{y_r}}= \frac{\sum_{i\in S}\sum_{j \in S_i}w_{ij}y_{ij}}{\sum_{i\in S}\sum_{j \in S_i}w_{ij}}\]</span></p>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Example. High school Algebra
</div>
</div>
<div class="callout-body-container callout-body">
<p>Consider a population of 187 high school algebra classes in a city. An investigator takes an SRS of classes, and gives each student in the sampled classes a test about function knowledge. The (hypothetical) data are given in the file <code>algebra.csv</code>.</p>
</div>
</div>
<ol type="a">
<li>Load in the data and look at the first few rows. Explain what the values in each column mean.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>algebra <span class="ot">&lt;-</span> readr<span class="sc">::</span><span class="fu">read_csv</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"data"</span>, <span class="st">"algebra.csv"</span>))</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(algebra)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
  class    Mi score
  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1    23    20    57
2    23    20    90
3    23    20    56
4    23    20    57
5    23    20    46
6    23    20    55</code></pre>
</div>
</div>
<ul>
<li>Each row is a student, with three columns: <code>class</code>, <code>Mi</code>, and <code>score</code>.</li>
<li><code>class</code> is a number representing which class the student is in. These are the psus.</li>
<li><code>Mi</code> is the number of students in that specific class. For class 23, there are 20 students.</li>
<li><code>score</code> is the score the student earned on the given test.</li>
</ul>
<ol start="2" type="a">
<li>Plot the distribution of test score by class. Interpret your graph by comparing the medians, ranges, and variances across classes. What do you notice?</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>algebra<span class="sc">$</span>class <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(algebra<span class="sc">$</span>class)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(algebra, <span class="fu">aes</span>(<span class="at">x =</span> class, <span class="at">y =</span> score)) <span class="sc">+</span> <span class="fu">geom_boxplot</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="cn05-cluster_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>algebra <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(class) <span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="at">median =</span> <span class="fu">median</span>(score),</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>                                          <span class="at">min =</span> <span class="fu">min</span>(score),</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>                                          <span class="at">max =</span> <span class="fu">max</span>(score),</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>                                          <span class="at">var =</span> <span class="fu">var</span>(score))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12 × 5
   class median   min   max   var
   &lt;fct&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
 1 23      58      25    90  310.
 2 37      64      24   100  461.
 3 38      58.5    24   100  420.
 4 39      54      32    89  200.
 5 41      58.5    19    87  188.
 6 44      64.5    27   100  193.
 7 46      49      34    88  253.
 8 51      71.5    22   100  329.
 9 58      51      28   100  546.
10 62      71      31    99  282.
11 106     67.5    14    94  355.
12 108     69.5    31   100  227.</code></pre>
</div>
</div>
<p>There is a large range between the minimum and the maximum score in each class, with all of the minimums being between 14 and 34 and all of the maximums being between 87 and 100. We can also see some pretty large differences in median between classes, for example Class 46 has a median score of 49.0 and Class 51 has a median score of 71.5. For variance, the lowest class is Class 41 with about 188, and the largest class is Class 58 with about 546.</p>
<ol start="3" type="a">
<li>How many <em>psus</em> are there? What is the <em>psu</em> with the highest number of <em>ssus</em>? Which one has the least? You must answer this question using R functions such as<code>unique</code> or <code>table</code>. Don’t count this by hand (practice for when you have a billion rows)</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>(n <span class="ot">&lt;-</span> <span class="fu">length</span>(<span class="fu">unique</span>(algebra<span class="sc">$</span>class))) <span class="co"># Total number of psu</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 12</code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>psu <span class="ot">&lt;-</span> <span class="fu">table</span>(algebra<span class="sc">$</span>class)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>(psu.max.ssu<span class="ot">&lt;-</span> <span class="fu">names</span>(<span class="fu">which.max</span>(psu))) <span class="co"># PSU with most SSUs</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "39"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>(max.ssu<span class="ot">&lt;-</span> <span class="fu">max</span>(algebra<span class="sc">$</span>Mi)) <span class="co">#This shows the max SSU</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 34</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>(psu.min.ssu<span class="ot">&lt;-</span> <span class="fu">names</span>(<span class="fu">which.min</span>(psu))) <span class="co"># PSU with fewest SSUs</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "58"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>(min.ssu<span class="ot">&lt;-</span><span class="fu">min</span>(algebra<span class="sc">$</span>Mi)) <span class="co">#This shows the minimum SSU</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 17</code></pre>
</div>
</div>
<p>There are 12 psus which are the classes. The psu with the highest number of ssus is class 39 with 34 ssus, and the smallest ssus is class 58 with 17 ssus.</p>
<ol start="4" type="a">
<li>Add variables containing the weights and the <code>fpc</code> to this data set.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="dv">187</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>algebra <span class="ot">&lt;-</span> algebra <span class="sc">%&gt;%</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">wt =</span> N<span class="sc">/</span>n, </span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">fpc=</span><span class="fu">rep</span>(<span class="dv">187</span>,<span class="dv">299</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol start="5" type="a">
<li>Using the proper functions from the <code>survey</code> package, estimate the population average algebra score, with a 95% interval and interpret your interval. Be sure to NOT assume a Z-distribution for this confidence interval but use the <code>degf</code> function to get the proper degrees of freedom out of the survey design object and pass it to the <code>confint</code> function.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>design <span class="ot">&lt;-</span> <span class="fu">svydesign</span>(</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">id =</span> <span class="sc">~</span>class,</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">fpc =</span> <span class="sc">~</span>Mi,</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">weights =</span> <span class="sc">~</span>wt, </span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> algebra</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a><span class="co"># the mean</span></span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>mean_estimate <span class="ot">&lt;-</span> <span class="fu">svymean</span>(<span class="sc">~</span>score, design)</span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a><span class="co"># degrees of freedom function</span></span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">degf</span>(design)</span>
<span id="cb31-13"><a href="#cb31-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-14"><a href="#cb31-14" aria-hidden="true" tabindex="-1"></a><span class="co">#conf. interval, t distribution</span></span>
<span id="cb31-15"><a href="#cb31-15" aria-hidden="true" tabindex="-1"></a>ci <span class="ot">&lt;-</span> <span class="fu">confint</span>(mean_estimate, <span class="at">df =</span> df)</span>
<span id="cb31-16"><a href="#cb31-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-17"><a href="#cb31-17" aria-hidden="true" tabindex="-1"></a>(mean_estimate)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        mean     SE
score 62.569 0.9752</code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>(ci)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         2.5 %   97.5 %
score 60.42224 64.71488</code></pre>
</div>
</div>
<hr>
</section>
</section>
</section>
<section id="two-stage-clustering-sampling" class="level1">
<h1>Two-Stage Clustering Sampling</h1>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figs/fig5_2.jpg" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Textbook Figure 5.2. Differences between one-stage and two-stage cluster sampling.</figcaption><p></p>
</figure>
</div>
<section id="unbiased-estimator-of-population-total." class="level2">
<h2 class="anchored" data-anchor-id="unbiased-estimator-of-population-total.">Unbiased estimator of population total.</h2>
<p>To estimate the total for each PSU (<span class="math inline">\(\hat{t_i}\)</span>) we multiply the total number of SSUs in a PSU (<span class="math inline">\(i\)</span>) <em>by</em> the average of the sampled SSUs in a PSU (<span class="math inline">\(i\)</span>). This is then used in equation (5.21) to get the unbiased estimate of the total population. This is essentially scaling up the estimates using the known sizes:</p>
<ul>
<li><span class="math inline">\(N\)</span> (total number of PSUs in the population)</li>
<li><span class="math inline">\(n\)</span> (Number of PSUs sampled)</li>
<li><span class="math inline">\(M_i\)</span> (total number of SSUs in PSU_i)</li>
<li><span class="math inline">\(m_i\)</span> (number of SSUs actually sampled in PSU_i).</li>
</ul>
</section>
<section id="survey-weights" class="level2">
<h2 class="anchored" data-anchor-id="survey-weights">Survey weights</h2>
<p>The chance of selecting any SSU depends on:</p>
<ol type="1">
<li>The chance that its PSU was selected in the first stage.</li>
<li>The chance that the SSU was selected in the second stage within that PSU.</li>
</ol>
<p>The sampling weight for each SSU is the reciprocal of its selection probability. It tells you how many units in the population that one SSU is meant to represent.</p>
<p>If all PSUs sample SSUs in proportion to their size, the design is self-weighting.</p>
<p><span class="math display">\[w_i = NM_i / nm_i\]</span></p>
</section>
<section id="variance-estimation-for-two-stage-cluster-samples." class="level2">
<h2 class="anchored" data-anchor-id="variance-estimation-for-two-stage-cluster-samples.">Variance estimation for two-stage cluster samples.</h2>
<p>Variance <span class="math inline">\(\hat{t}\)</span> has 2 components: the variability between psu’s and the variability of of ssus within psu’s.( We don’t have to worry about this with one stage clustering.)</p>
<p>Essentially what the equation is doing is proving that the second term in the 5.24 equation goes to zero so you don’t need to account for this. The equation below calculates the variance for the sample variance among psu totals and then calcs the sample variance within the psu i.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Example 5.7: More estimation of math scores.
</div>
</div>
<div class="callout-body-container callout-body">
<p>The file <code>schools.csv</code> contains data from a two-stage sample of students from hypothetical classes. The final weights are provided in the variable <code>finalwt</code>.</p>
<ul>
<li>During the first stage of sampling, an SRS of size n = 10 schools was selected from a population of N = 75 schools overall.</li>
<li>During the second stage of sampling, an SRS of size <span class="math inline">\(m_i\)</span> = 20 students was selected from each sampled school.</li>
<li>Tests for reading and math scores were administered for individuals.</li>
</ul>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>schools <span class="ot">&lt;-</span> readr<span class="sc">::</span><span class="fu">read_csv</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"data"</span>, <span class="st">"schools.csv"</span>))</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="co">#factorizing our school ids</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>schools<span class="sc">$</span>schoolid <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(schools<span class="sc">$</span>schoolid)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>a) Create side by side boxplots for the math score for sampled schools. Which do you think is larger, the within or between cluster variance?</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(schools, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span>(schoolid, math, <span class="at">FUN =</span> median), </span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>                    <span class="at">y =</span> math, <span class="at">fill =</span> schoolid)) <span class="sc">+</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"School ID"</span>, <span class="at">y =</span> <span class="st">"Math Score"</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="cn05-cluster_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>From the way the medians of each of the schools differ from each other greatly, it seems that the between cluster variance is greater than the within cluster variance.</p>
<p><strong>b) Create an ANOVA table for this example. Is your interpretation from the graph upheld by this analysis?</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">aov</span>(math <span class="sc">~</span> schoolid, <span class="at">data=</span>schools) <span class="sc">|&gt;</span> <span class="fu">summary</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Df Sum Sq Mean Sq F value   Pr(&gt;F)    
schoolid      9   7018   779.8   7.583 1.79e-09 ***
Residuals   190  19538   102.8                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Yes. The Mean Sq for the first row of the Anova table is the between clusters mean squares(MSB), while the second row’s Mean Sq is the within clusters mean squared (MSW). Since the MSB is seven times the MSW, the Anova table supports our hypothesis that the variance between clusters(schools in this example) is greater than the variance within clusters.</p>
<p><strong>c) Estimate with proper 95% CI the average math score for the population of students under consideration.</strong></p>
<p>Since we don’t have the knowledge about the population to calculate the fpc, we will treat this sample as if it were taken with replacement and not use the finite population corrector in the survey design for using the survey package.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>dschools <span class="ot">&lt;-</span> <span class="fu">svydesign</span>(<span class="at">id=</span><span class="sc">~</span>schoolid,</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>                      <span class="at">weights=</span><span class="sc">~</span>finalwt,</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>                      <span class="at">data=</span>schools)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We will save the <code>mathmean</code> information to use to calculate our confidence interval</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>mathmean <span class="ot">&lt;-</span> <span class="fu">svymean</span>(<span class="sc">~</span>math,dschools)</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>mathmean</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       mean     SE
math 33.123 1.7599</code></pre>
</div>
</div>
<p>This is the confidence interval using the t-distribution with 9 degrees of freedom since we have 10 schools, or clusters, within our sample. Note that our degrees of freedom is the number of psus - 1, not the number of ssus - 1. This is a cluster sample, not an SRS.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(mathmean,<span class="at">df=</span><span class="fu">degf</span>(dschools))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        2.5 %  97.5 %
math 29.14179 37.1041</code></pre>
</div>
</div>
<p>Our sample mean math score is 33. We are 95% confident that the true average math score for the population we are considering is between 29 and 37.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">This site is built with <span class="emoji" data-emoji="heart">❤️</span>, <a href="https://posit.co/">R</a> and <a href="https://quarto.org/">Quarto</a> by <a href="www.norcalbiostat.com">Robin Donatello</a> and the Spring 2025 Math 458 class</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>



</body></html>