<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.319">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="DRAFT - 458 class">
<meta name="dcterms.date" content="2023-03-20">
<meta name="description" content="A method to use additional information about the population in the survey design. Lohr Ch 3.">

<title>Sampling Methods - Stratified Sampling</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Sampling Methods</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../weekly_details.html" rel="" target="">
 <span class="menu-text">Weekly Overview</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../notes.html" rel="" target="">
 <span class="menu-text">Notes</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../assignments.html" rel="" target="">
 <span class="menu-text">Assignments</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-hackmd" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">HackMD</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-hackmd">    
        <li>
    <a class="dropdown-item" href="https://hackmd.io/@norcalbiostat/sampling_r_resources" rel="" target="">
 <span class="dropdown-text">R resources</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://hackmd.io/@norcalbiostat/458_intro_hackmd" rel="" target="">
 <span class="dropdown-text">What is HackMD</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://hackmd.io/@norcalbiostat/cn02-intro_sampling" rel="" target="">
 <span class="dropdown-text">Sampling Framework notes</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://hackmd.io/@norcalbiostat/cn03-statistical_foundations" rel="" target="">
 <span class="dropdown-text">Foundations of Estimation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://hackmd.io/@norcalbiostat/cn06_stratified" rel="" target="">
 <span class="dropdown-text">Stratified Sampling</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://hackmd.io/@norcalbiostat/cn07_cluster" rel="" target="">
 <span class="dropdown-text">Cluster Sampling</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../syllabus.html" rel="" target="">
 <span class="menu-text">Syllabus</span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#what-is-stratified-sampling" id="toc-what-is-stratified-sampling" class="nav-link active" data-scroll-target="#what-is-stratified-sampling">What is Stratified Sampling</a>
  <ul class="collapse">
  <li><a href="#overview" id="toc-overview" class="nav-link" data-scroll-target="#overview">Overview</a>
  <ul class="collapse">
  <li><a href="#why-use-a-stratified-sample" id="toc-why-use-a-stratified-sample" class="nav-link" data-scroll-target="#why-use-a-stratified-sample">Why Use A Stratified Sample?</a></li>
  </ul></li>
  <li><a href="#gain-from-stratification" id="toc-gain-from-stratification" class="nav-link" data-scroll-target="#gain-from-stratification">Gain from stratification</a></li>
  </ul></li>
  <li><a href="#theory-of-stratified-sampling" id="toc-theory-of-stratified-sampling" class="nav-link" data-scroll-target="#theory-of-stratified-sampling">Theory of Stratified Sampling</a>
  <ul class="collapse">
  <li><a href="#notation-and-formulas-used-in-stratified-random-sampling" id="toc-notation-and-formulas-used-in-stratified-random-sampling" class="nav-link" data-scroll-target="#notation-and-formulas-used-in-stratified-random-sampling">Notation and Formulas used in Stratified Random Sampling</a></li>
  <li><a href="#confidence-interval-for-stratified-random-sample" id="toc-confidence-interval-for-stratified-random-sample" class="nav-link" data-scroll-target="#confidence-interval-for-stratified-random-sample">Confidence Interval for Stratified Random Sample</a></li>
  </ul></li>
  <li><a href="#sampling-weights" id="toc-sampling-weights" class="nav-link" data-scroll-target="#sampling-weights">Sampling Weights</a>
  <ul class="collapse">
  <li><a href="#how-are-weights-calculated" id="toc-how-are-weights-calculated" class="nav-link" data-scroll-target="#how-are-weights-calculated">How are weights calculated?</a></li>
  <li><a href="#how-are-weights-used" id="toc-how-are-weights-used" class="nav-link" data-scroll-target="#how-are-weights-used">How are weights used?</a></li>
  </ul></li>
  <li><a href="#allocation-methods" id="toc-allocation-methods" class="nav-link" data-scroll-target="#allocation-methods">Allocation Methods</a>
  <ul class="collapse">
  <li><a href="#which-allocation-to-use" id="toc-which-allocation-to-use" class="nav-link" data-scroll-target="#which-allocation-to-use">Which allocation to use?</a></li>
  </ul></li>
  <li><a href="#selecting-strata" id="toc-selecting-strata" class="nav-link" data-scroll-target="#selecting-strata">Selecting Strata</a>
  <ul class="collapse">
  <li><a href="#defining-strata" id="toc-defining-strata" class="nav-link" data-scroll-target="#defining-strata">Defining Strata</a></li>
  <li><a href="#how-many-strata" id="toc-how-many-strata" class="nav-link" data-scroll-target="#how-many-strata">How Many Strata?</a></li>
  </ul></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary">Summary</a></li>
  <li><a href="#using-r" id="toc-using-r" class="nav-link" data-scroll-target="#using-r">Using R</a>
  <ul class="collapse">
  <li><a href="#selecting-a-stratified-random-sample" id="toc-selecting-a-stratified-random-sample" class="nav-link" data-scroll-target="#selecting-a-stratified-random-sample">Selecting a Stratified Random Sample</a>
  <ul class="collapse">
  <li><a href="#using-the-strata-function-from-the-sampling-package" id="toc-using-the-strata-function-from-the-sampling-package" class="nav-link" data-scroll-target="#using-the-strata-function-from-the-sampling-package">Using the <code>strata</code> function from the <code>sampling</code> package</a></li>
  </ul></li>
  <li><a href="#computing-statistics-from-a-stratified-random-sample" id="toc-computing-statistics-from-a-stratified-random-sample" class="nav-link" data-scroll-target="#computing-statistics-from-a-stratified-random-sample">Computing Statistics from a Stratified Random Sample</a>
  <ul class="collapse">
  <li><a href="#setup-the-information-for-the-survey-design." id="toc-setup-the-information-for-the-survey-design." class="nav-link" data-scroll-target="#setup-the-information-for-the-survey-design.">1. Setup the information for the survey design.</a></li>
  <li><a href="#call-svydesign" id="toc-call-svydesign" class="nav-link" data-scroll-target="#call-svydesign">2. Call <code>svydesign</code></a></li>
  <li><a href="#calculate-total-se-and-ci" id="toc-calculate-total-se-and-ci" class="nav-link" data-scroll-target="#calculate-total-se-and-ci">3. Calculate total, SE and CI</a></li>
  <li><a href="#calculating-stratum-means-and-variances" id="toc-calculating-stratum-means-and-variances" class="nav-link" data-scroll-target="#calculating-stratum-means-and-variances">Calculating stratum means and variances</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Stratified Sampling</h1>
</div>

<div>
  <div class="description">
    A method to use additional information about the population in the survey design. Lohr Ch 3.
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>DRAFT - 458 class </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">March 20, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(here); <span class="fu">library</span>(tidyverse);<span class="fu">library</span>(knitr)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sampling); <span class="fu">library</span>(survey)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="what-is-stratified-sampling" class="level1">
<h1>What is Stratified Sampling</h1>
<section id="overview" class="level2">
<h2 class="anchored" data-anchor-id="overview">Overview</h2>
<ul>
<li>A sampling technique in which we divide the desired population into subgroups called <em>strata</em></li>
<li>Each individual is necessarily in a single strata; no overlap within strata</li>
<li>All strata consist of the entire population</li>
<li>An SRS is taken from each strata, then results can be pooled to make inferences about the entire population</li>
</ul>
<section id="why-use-a-stratified-sample" class="level3">
<h3 class="anchored" data-anchor-id="why-use-a-stratified-sample">Why Use A Stratified Sample?</h3>
<ul>
<li>Protection from bad samples; less likely of drawing a non representative sample through pure chance</li>
<li>Want data of known subgroups (i.e., if we are interested in people’s heights, we know that men tend to be taller than women)</li>
<li>Convenience / cost effectiveness – At what point will this compromise the legitimacy of the study?</li>
<li>Lowers variance when done properly; variance within each strata is likely lower than the population variance</li>
<li>you do not have to sample the same fraction of observations in each stratum. If the variability is higher in a certain strata then you can try to reduce the variability of the estimated total by taking more observations from that stratum.</li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Motivating Example - Estimating the average number of farm acres.
</div>
</div>
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>agpop <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="fu">here</span>(<span class="st">"data"</span>, <span class="st">"agpop.csv"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In Example 2.6 we took a SRS to find the average number of farm acres per county. Even though our methods of taking an SRS were correct, some areas of the country were over or underrepresented due to the variability in the size of farms in different regions in the country. An example of this would be that western states in the U.S tend to be larger, and therefore tend to have larger farms.</p>
</div>
</div>
<p>To try and fix this, we can use a stratified sample can give balance to the sample on the stratifying variable, which in this case would be region that the farms are located.</p>
<p>To begin, we can divide our data into four regions (these are the strata):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(agpop<span class="sc">$</span>region) <span class="co"># the four regions and their names</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "W"  "S"  "NE" "NC"</code></pre>
</div>
</div>
<p>Previously we sampled 10% of the population with an SRS, and so to be able to compare our results with our stratified sample, we should sample 10% of the population from each strata through four separate and independent SRS’s.</p>
<p>The process to do this would be to take the four regions, number off the counties that are in the region, calculate what number of counties is 10% of the total number of counties in the region, and select that many numbers from the list of numbered counties.</p>
<blockquote class="blockquote">
<p><em>Details on how to do this in R is covered in a later section. For now we will use the <code>agstrat</code> dataset from the book as the stratified sample.</em></p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>agstrat <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="fu">here</span>(<span class="st">"data"</span>, <span class="st">"agstrat.csv"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exploring the distribution of farm acreage in 1992 by region.
</div>
</div>
<div class="callout-body-container callout-body">
<div class="cell fig-cap-location-top">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(acres92<span class="sc">/</span><span class="dv">10</span><span class="sc">^</span><span class="dv">6</span> <span class="sc">~</span> region, <span class="at">data =</span> agstrat,</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">xlab =</span> <span class="st">"Region"</span>, <span class="at">ylab =</span> <span class="st">"Millions of Acres"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="cn06-stratified_sampling_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">The thick line for each region is the median of the sample data from that region. The upper and lower horizontal lines of the boxes are the 25th and 75th percentiles.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>The Northeast has the lowest median and the smallest variance. The West has the highest median and the highest mean and variance. The distribution of farm acreage appears to to be positively skewed in each region.</p>
</div>
</div>
<p>The summary statistics <span class="math inline">\(\bar{y}_{h}\)</span> and <span class="math inline">\(s^{2}_{h}\)</span> can be calculated using R after grouping by the stratification variable.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>table3<span class="fl">.1</span> <span class="ot">&lt;-</span> agstrat <span class="sc">%&gt;%</span> </span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>   <span class="fu">group_by</span>(region) <span class="sc">%&gt;%</span> </span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>   <span class="fu">summarize</span>(<span class="at">y.bar.h =</span> <span class="fu">mean</span>(acres92),</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">s2.h    =</span> <span class="fu">var</span>(acres92),</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>             <span class="at">n.h     =</span> <span class="fu">n</span>())</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>counties_in_pop <span class="ot">&lt;-</span> <span class="fu">table</span>(agpop<span class="sc">$</span>region)</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>new_table3<span class="fl">.1</span> <span class="ot">&lt;-</span> <span class="fu">cbind</span>(table3<span class="fl">.1</span>, counties_in_pop)</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>new_table3<span class="fl">.1</span> <span class="ot">&lt;-</span> <span class="fu">select</span>(new_table3<span class="fl">.1</span>, <span class="sc">-</span>Var1) <span class="co"># drop the extra variable </span></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(new_table3<span class="fl">.1</span>) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Region"</span>, <span class="st">"Sample Avg in Region"</span>, <span class="st">"Sample Variance in Region"</span>, </span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a><span class="st">"Number of Counties in Region"</span>, <span class="st">"Number of Counties in Population"</span>)</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(new_table3<span class="fl">.1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 6%">
<col style="width: 18%">
<col style="width: 22%">
<col style="width: 25%">
<col style="width: 28%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Region</th>
<th style="text-align: right;">Sample Avg in Region</th>
<th style="text-align: right;">Sample Variance in Region</th>
<th style="text-align: right;">Number of Counties in Region</th>
<th style="text-align: right;">Number of Counties in Population</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">NC</td>
<td style="text-align: right;">300504.16</td>
<td style="text-align: right;">29618183543</td>
<td style="text-align: right;">103</td>
<td style="text-align: right;">1054</td>
</tr>
<tr class="even">
<td style="text-align: left;">NE</td>
<td style="text-align: right;">97629.81</td>
<td style="text-align: right;">7647472708</td>
<td style="text-align: right;">21</td>
<td style="text-align: right;">220</td>
</tr>
<tr class="odd">
<td style="text-align: left;">S</td>
<td style="text-align: right;">211315.04</td>
<td style="text-align: right;">53587487856</td>
<td style="text-align: right;">135</td>
<td style="text-align: right;">1382</td>
</tr>
<tr class="even">
<td style="text-align: left;">W</td>
<td style="text-align: right;">662295.51</td>
<td style="text-align: right;">396185950266</td>
<td style="text-align: right;">41</td>
<td style="text-align: right;">422</td>
</tr>
</tbody>
</table>
<p>Lohr Table 3.1. Summary statistics for each stratum</p>
</div>
</div>
<p>These summary statistics can be used to calculate estimates of the total number of farms acres, and estimated variance of the total within each of the four stratum (Table 3.2 below)</p>
<p>Because we took an SRS in each stratum, we can use the following equations to estimate population quantities for each stratum.</p>
<p><span class="math inline">\(\hat{\tau_{h}} = N * \bar{y}_{h} \quad \mbox{ and } \quad \hat{V}(\hat{\tau}_{h}) = N_{h}^{2} * \hat{V}(\bar{y}_{h})\)</span></p>
<ul>
<li>We can estimate the total number of acres devoted to farming in the United States in 1992 by summing the estimated totals for each stratum.</li>
<li>The variance of the total is the sum of the variances of the estimated stratum totals.</li>
</ul>
<blockquote class="blockquote">
<p>More information on how to do this in the next section.</p>
</blockquote>
<div class="callout callout-style-default callout-warning no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="emoji" data-emoji="star">⭐</span> You try it.
</div>
</div>
<div class="callout-body-container callout-body">
<p>Explore the distribution of farm acreage in 1987 by region. Create a table of summary statistics and a boxplot. Discuss your findings.</p>
</div>
</div>
<div class="callout callout-style-simple callout-warning no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>agstrat <span class="sc">%&gt;%</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(region) <span class="sc">%&gt;%</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">y.bar =</span> <span class="fu">mean</span>(farms87),</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">s2 =</span> <span class="fu">var</span>(farms87),</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">n. =</span><span class="fu">n</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 4
  region y.bar      s2    n.
  &lt;chr&gt;  &lt;dbl&gt;   &lt;dbl&gt; &lt;int&gt;
1 NC      837. 156050.   103
2 NE      605. 175660.    21
3 S       610. 231169.   135
4 W       615. 275507.    41</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(agstrat, <span class="fu">aes</span>(<span class="at">x =</span> region, <span class="at">y =</span> farms87, <span class="at">fill =</span> region)) <span class="sc">+</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Box Plot of Farm acreage in 1987 by Region"</span>,</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Region"</span>,</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Acreage"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="cn06-stratified_sampling_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Both the boxplot and the table suggest that, on average, farms in the north-central region have the most acreage (837 acres). The mean acreages in the North East, South, and West regions are similar, ranging from 605-615 acres. The variances for all four regions are large, suggesting the individual acreage of the farms varies greatly and is not precise. The results indicate that the quantity’s mean value for area North Central is 837.0485 with a variance of 156503.3 and a sample size of 103. The mean value for area North East is 605.2381, with a variance of 175660.4 and a sample size of 21. With a sample size of 135 and a variance of 231169.2, the mean value for region South is 610.4889. For region West with a sample size of 41, the mean value is 614.7073 with a variance of 275506.9.</p>
</div>
</div>
</div>
</section>
</section>
<section id="gain-from-stratification" class="level2">
<h2 class="anchored" data-anchor-id="gain-from-stratification">Gain from stratification</h2>
<ul>
<li>Observations within strata are more similar to each other, than they are to the population as a whole</li>
<li>reduction in variance in individual strata can lead to a reduced variance for the population estimate.</li>
</ul>
<div class="callout callout-style-default callout-important no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Definition: Relative gain from stratification
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math display">\[
\frac{\hat{Var_{strata}}}{\hat{Var_{SRS}}}
\]</span></p>
</div>
</div>
<p>From the Farm example, this ratio was calculated to be 0.75. That means we would only need 0.75*300 = 225 observations from a stratified sample to obtain the same precision as from a SRS of 300.</p>
<blockquote class="blockquote">
<p>By sampling within strata, we are “borrowing” information from other similar observations.</p>
</blockquote>
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Clean up
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(counties_in_pop, table3<span class="fl">.1</span>, new_table3<span class="fl">.1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
</section>
</section>
<section id="theory-of-stratified-sampling" class="level1">
<h1>Theory of Stratified Sampling</h1>
<section id="notation-and-formulas-used-in-stratified-random-sampling" class="level2">
<h2 class="anchored" data-anchor-id="notation-and-formulas-used-in-stratified-random-sampling">Notation and Formulas used in Stratified Random Sampling</h2>
<ul>
<li>To take a stratified random sample, we take a SRS from each stratum, so that <span class="math inline">\(n_h\)</span> units are sampled from the <span class="math inline">\(N_h\)</span> population units in stratum <span class="math inline">\(h\)</span>.</li>
<li>Statistics and sample sizes for stratum <span class="math inline">\(h\)</span> have subscript <span class="math inline">\(h\)</span> where <span class="math inline">\(h=1 \ldots H\)</span> index strata</li>
<li>When a statistic has the subscript <span class="math inline">\(str\)</span>, that means that the statistic is the combined estimate across all stratas.
<ul>
<li><span class="math inline">\(\bar{y}_{str}\)</span> is a weighted average of the sample stratum means</li>
<li><span class="math inline">\(\hat{p}_{str}\)</span> estimated proportion of population units having a specified characteristic. <em>Recall a proportion is a mean of a variable that takes on the values 0 and 1.</em></li>
</ul></li>
<li><span class="math inline">\(y_{hj}\)</span> value of the <span class="math inline">\(j\)</span>th unit in strata <span class="math inline">\(h\)</span></li>
<li><span class="math inline">\(\sum_{j=1}^{n_{h}}\)</span> means to sum of <em>all</em> units in strata <span class="math inline">\(h\)</span></li>
<li><span class="math inline">\(\sum_{j}\)</span> means to sum over the units that were sampled from in strata <span class="math inline">\(h\)</span></li>
<li><span class="math inline">\(\sum_{h}\)</span> is shorthand for <span class="math inline">\(\sum_{H=1}^{h}\)</span></li>
</ul>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true">Formulas</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false">Explanations</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<table class="table">
<colgroup>
<col style="width: 23%">
<col style="width: 38%">
<col style="width: 38%">
</colgroup>
<thead>
<tr class="header">
<th>Measure</th>
<th>Population <span class="math inline">\((\theta)\)</span></th>
<th>Sample <span class="math inline">\((\hat{\theta})\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Sample size in strata <span class="math inline">\(h\)</span></td>
<td><span class="math inline">\(N_{h}\)</span></td>
<td><span class="math inline">\(n_{h}\)</span></td>
</tr>
<tr class="even">
<td>Overall sample size</td>
<td><span class="math inline">\(N = \sum^{H}_{h=1} N_{h}\)</span></td>
<td><span class="math inline">\(n = \sum^{H}_{h=1} n_{h}\)</span></td>
</tr>
<tr class="odd">
<td>Var(y) in strata <span class="math inline">\(h\)</span></td>
<td><span class="math inline">\(\sigma_{h}^2 = \frac{1}{N_{h}-1}\sum_{j=1}^{N_{h}}(y_{hj}-\mu_{h})^2\)</span></td>
<td><span class="math inline">\(s_{h}^2 = \frac{1}{n_{h}-1}\sum_{j}(y_{hj}-\bar{y}_{h})^2\)</span></td>
</tr>
<tr class="even">
<td>Total in strata <span class="math inline">\(h\)</span></td>
<td><span class="math inline">\(\tau_{h} = \sum_{j=1}^{N_{h}} y_{hj}\)</span></td>
<td><span class="math inline">\(\hat{\tau}_{h} = N_{h}\bar{y_h}\)</span></td>
</tr>
<tr class="odd">
<td>Overall total</td>
<td><span class="math inline">\(\tau = \sum_{h=1}^{H} \tau_{h}\)</span></td>
<td><span class="math inline">\(\hat{\tau}_{str} = \sum_{h=1}^{H}N_{h}\bar{y}_{h}\)</span></td>
</tr>
<tr class="even">
<td>Mean in strata <span class="math inline">\(h\)</span></td>
<td><span class="math inline">\(\mu_{h} = \frac{\tau_{h}}{N_{h}}\)</span></td>
<td><span class="math inline">\(\bar{y}_{h} = \frac{1}{n_{h}}\sum_{j} y_{hj}\)</span></td>
</tr>
<tr class="odd">
<td>Overall mean</td>
<td><span class="math inline">\(\mu = \frac{\tau}{N}\)</span></td>
<td><span class="math inline">\(\bar{y}_{str} = \sum_{h=1}^{H} \frac{N_{h}}{N}\bar{y}_{h}\)</span></td>
</tr>
<tr class="even">
<td>Proportion in strata <span class="math inline">\(h\)</span></td>
<td><span class="math inline">\(p_{h} = \mu_h\)</span></td>
<td><span class="math inline">\(\bar{y}_h = \hat{p}_h\)</span></td>
</tr>
<tr class="odd">
<td>Variance of <span class="math inline">\(p_{h}\)</span></td>
<td><span class="math inline">\(\sigma_h^2=\frac{N_h}{N_h-1} p_h(1-p_h)\)</span></td>
<td><span class="math inline">\(s_h^2=\frac{n_h}{n_h-1} \hat{p}_h(1-\hat{p}_h)\)</span></td>
</tr>
<tr class="even">
<td>Overall proportion</td>
<td><span class="math inline">\(p_{str} = \sum_{h=1}^{H} \frac{N_h}{N} p_h\)</span></td>
<td><span class="math inline">\(\hat{p}_{str} = \sum_{h=1}^{H} \frac{N_h}{N}\hat{p}_h\)</span></td>
</tr>
</tbody>
</table>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<table class="table">
<colgroup>
<col style="width: 25%">
<col style="width: 37%">
<col style="width: 37%">
</colgroup>
<thead>
<tr class="header">
<th>Measure</th>
<th>Population <span class="math inline">\((\theta)\)</span></th>
<th>Sample <span class="math inline">\((\hat{\theta})\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Sample size in strata <span class="math inline">\(h\)</span></td>
<td>number of population units in stratum h</td>
<td>sample size taken in stratum h</td>
</tr>
<tr class="even">
<td>Overall sample size</td>
<td>total population size, from all strata</td>
<td>total sample size, from all strata</td>
</tr>
<tr class="odd">
<td>Total in strata <span class="math inline">\(h\)</span></td>
<td>population total in strata h</td>
<td>estimated population total in stratum h</td>
</tr>
<tr class="even">
<td>Overall total</td>
<td>population total</td>
<td>estimated population total</td>
</tr>
<tr class="odd">
<td>Mean in strata <span class="math inline">\(h\)</span></td>
<td>population mean in strata h</td>
<td>sample mean in stratum h</td>
</tr>
<tr class="even">
<td>Overall mean</td>
<td>population mean</td>
<td>weighted average of the sample stratum means</td>
</tr>
<tr class="odd">
<td>Variance of the mean</td>
<td>population variance in stratum h</td>
<td>sample variance in stratum h</td>
</tr>
<tr class="even">
<td>Proportion in strata <span class="math inline">\(h\)</span></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>Variance of proportion</td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Overall proportion</td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>With estimated variances;</p>
<ul>
<li>Within strata total <span class="math inline">\(\hat{V}(\hat{\tau}_{h}) = (1-\frac{n_h}{N_h})N^2 \frac{s^2_h}{n_h}\)</span><br>
</li>
<li>Within strata mean <span class="math inline">\(\hat{V}(\bar{y}_{h}) = \frac{1}{N^2}V(\hat{\tau}_{h})\)</span></li>
<li>Overall population total <span class="math inline">\(\hat{V}(\hat{\tau}_{str}) = \sum_{h=1}^H (1-\frac{n_h}{N_h})N^2 \frac{s^2_h}{n_h}\)</span></li>
<li>Population proportion <span class="math inline">\(\hat{V}(\hat{p}_{str}) = \sum_{h=1}^H (1-\frac{n_h}{N_h}) (\frac{N_h}{N})^2 \frac{\hat{p}_h (1-\hat{p}_h)}{n_h-1}\)</span></li>
<li>Estimated total number of population units having a specified characteristic: <span class="math inline">\(\hat{t}_{\it{str}} = \sum_{h=1}^H N_h \hat{p}_h\)</span></li>
</ul>
</section>
<section id="confidence-interval-for-stratified-random-sample" class="level2">
<h2 class="anchored" data-anchor-id="confidence-interval-for-stratified-random-sample">Confidence Interval for Stratified Random Sample</h2>
<p>If either the sample sizes within each stratum are large or the sampling design has a large number of strata, then the confidence interval for the population mean <span class="math inline">\(\bar{y}\mu\)</span> is:</p>
<p><span class="math display">\[ \bar{y}_{str}= \pm z_{\alpha /2 } SE (\bar{y}_{str})\]</span></p>
<p>However, most survey packages use a <span class="math inline">\(t_{n-H}\)</span> distribution instead of using the normal assumption.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Example: Estimate the total number of farm acres in 1992 (Table 3.2)
</div>
</div>
<div class="callout-body-container callout-body">
<p>The best way to understand an equation, is to try to use it in a calculation.</p>
</div>
</div>
<ol type="1">
<li>Calculate summary statistics for each region. <em>This was seen earlier as <code>new_table3.1</code></em></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>strata.summary.stats <span class="ot">&lt;-</span> agstrat <span class="sc">%&gt;%</span> </span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>   <span class="fu">group_by</span>(region) <span class="sc">%&gt;%</span> </span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>   <span class="fu">summarize</span>(<span class="at">y.bar.h =</span> <span class="fu">mean</span>(acres92),</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">s2.h    =</span> <span class="fu">var</span>(acres92),</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>             <span class="at">n.h     =</span> <span class="fu">n</span>()) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol start="2" type="1">
<li>Calculate Population region sizes, add this vector to the data frame created above.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>(region.size <span class="ot">&lt;-</span> agpop <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(region) <span class="sc">%&gt;%</span> <span class="fu">tally</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 2
  region     n
  &lt;chr&gt;  &lt;int&gt;
1 NC      1054
2 NE       220
3 S       1382
4 W        422</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>strata.summary.stats<span class="sc">$</span>N.h <span class="ot">&lt;-</span> region.size<span class="sc">$</span>n</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>strata.summary.stats</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 5
  region y.bar.h          s2.h   n.h   N.h
  &lt;chr&gt;    &lt;dbl&gt;         &lt;dbl&gt; &lt;int&gt; &lt;int&gt;
1 NC     300504.  29618183543.   103  1054
2 NE      97630.   7647472708.    21   220
3 S      211315.  53587487856.   135  1382
4 W      662296. 396185950266.    41   422</code></pre>
</div>
</div>
<ol start="3" type="1">
<li>Calculate the sample total <span class="math inline">\(\hat{\tau}_{h} = N_{h}\bar{y_h}\)</span>.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>strata.summary.stats<span class="sc">$</span>tau.hat.h <span class="ot">&lt;-</span> strata.summary.stats<span class="sc">$</span>y.bar.h <span class="sc">*</span> strata.summary.stats<span class="sc">$</span>N.h</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>strata.summary.stats</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 6
  region y.bar.h          s2.h   n.h   N.h  tau.hat.h
  &lt;chr&gt;    &lt;dbl&gt;         &lt;dbl&gt; &lt;int&gt; &lt;int&gt;      &lt;dbl&gt;
1 NC     300504.  29618183543.   103  1054 316731380.
2 NE      97630.   7647472708.    21   220  21478558.
3 S      211315.  53587487856.   135  1382 292037391.
4 W      662296. 396185950266.    41   422 279488706.</code></pre>
</div>
</div>
<ol start="4" type="1">
<li>Calculate the within-strata variance of this total <span class="math inline">\(\Big(1 - \frac{n_{h}}{N_{h}}\Big)N^{2}_{h}\frac{s^{2}_{h}}{n_{h}}\)</span>.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>strata.summary.stats <span class="ot">&lt;-</span> strata.summary.stats <span class="sc">%&gt;%</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">var.tau.hat.h =</span> </span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>           (<span class="dv">1</span> <span class="sc">-</span> n.h<span class="sc">/</span>N.h)<span class="sc">*</span>(N.h<span class="sc">^</span><span class="dv">2</span>)<span class="sc">*</span>(s2.h<span class="sc">/</span>n.h)</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>strata.summary.stats</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 7
  region y.bar.h          s2.h   n.h   N.h  tau.hat.h var.tau.hat.h
  &lt;chr&gt;    &lt;dbl&gt;         &lt;dbl&gt; &lt;int&gt; &lt;int&gt;      &lt;dbl&gt;         &lt;dbl&gt;
1 NC     300504.  29618183543.   103  1054 316731380.       2.88e14
2 NE      97630.   7647472708.    21   220  21478558.       1.59e13
3 S      211315.  53587487856.   135  1382 292037391.       6.84e14
4 W      662296. 396185950266.    41   422 279488706.       1.55e15</code></pre>
</div>
</div>
<ol start="5" type="1">
<li>Calculate the overall total <span class="math inline">\(\hat{\tau}_{str}\)</span> and variance <span class="math inline">\(\hat{V}\big(\hat{\tau}_{str}\big)\)</span> by summing these values across the strata.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>(tau.hat.str <span class="ot">&lt;-</span> <span class="fu">sum</span>(strata.summary.stats<span class="sc">$</span>tau.hat.h))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 909736035</code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>(V.tau.hat.str <span class="ot">&lt;-</span> <span class="fu">sum</span>(strata.summary.stats<span class="sc">$</span>var.tau.hat.h))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.541899e+15</code></pre>
</div>
</div>
<p>The estimated total number of acres devoted to farming is 909,736,035, with standard error 50,417,248. These numbers match those found in Table 3.2.</p>
<div class="callout callout-style-default callout-warning no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="emoji" data-emoji="star">⭐</span> You try it
</div>
</div>
<div class="callout-body-container callout-body">
<p>Siniff and Skoog (1964) used stratified random sampling to estimate the size of a herd of Alaskan caribou in 1992. Using prior known caribou density estimates for the region, the researches divided the area into 6 strata, then within each strata they formed a grid where each cell was 4 sq miles. They then randomly sampled the grids within each strata. The summary information from each strata is contained in the table below.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Stratum</th>
<th style="text-align: right;">N.h</th>
<th style="text-align: right;">n.h</th>
<th style="text-align: right;">y.bar.h</th>
<th style="text-align: right;">s2.h</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">A</td>
<td style="text-align: right;">400</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">24.1</td>
<td style="text-align: right;">5575</td>
</tr>
<tr class="even">
<td style="text-align: left;">B</td>
<td style="text-align: right;">30</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">25.6</td>
<td style="text-align: right;">4064</td>
</tr>
<tr class="odd">
<td style="text-align: left;">C</td>
<td style="text-align: right;">61</td>
<td style="text-align: right;">37</td>
<td style="text-align: right;">267.6</td>
<td style="text-align: right;">347556</td>
</tr>
<tr class="even">
<td style="text-align: left;">D</td>
<td style="text-align: right;">18</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">179.0</td>
<td style="text-align: right;">22798</td>
</tr>
<tr class="odd">
<td style="text-align: left;">E</td>
<td style="text-align: right;">70</td>
<td style="text-align: right;">39</td>
<td style="text-align: right;">293.7</td>
<td style="text-align: right;">123578</td>
</tr>
<tr class="even">
<td style="text-align: left;">F</td>
<td style="text-align: right;">120</td>
<td style="text-align: right;">21</td>
<td style="text-align: right;">33.2</td>
<td style="text-align: right;">9795</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Use this information and the equations from this chapter to calculate the estimated total number of caribou in this region in Alaska with a 95% CI.</p>
</div>
</div>
<div class="callout callout-style-simple callout-warning no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create data frame</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>caribou <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">Stratum =</span> <span class="fu">c</span>(<span class="st">"A"</span>, <span class="st">"B"</span>, <span class="st">"C"</span>, <span class="st">"D"</span>, <span class="st">"E"</span>, <span class="st">"F"</span>), </span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">N.h =</span> <span class="fu">c</span>(<span class="dv">400</span>, <span class="dv">30</span>, <span class="dv">61</span>, <span class="dv">18</span>, <span class="dv">70</span>, <span class="dv">120</span>), </span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">n.h =</span> <span class="fu">c</span>(<span class="dv">98</span>, <span class="dv">10</span>, <span class="dv">37</span>, <span class="dv">6</span>, <span class="dv">39</span>, <span class="dv">21</span>), </span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">y.bar.h =</span> <span class="fu">c</span>(<span class="fl">24.1</span>, <span class="fl">25.6</span>, <span class="fl">267.6</span>, <span class="dv">179</span>, <span class="fl">293.7</span>, <span class="fl">33.2</span>), </span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">s2.h =</span> <span class="fu">c</span>(<span class="dv">5575</span>, <span class="dv">4064</span>, <span class="dv">347556</span>, <span class="dv">22798</span>, <span class="dv">123578</span>, <span class="dv">9795</span>))</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a><span class="co"># within strata total</span></span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>caribou<span class="sc">$</span>tau.hat.h <span class="ot">&lt;-</span> caribou<span class="sc">$</span>y.bar.h <span class="sc">*</span>caribou<span class="sc">$</span>N.h</span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a><span class="co"># within strata variance</span></span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a>caribou <span class="ot">&lt;-</span> caribou <span class="sc">%&gt;%</span></span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">var.tau.hat.h =</span> (<span class="dv">1</span> <span class="sc">-</span> n.h<span class="sc">/</span>N.h)<span class="sc">*</span>(N.h<span class="sc">^</span><span class="dv">2</span>)<span class="sc">*</span>(s2.h<span class="sc">/</span>n.h)</span>
<span id="cb25-15"><a href="#cb25-15" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb25-16"><a href="#cb25-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-17"><a href="#cb25-17" aria-hidden="true" tabindex="-1"></a><span class="co"># overall total and variance of the total</span></span>
<span id="cb25-18"><a href="#cb25-18" aria-hidden="true" tabindex="-1"></a>(tau.hat.str <span class="ot">&lt;-</span> <span class="fu">sum</span>(caribou<span class="sc">$</span>tau.hat.h))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 54496.6</code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>V.tau.hat.str <span class="ot">&lt;-</span> <span class="fu">sum</span>(caribou<span class="sc">$</span>var.tau.hat.h)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="co"># calculating at CI using a t_{n-H} distribution</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>n.caribou <span class="ot">&lt;-</span> <span class="fu">sum</span>(caribou<span class="sc">$</span>n.h)</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>n.strata <span class="ot">&lt;-</span> <span class="fu">length</span>(caribou<span class="sc">$</span>Stratum)</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> n.caribou <span class="sc">-</span> n.strata</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>(crit.value <span class="ot">&lt;-</span> <span class="fu">qt</span>(.<span class="dv">975</span>, df))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.971603</code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>s.error <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(var.tau.hat.str)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-error">
<pre><code>Error in eval(expr, envir, enclos): object 'var.tau.hat.str' not found</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>(tau.hat.str <span class="sc">-</span> crit.value<span class="sc">*</span>s.error)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-error">
<pre><code>Error in eval(expr, envir, enclos): object 's.error' not found</code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>(tau.hat.str <span class="sc">+</span> crit.value<span class="sc">*</span>s.error)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-error">
<pre><code>Error in eval(expr, envir, enclos): object 's.error' not found</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
missing
</div>
</div>
<div class="callout-body-container callout-body">
<p>CI and interpretation of CI</p>
</div>
</div>
<p>This CI only explains uncertainty due to sampling error, if researchers tend to miss animals, this CI will be low.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-warning no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="emoji" data-emoji="star">⭐</span> You try it
</div>
</div>
<div class="callout-body-container callout-body">
<p>The ACLS intends to use a stratified random sample to study publications and library use among members. They divide their data into discipline, making 7 stratas.</p>
<p>Use the summary table below to estimate the the percentage and number of respondents that are female in those seven disciplines.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: center;">Membership</th>
<th style="text-align: center;">Valid.Returns</th>
<th style="text-align: center;">Female.members</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">9100</td>
<td style="text-align: center;">636</td>
<td style="text-align: center;">0.38</td>
</tr>
<tr class="even">
<td style="text-align: center;">1950</td>
<td style="text-align: center;">451</td>
<td style="text-align: center;">0.27</td>
</tr>
<tr class="odd">
<td style="text-align: center;">5500</td>
<td style="text-align: center;">481</td>
<td style="text-align: center;">0.18</td>
</tr>
<tr class="even">
<td style="text-align: center;">10850</td>
<td style="text-align: center;">611</td>
<td style="text-align: center;">0.19</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2100</td>
<td style="text-align: center;">493</td>
<td style="text-align: center;">0.36</td>
</tr>
<tr class="even">
<td style="text-align: center;">5500</td>
<td style="text-align: center;">575</td>
<td style="text-align: center;">0.13</td>
</tr>
<tr class="odd">
<td style="text-align: center;">9000</td>
<td style="text-align: center;">588</td>
<td style="text-align: center;">0.26</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-warning no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-12-contents" aria-controls="callout-12" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-12" class="callout-12-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>First extract the table information into vectors.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>Nh <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">9100</span>,<span class="dv">1950</span>,<span class="dv">5500</span>,<span class="dv">10850</span>,<span class="dv">2100</span>,<span class="dv">5500</span>,<span class="dv">9000</span>)</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>nh <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">636</span>,<span class="dv">451</span>,<span class="dv">481</span>,<span class="dv">611</span>,<span class="dv">493</span>,<span class="dv">575</span>,<span class="dv">588</span>)</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>ph <span class="ot">&lt;-</span> <span class="fu">c</span>(.<span class="dv">38</span>,.<span class="dv">27</span>,.<span class="dv">18</span>,.<span class="dv">19</span>,.<span class="dv">36</span>,.<span class="dv">13</span>,.<span class="dv">26</span>)</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="fu">sum</span>(Nh)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Then the overall estimated proportion of female members in the societies is calculated as</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>(<span class="at">p.str =</span> <span class="fu">sum</span>((Nh<span class="sc">/</span>N)<span class="sc">*</span>ph))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2465227</code></pre>
</div>
</div>
<p>with variance</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>((<span class="dv">1</span><span class="sc">-</span>(nh<span class="sc">/</span>Nh))<span class="sc">*</span>((Nh<span class="sc">/</span>N)<span class="sc">^</span><span class="dv">2</span>)<span class="sc">*</span>((ph<span class="sc">*</span>(<span class="dv">1</span><span class="sc">-</span>ph))<span class="sc">/</span>(nh<span class="dv">-1</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5.067478e-05</code></pre>
</div>
</div>
<p>The total number of female members in this society is calculated as</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>N<span class="sc">*</span>p.str</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 10847</code></pre>
</div>
</div>
<p>There are an estimated 10,847 female members.</p>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-13-contents" aria-controls="callout-13" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Clean up
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-13" class="callout-13-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list=</span><span class="fu">ls</span>()[<span class="sc">!</span><span class="fu">ls</span>() <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"agpop"</span>, <span class="st">"agstrat"</span>,<span class="st">"caribou"</span>)])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
</section>
</section>
<section id="sampling-weights" class="level1">
<h1>Sampling Weights</h1>
<section id="how-are-weights-calculated" class="level2">
<h2 class="anchored" data-anchor-id="how-are-weights-calculated">How are weights calculated?</h2>
<p>Sampling weights in the context of Stratified Sampling function almost identically as they did in SRS.</p>
<p>For any unit <span class="math inline">\(j\)</span> in a stratum <span class="math inline">\(h\)</span>, a sampling weight(<span class="math inline">\(w_{hj}\)</span>) is still the inverse of an inclusion probability(<span class="math inline">\(\pi_{hj}\)</span>). However, because the population of a stratum, <span class="math inline">\(N_h\)</span>, and the size of a sample of a stratum, <span class="math inline">\(n_h\)</span>, don’t have to be constant within a population of <span class="math inline">\(H\)</span> strata, each stratum will have different sampling weights.</p>
<p><span class="math inline">\(w_{hj}= \frac{1}{\pi_{hj}}=\frac{N_h}{n_h}\)</span></p>
</section>
<section id="how-are-weights-used" class="level2">
<h2 class="anchored" data-anchor-id="how-are-weights-used">How are weights used?</h2>
<p>The weights are directly applied to the values of <span class="math inline">\(y\)</span> before being used in any calculations.</p>
<p><span class="math display">\[\hat{t}_{str}= \sum_{h=1}^H\sum_{j\in S_h} w_{hj}y_{hj}\]</span></p>
<p>is the estimator of the total population using a stratified sample, and</p>
<p><span class="math display">\[\bar{y}_{str}= \frac{\hat{t}_{str}}{\sum_{h=1}^H\sum_{j\in S_h} w_{hj}}=
\frac{\sum_{h=1}^H\sum_{j\in S_h} w_{hj}y_{hj}}{\sum_{h=1}^H\sum_{j\in S_h} w_{hj}}\]</span></p>
<p>is the estimate for a population mean using stratified sampling.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Example: Re-Estimate the total number of farm acres in 1992 using sample weights
</div>
</div>
<div class="callout-body-container callout-body">
<p>Note, this agriculture example was designed so that each county in the US had approximately the same probability of appearing in the sample.</p>
</div>
</div>
<ol type="1">
<li>Calculate stratum weights. Sometimes this is given to you, othertimes you have to calculate it.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>strat.weights <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">region =</span> <span class="fu">table</span>(agpop<span class="sc">$</span>region) <span class="sc">%&gt;%</span> <span class="fu">names</span>(),</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">N.h =</span> <span class="fu">table</span>(agpop<span class="sc">$</span>region) <span class="sc">%&gt;%</span> <span class="fu">as.vector</span>(), </span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">n.h =</span> <span class="fu">table</span>(agstrat<span class="sc">$</span>region) <span class="sc">%&gt;%</span> <span class="fu">as.vector</span>()</span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>strat.weights<span class="sc">$</span>wt <span class="ot">&lt;-</span> strat.weights<span class="sc">$</span>N.h <span class="sc">/</span> strat.weights<span class="sc">$</span>n.h</span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>strat.weights</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  region  N.h n.h       wt
1     NC 1054 103 10.23301
2     NE  220  21 10.47619
3      S 1382 135 10.23704
4      W  422  41 10.29268</code></pre>
</div>
</div>
<ol start="2" type="1">
<li>Merge those weights back onto the sample data, joining by region.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>agstrat <span class="ot">&lt;-</span> agstrat <span class="sc">%&gt;%</span> <span class="fu">left_join</span>(strat.weights)</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(agstrat<span class="sc">$</span>wt)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
10.2330097087379  10.237037037037 10.2926829268293 10.4761904761905 
             103              135               41               21 </code></pre>
</div>
</div>
<p>This last table is used to confirm that the number of weighting values equals the strata sample sizes.</p>
<ol start="3" type="1">
<li>Calculate the weighted values <span class="math inline">\(w_{hj}y_{hj}\)</span>. The weights need to be applied to the individual data points, <span class="math inline">\(y_{jh}\)</span>, then all the above calculations can occur again.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>agstrat<span class="sc">$</span>wtd.acres92 <span class="ot">&lt;-</span> agstrat<span class="sc">$</span>acres92 <span class="sc">*</span> agstrat<span class="sc">$</span>wt </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol start="4" type="1">
<li>Calculate the weighted totals and variances within strata. Include the population and sample sizes within each strata in the <code>group_by</code> statement so it can remain on the grouped dataset for later use.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>(wt.str.sum.stats <span class="ot">&lt;-</span> agstrat <span class="sc">%&gt;%</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>   <span class="fu">group_by</span>(region, N.h, n.h) <span class="sc">%&gt;%</span> </span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>   <span class="fu">summarize</span>(<span class="at">y.bar.h =</span> <span class="fu">sum</span>(wtd.acres92)<span class="sc">/</span>n.h,  </span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">s2.h    =</span> (<span class="dv">1</span><span class="sc">/</span>(n.h<span class="dv">-1</span>))<span class="sc">*</span><span class="fu">sum</span>((wtd.acres92<span class="sc">-</span>y.bar.h)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a>             ) <span class="sc">%&gt;%</span></span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a>   <span class="fu">unique</span>() <span class="co"># this removes duplicate rows created in the variance function</span></span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a> )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 5
# Groups:   region, N.h, n.h [4]
  region   N.h   n.h  y.bar.h    s2.h
  &lt;chr&gt;  &lt;int&gt; &lt;int&gt;    &lt;dbl&gt;   &lt;dbl&gt;
1 NC      1054   103 3075062. 3.10e12
2 NE       220    21 1022788. 8.39e11
3 S       1382   135 2163240. 5.62e12
4 W        422    41 6816798. 4.20e13</code></pre>
</div>
</div>
<ol start="5" type="1">
<li>Calculate within strata totals and variances <span class="math inline">\(\hat{\tau}_{h}\)</span> and <span class="math inline">\(\hat{V}(\hat{\tau}_{h})\)</span>.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>(wt.str.sum.stats <span class="ot">&lt;-</span> wt.str.sum.stats <span class="sc">%&gt;%</span> </span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">tau.hat.h =</span> y.bar.h <span class="sc">*</span> N.h , </span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">var.tau.hat.h =</span> (<span class="dv">1</span> <span class="sc">-</span> n.h<span class="sc">/</span>N.h)<span class="sc">*</span>(N.h<span class="sc">^</span><span class="dv">2</span>)<span class="sc">*</span>(s2.h<span class="sc">/</span>n.h)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 7
# Groups:   region, N.h, n.h [4]
  region   N.h   n.h  y.bar.h    s2.h   tau.hat.h var.tau.hat.h
  &lt;chr&gt;  &lt;int&gt; &lt;int&gt;    &lt;dbl&gt;   &lt;dbl&gt;       &lt;dbl&gt;         &lt;dbl&gt;
1 NC      1054   103 3075062. 3.10e12 3241115284.       3.02e16
2 NE       220    21 1022788. 8.39e11  225013466.       1.75e15
3 S       1382   135 2163240. 5.62e12 2989597592.       7.17e16
4 W        422    41 6816798. 4.20e13 2876688634.       1.65e17</code></pre>
</div>
</div>
<ol start="6" type="1">
<li>Calculate the overall total <span class="math inline">\(\hat{\tau}_{str}\)</span> and variance <span class="math inline">\(\hat{V}\big(\hat{\tau}_{str}\big)\)</span> by summing these values across the strata.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>(tau.hat.str <span class="ot">&lt;-</span> <span class="fu">sum</span>(wt.str.sum.stats<span class="sc">$</span>tau.hat.h))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 9332414976</code></pre>
</div>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>(V.tau.hat.str <span class="ot">&lt;-</span> <span class="fu">sum</span>(wt.str.sum.stats<span class="sc">$</span>var.tau.hat.h))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.682133e+17</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>Note. This value for <code>tau.hat.str</code> does not match what the book says. Not sure where the error is at.</p>
</blockquote>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="emoji" data-emoji="star">⭐</span> You try it Caribou weights
</div>
</div>
<div class="callout-body-container callout-body">
<p>In the caribou example, strata A had N=400 and n=98, so the sampling weight is 400/98 or 4.08.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>caribou<span class="sc">$</span>w.hj <span class="ot">&lt;-</span> caribou<span class="sc">$</span>N.h<span class="sc">/</span> caribou<span class="sc">$</span>n.h</span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>caribou <span class="sc">%&gt;%</span> <span class="fu">select</span>(Stratum<span class="sc">:</span>n.h, w.hj)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Stratum N.h n.h     w.hj
1       A 400  98 4.081633
2       B  30  10 3.000000
3       C  61  37 1.648649
4       D  18   6 3.000000
5       E  70  39 1.794872
6       F 120  21 5.714286</code></pre>
</div>
</div>
</div>
</div>
<p>Note: We cannot re-estimate the total number of caribou using the information provided because we are given the summary statistics <span class="math inline">\(\bar{Y}_h\)</span>, not the raw data <span class="math inline">\(y_{hj}\)</span>. To re-estimate the total number of caribou we would need to multiply the weights <span class="math inline">\(w_{h}\)</span> to <span class="math inline">\(y_{hj}\)</span>.</p>
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-16-contents" aria-controls="callout-16" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Clean up
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-16" class="callout-16-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list=</span><span class="fu">ls</span>()[<span class="sc">!</span><span class="fu">ls</span>() <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"agpop"</span>, <span class="st">"agstrat"</span>,<span class="st">"caribou"</span>)])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
<hr>
</section>
</section>
<section id="allocation-methods" class="level1">
<h1>Allocation Methods</h1>
<p>Designing the survey is the most important part of using a survey in research. If the survey is badly designed, then no amount of analysis will yield the needed information.</p>
<p>Simple random sample was easy - you just need to figure out the end sample size. For stratified sampling, we need to define the strata, and the sample size within each strata.</p>
<div class="callout callout-style-default callout-important no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Method 1: Proportional Allocation
</div>
</div>
<div class="callout-body-container callout-body">
<p>The number of sampling unit in a stratum is proportional to the population of each stratum.</p>
</div>
</div>
<ul>
<li>Probability selection (n/N) the same for each stratum (n being the number of sampling units in the stratum and N being the population of the stratum)</li>
<li>Weight of each sample will be the same</li>
<li>Stratified sampling estimate of the population mean is the average of all observations</li>
<li>Self-weighting: every unit in sample carries the same weight</li>
<li>When the strata are large enough, <span class="math inline">\(Var(\bar{y}_{str})\)</span> will almost always be less than the population variance of <span class="math inline">\(Var(\bar{y}_{srs})\)</span> of the same sample size</li>
<li>The more the means of the strata differ, the more precision you will gain from using proportional allocation.</li>
<li>When the variances are roughly the same across all strata, proportional allocation is likely your best bet for increasing precision</li>
</ul>
<div class="callout callout-style-default callout-important no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Method 2: Optimal Allocation
</div>
</div>
<div class="callout-body-container callout-body">
<p>Allocation of sampling units to strata so that the variance of the estimator is minimized for a given total cost.</p>
</div>
</div>
<ul>
<li>It is best to use when the sampling units are from corporations, cities, hospitals, or wherever the size varies largely. You want to get the most from the least cost.
<ul>
<li>E.g. If we wanted to estimate trade with Europe, the variance among large corporations would be larger than when compared to small corporations, so we’d sample more large corporations</li>
</ul></li>
<li>When the variances of the strata are significantly different, optimal allocation lowers the cost</li>
<li>When certain strata are more expensive to sample than others, optimal allocation may be useful</li>
<li>Generally, heavily sample from a stratum if:
<ul>
<li>Stratum is large</li>
<li>Variance of stratum is large</li>
<li>Its cheap</li>
</ul></li>
</ul>
<p>Optimization methods:</p>
<ul>
<li><em>Disproportional allocation</em>: Allocation of sampling units to strata so that the sampling fractions <span class="math inline">\(\frac{n_h}{N_h}\)</span> are unequal</li>
<li><em>Oversampling</em>: Selecting more observations in a stratum than would be called for in proportional allocation. An oversampled stratum has <span class="math inline">\(\frac{n_h}{N_h} \gt \frac{n}{N}\)</span></li>
<li><em>Neyman Allocation</em>: special case of optimal allocation where the costs in the strata are about equal, but the variances are not
<ul>
<li>If variances within strata are specified correctly, Neyman Allocation will give a smaller variance than proportional allocation</li>
</ul></li>
</ul>
<div class="callout callout-style-default callout-important no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Method 3: Allocation for Specified Precision within Strata
</div>
</div>
<div class="callout-body-container callout-body">
<p>Sometimes we are less interested in estimating the overall population values, and more interested in comparing the totals or means across stratum</p>
<p>In this case we would need to determine the sample size for each stratum that corresponds to a specific level of precision.</p>
</div>
</div>
<section id="which-allocation-to-use" class="level2">
<h2 class="anchored" data-anchor-id="which-allocation-to-use">Which allocation to use?</h2>
<p>Proportional Allocation</p>
<ul>
<li>should be used when you want your sample to be a mini version of the population.</li>
<li>the only knowledge about your data that is needed is N, making this a better option for some survey designs that might not have information about variances</li>
</ul>
<p>Disproportional Allocation:</p>
<ul>
<li>should be used when you want to oversample one or more of the strata</li>
<li>to guarantee precision in a certain strata</li>
</ul>
</section>
</section>
<section id="selecting-strata" class="level1">
<h1>Selecting Strata</h1>
<section id="defining-strata" class="level3">
<h3 class="anchored" data-anchor-id="defining-strata">Defining Strata</h3>
<ul>
<li>Stratified sampling with proportional allocation improves the precision for every variable y measured in the survey.</li>
<li>We want the means across strata to be as different as possible
<ul>
<li>We do this to minimize the variability within strata</li>
</ul></li>
<li>Most surveys measure more than one variable, so any stratification design should keep many characteristics of interest in mind.
<ul>
<li>If several stratification designs are applicable, use the design associated with the most important responses.</li>
</ul></li>
</ul>
</section>
<section id="how-many-strata" class="level3">
<h3 class="anchored" data-anchor-id="how-many-strata">How Many Strata?</h3>
<ul>
<li>The more information you have, the more strata you should use.</li>
<li>If there is a lot of prior information known about the target population, then an SRS may be more convenient.</li>
<li>Appropriate number of strata depends on a lot
<ul>
<li>The difficulty in constructing a sampling frame with stratifying information</li>
<li>Cost of Stratifying</li>
</ul></li>
<li>General rule: The less information, the fewer strata you should use.
<ul>
<li>Use an SRS when you know practically nothing about the target population.
<ul>
<li>However, you can usually collect preliminary data
<ul>
<li>The information used to construct strata does not need to be perfect because misclassification does not affect the validity of estimates from the survey because their properties depend only on the stratification that was used.</li>
</ul></li>
</ul></li>
</ul></li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Example: Estimating homeless population from NYC
</div>
</div>
<div class="callout-body-container callout-body">
<p>New York City takes an annual survey to estimate the homeless population and collect data on their characteristics. The survey is conducted on one of the first 10 nights in January; all data is collected in one night to reduce the chances of double counting.</p>
<p>The sampling plan needs to meet two criteria:</p>
<ol type="1">
<li>Provide an accurate estimate on the size of the unsheltered population (data on sheltered homeless is collected from the shelters, so population size is known)<br>
</li>
<li>Contact as many unsheltered homeless as possible.</li>
</ol>
</div>
</div>
<p>NYC decided to use a stratified random sample, to do this they:</p>
<ul>
<li>Partitioned the city into 7000 areas</li>
<li>Using previous years’ data and other available resources, classified each area as either “high density” or “low density”
<ul>
<li>High density is defined as an area expected to contain at least 1 homeless person, save for in Manhattan or the subway system, where we would expect to find at least two homeless people there</li>
<li>Low density is defined as not high density</li>
</ul></li>
</ul>
<p>This results in 12 strata: one high and one low density stratum for each of the 5 boroughs plus the subway system.</p>
<p>All areas in high density areas were canvassed, while they took a random sample of areas in low density strata</p>
<p>The results are statistically valid because a random sample of areas is sampled from each of the low density stratum</p>
<p>There is some measurement error due to 3 things:</p>
<ol type="1">
<li>Some homeless people are in dark places and are not seen</li>
<li>Some areas are deemed unsafe so no samples can be taken</li>
<li>Cannot always tell if an individual is homeless or not</li>
</ol>
<hr>
</section>
</section>
<section id="summary" class="level1">
<h1>Summary</h1>
<ul>
<li><p>This section setup the motivation for why using the stratified sampling method may be beneficial.</p></li>
<li><p>Once SRS’s are taken from each strata, the results can be pooled to make inferences about the entire population (the ultimate goal).</p></li>
<li><p>Don’t have to sample the same % from each strata</p></li>
<li><p>Could see a greater reduction in variance of the overall estimate with an increased sampling fraction from strata with high variance.</p></li>
<li><p>Stratification is an SRS of size n_h from each stratum h</p>
<ul>
<li>Relative pop size for each stratum: N_h/N</li>
<li>Probability for unit i in stratum h: n_h/N_h</li>
<li>Sampling weight: N_h/n_h</li>
<li>To estimate the population total using a stratified random sample, let <span class="math inline">\(\hat{tau_h}\)</span> estimate the population total in stratum <span class="math inline">\(h\)</span>.</li>
</ul></li>
</ul>
<p><strong>3 Design Issues When Stratifying</strong></p>
<ul>
<li>Strata Definitions</li>
<li>Total sample size</li>
<li>Proper Allocation Method</li>
</ul>
<p><strong>Allocation Methods</strong></p>
<ul>
<li>Proportional allocation focuses on reducing the variance of the final estimate.
<ul>
<li>The same sampling fraction is used in each stratum</li>
<li>Almost always results in smaller variances for estimated means and totals than SRS</li>
</ul></li>
<li>Disproportional allocation
<ul>
<li>May be preferred if some strata should have higher sampling fractions than others ex. If wanting to have larger sample sizes for strata with minority populations or for strata with large companies</li>
</ul></li>
<li>Optimal Allocation
<ul>
<li>Specifies taking larger sampling fractions in strata that have larger variances or lower sampling costs</li>
</ul></li>
</ul>
<hr>
</section>
<section id="using-r" class="level1">
<h1>Using R</h1>
<section id="selecting-a-stratified-random-sample" class="level2">
<h2 class="anchored" data-anchor-id="selecting-a-stratified-random-sample">Selecting a Stratified Random Sample</h2>
<section id="using-the-strata-function-from-the-sampling-package" class="level3">
<h3 class="anchored" data-anchor-id="using-the-strata-function-from-the-sampling-package">Using the <code>strata</code> function from the <code>sampling</code> package</h3>
<ol type="1">
<li>Sort the data by the stratification variable</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>agpop.sorted <span class="ot">&lt;-</span> agpop <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(region)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol start="2" type="1">
<li>Specify the desired within-strata sample sizes <span class="math inline">\(n_{k}\)</span>.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>n.k <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">103</span>, <span class="dv">21</span>, <span class="dv">135</span>, <span class="dv">41</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol start="3" type="1">
<li>Create the sampling index of records to select using the <code>strata</code> function with arguments specifying the strata names, strata size, and sampling method within strata.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>strat.idx <span class="ot">&lt;-</span> sampling<span class="sc">::</span><span class="fu">strata</span>(<span class="at">data =</span> agpop.sorted, <span class="at">stratanames =</span> <span class="st">"region"</span>, </span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>                    <span class="at">size =</span> n.k, <span class="at">method =</span> <span class="st">"srswor"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><span class="emoji" data-emoji="warning">⚠️</span> Package conflicts can occur with the <code>strata</code> function. If it is not working for you, use the <code>sampling::strata</code> method of calling the function to ensure you are using the correct version of the <code>strata</code> function from the <code>sampling</code> package.</p>
<ol start="4" type="1">
<li>Extract the data records that correspond to the sampling index.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>ag.str <span class="ot">&lt;-</span> <span class="fu">getdata</span>(agpop.sorted, strat.idx)</span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(ag.str)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           county state acres92 acres87 acres82 farms92 farms87 farms82
15    CASS COUNTY    IA  347353  333083  345726     905     942    1087
36 FREMONT COUNTY    IA  302352  308796  306786     596     719     771
37  GREENE COUNTY    IA  366927  353283  359023     851     948    1054
44   HENRY COUNTY    IA  225835  231617  239403     795     893     963
45  HOWARD COUNTY    IA  260781  269285  278861     881     938    1055
48    IOWA COUNTY    IA  321285  329705  361465     977    1057    1150
   largef92 largef87 largef82 smallf92 smallf87 smallf82 region ID_unit
15       70       52       38       55       66       72     NC      15
36       91       72       51       37       59       50     NC      36
37       78       52       38       51       81       89     NC      37
44       31       20       18       57       69       63     NC      44
45       40       33       30       68       64       70     NC      45
48       43       32       36       58       64       62     NC      48
         Prob Stratum
15 0.09772296       1
36 0.09772296       1
37 0.09772296       1
44 0.09772296       1
45 0.09772296       1
48 0.09772296       1</code></pre>
</div>
</div>
<ol start="5" type="1">
<li>Calculate the sampling weights using the inclusion probabilities (these were created as the variable <code>Prob</code> when you used the <code>strata</code> function)</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>ag.str<span class="sc">$</span>wt <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">/</span>ag.str<span class="sc">$</span>Prob</span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(ag.str)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           county state acres92 acres87 acres82 farms92 farms87 farms82
15    CASS COUNTY    IA  347353  333083  345726     905     942    1087
36 FREMONT COUNTY    IA  302352  308796  306786     596     719     771
37  GREENE COUNTY    IA  366927  353283  359023     851     948    1054
44   HENRY COUNTY    IA  225835  231617  239403     795     893     963
45  HOWARD COUNTY    IA  260781  269285  278861     881     938    1055
48    IOWA COUNTY    IA  321285  329705  361465     977    1057    1150
   largef92 largef87 largef82 smallf92 smallf87 smallf82 region ID_unit
15       70       52       38       55       66       72     NC      15
36       91       72       51       37       59       50     NC      36
37       78       52       38       51       81       89     NC      37
44       31       20       18       57       69       63     NC      44
45       40       33       30       68       64       70     NC      45
48       43       32       36       58       64       62     NC      48
         Prob Stratum       wt
15 0.09772296       1 10.23301
36 0.09772296       1 10.23301
37 0.09772296       1 10.23301
44 0.09772296       1 10.23301
45 0.09772296       1 10.23301
48 0.09772296       1 10.23301</code></pre>
</div>
</div>
<p>5b. Check that the sampling weights sum to the stratum population sizes.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>ag.str <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(region) <span class="sc">%&gt;%</span> <span class="fu">summarize</span>(<span class="at">sum.wts =</span> <span class="fu">sum</span>(wt))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 2
  region sum.wts
  &lt;chr&gt;    &lt;dbl&gt;
1 NC        1054
2 NE         220
3 S         1382
4 W          422</code></pre>
</div>
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(agpop.sorted<span class="sc">$</span>region)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  NC   NE    S    W 
1054  220 1382  422 </code></pre>
</div>
</div>
<div class="callout callout-style-default callout-important no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body">
<p>If the weights do not sum to the stratum population sizes, you have made a mistake somewhere in the calculations for the weights or strata sizes.</p>
</div>
</div>
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-22-contents" aria-controls="callout-22" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Clean up
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-22" class="callout-22-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list=</span><span class="fu">ls</span>()[<span class="sc">!</span><span class="fu">ls</span>() <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"agpop"</span>, <span class="st">"agstrat"</span>,<span class="st">"caribou"</span>, <span class="st">"agpop.sorted"</span>, <span class="st">"N.k"</span>, <span class="st">"n.k"</span>, <span class="st">"ag.str"</span>)])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
<hr>
</section>
</section>
<section id="computing-statistics-from-a-stratified-random-sample" class="level2">
<h2 class="anchored" data-anchor-id="computing-statistics-from-a-stratified-random-sample">Computing Statistics from a Stratified Random Sample</h2>
<section id="setup-the-information-for-the-survey-design." class="level3">
<h3 class="anchored" data-anchor-id="setup-the-information-for-the-survey-design.">1. Setup the information for the survey design.</h3>
<section id="a.-specify-weights" class="level4">
<h4 class="anchored" data-anchor-id="a.-specify-weights">a. Specify weights</h4>
<p>We created the weights in the dataset in the the last step.</p>
</section>
<section id="b.-specify-fpc" class="level4">
<h4 class="anchored" data-anchor-id="b.-specify-fpc">b. Specify fpc</h4>
<p>We need to create a vector of fpc’s that are equal to the strata population size. In a SRS, we used <code>fpc = rep(N,n)</code>. This create a vector that contains the value <code>N</code>, repeated <code>n</code> times. In this case, we need to match the strata population size to each record from that strata.</p>
<p>Option 1: Create a vector that repeats the values in the vector <code>N.k</code>, each <code>n.k</code> times.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>option1.fpc <span class="ot">&lt;-</span> <span class="fu">rep</span>(N.k, n.k)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout callout-style-simple callout-tip no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>Example on how to use the <code>rep</code> function</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>ex.N.k <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">10</span>,<span class="dv">25</span>,<span class="dv">50</span>) <span class="co"># example population sizes</span></span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a>ex.n.k <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">5</span>,<span class="dv">10</span>)   <span class="co"># example strata sizes</span></span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a><span class="fu">rep</span>(ex.N.k, ex.n.k)   </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 10 10 25 25 25 25 25 50 50 50 50 50 50 50 50 50 50</code></pre>
</div>
</div>
<p>The pop size for stratum 1 is repeated twice (the size of the sample from that stratum), the pop size for stratum 2 is repeated 5 times (the sample size for stat stratum) etc.</p>
</div>
</div>
</div>
<p>Option 2: Merge the pop sizes onto the sample data using <code>region</code> as a joining key</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a>(pop.strata.sizes <span class="ot">&lt;-</span> <span class="fu">table</span>(agpop.sorted<span class="sc">$</span>region) <span class="sc">%&gt;%</span> <span class="fu">data.frame</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Var1 Freq
1   NC 1054
2   NE  220
3    S 1382
4    W  422</code></pre>
</div>
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a>pop.strata.sizes <span class="ot">&lt;-</span> <span class="fu">rename</span>(pop.strata.sizes, <span class="at">region =</span> Var1, <span class="at">popsize =</span> Freq)</span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a>ag.str.opt2 <span class="ot">&lt;-</span> ag.str <span class="sc">%&gt;%</span> <span class="fu">left_join</span>(pop.strata.sizes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="call-svydesign" class="level3">
<h3 class="anchored" data-anchor-id="call-svydesign">2. Call <code>svydesign</code></h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a>agpop.str.dsgn <span class="ot">&lt;-</span> <span class="fu">svydesign</span>(<span class="at">id =</span> <span class="sc">~</span><span class="dv">1</span>, <span class="at">strata =</span> <span class="sc">~</span>region, <span class="at">weights =</span> <span class="sc">~</span>wt, </span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a>                            <span class="at">fpc =</span> <span class="sc">~</span>popsize, </span>
<span id="cb77-3"><a href="#cb77-3" aria-hidden="true" tabindex="-1"></a>                            <span class="co"># fpc = option1.fpc # This would be Option 1</span></span>
<span id="cb77-4"><a href="#cb77-4" aria-hidden="true" tabindex="-1"></a>                            <span class="at">data=</span> ag.str.opt2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="calculate-total-se-and-ci" class="level3">
<h3 class="anchored" data-anchor-id="calculate-total-se-and-ci">3. Calculate total, SE and CI</h3>
<p>Note the degrees of freedom for a CI under a stratified sample is <span class="math inline">\(n-H\)</span>, which can be extracted from the <code>svydesign</code> object using the <code>degf</code> function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a>(str.total <span class="ot">&lt;-</span> <span class="fu">svytotal</span>(<span class="sc">~</span>acres92, agpop.str.dsgn))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            total       SE
acres92 958967357 56164159</code></pre>
</div>
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(str.total, <span class="at">level =</span> .<span class="dv">95</span>, <span class="at">df =</span> <span class="fu">degf</span>(agpop.str.dsgn))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            2.5 %     97.5 %
acres92 848435688 1069499025</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Example: Farmland in 1992
</div>
</div>
<div class="callout-body-container callout-body">
<p>The book’s provided <code>agstrat</code> data set is a stratified random sample with proportional allocation. The weights are contained in a variable called <code>strwt</code>. Let’s re-estimate the total amount of farmland using the sampling package.</p>
</div>
</div>
<ol type="1">
<li>Calculate the vector of population sizes for the fpc using Option 2 above.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a>agstrat <span class="ot">&lt;-</span> agstrat <span class="sc">%&gt;%</span> <span class="fu">left_join</span>(pop.strata.sizes)</span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(agstrat<span class="sc">$</span>popsize) <span class="co"># confirm</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 220  422 1054 1382 
  21   41  103  135 </code></pre>
</div>
</div>
<ol start="2" type="1">
<li>Define the survey design</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a>agstrat.dsgn <span class="ot">&lt;-</span> <span class="fu">svydesign</span>(<span class="at">id =</span> <span class="sc">~</span><span class="dv">1</span>, <span class="at">strata =</span> <span class="sc">~</span>region, </span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a>                          <span class="at">weights =</span> <span class="sc">~</span>strwt, </span>
<span id="cb84-3"><a href="#cb84-3" aria-hidden="true" tabindex="-1"></a>                          <span class="at">fpc =</span> <span class="sc">~</span>popsize, </span>
<span id="cb84-4"><a href="#cb84-4" aria-hidden="true" tabindex="-1"></a>                          <span class="at">data=</span> agstrat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol start="3" type="1">
<li>calculate the stratified total with CI.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a>(str.total <span class="ot">&lt;-</span> <span class="fu">svytotal</span>(<span class="sc">~</span>acres92, agstrat.dsgn))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            total       SE
acres92 909736036 50417248</code></pre>
</div>
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(str.total, <span class="at">level =</span> .<span class="dv">95</span>, <span class="at">df =</span> <span class="fu">degf</span>(agstrat.dsgn))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            2.5 %     97.5 %
acres92 810514350 1008957721</code></pre>
</div>
</div>
</section>
<section id="calculating-stratum-means-and-variances" class="level3">
<h3 class="anchored" data-anchor-id="calculating-stratum-means-and-variances">Calculating stratum means and variances</h3>
<p>Instead of using the formulas as shown in Ch 3.3, we can use the <code>svyby</code> function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a>regional.totals <span class="ot">&lt;-</span> <span class="fu">svyby</span>(<span class="sc">~</span>acres92, <span class="at">by=</span><span class="sc">~</span>region, agstrat.dsgn, </span>
<span id="cb89-2"><a href="#cb89-2" aria-hidden="true" tabindex="-1"></a>                         svytotal, <span class="at">keep.var =</span> <span class="cn">TRUE</span>)</span>
<span id="cb89-3"><a href="#cb89-3" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(regional.totals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">region</th>
<th style="text-align: right;">acres92</th>
<th style="text-align: right;">se</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">NC</td>
<td style="text-align: left;">NC</td>
<td style="text-align: right;">316731380</td>
<td style="text-align: right;">16977399</td>
</tr>
<tr class="even">
<td style="text-align: left;">NE</td>
<td style="text-align: left;">NE</td>
<td style="text-align: right;">21478558</td>
<td style="text-align: right;">3992889</td>
</tr>
<tr class="odd">
<td style="text-align: left;">S</td>
<td style="text-align: left;">S</td>
<td style="text-align: right;">292037392</td>
<td style="text-align: right;">26154840</td>
</tr>
<tr class="even">
<td style="text-align: left;">W</td>
<td style="text-align: left;">W</td>
<td style="text-align: right;">279488706</td>
<td style="text-align: right;">39416342</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Confirm the overall total <span class="math inline">\(\hat{\tau}_{str}\)</span> by summing these values across the strata.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(regional.totals<span class="sc">$</span>acres92)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 909736036</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-warning no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="emoji" data-emoji="star">⭐</span> Estimating vehicle information for the entire USA.
</div>
</div>
<div class="callout-body-container callout-body">
<p>The Vehicle Inventory and Use Survey (VIUS) used is the result of a a stratified random sampling design that collects information on the number of private and commercial trucks in each state.</p>
<p>In the 2002 survey, 255 strata (51 * 5) were created from truck registrations among the 51 states and 5 truck types. Within each state (+DC),the truck registrations were partitioned into one of five classes:</p>
<ol type="1">
<li>Pickups</li>
<li>Minivans, other light vans, and sport utility vehicles</li>
<li>Light single-unit trucks with gross vehicle weight less than 26,000 pounds</li>
<li>Heavy single-unit trucks with gross vehicle weight greater than or equal to 26,000 pounds</li>
<li>Truck-tractors</li>
</ol>
<p>Use the <code>vius.csv</code> data to answer the following questions. The stratification variable is named <code>stratum</code> and the weights are contained in the variable <code>tabtrucks</code>.</p>
<ol type="a">
<li>Estimate the total number of trucks in the US</li>
<li>Estimate the total number of truck miles driven in 2002 (variable <code>miles_annl</code>)</li>
<li>Estimate the total number of truck miles driven in 2002 for each of the five trucktypes classes.</li>
<li>Estimate the total number of vehicles that have gross vehicle weight exceeding 10,000 lbs (variable <code>vius_gvw</code>)</li>
</ol>
</div>
</div>
<div class="callout callout-style-simple callout-warning no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-25-contents" aria-controls="callout-25" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-25" class="callout-25-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a>vius <span class="ot">&lt;-</span> readr<span class="sc">::</span><span class="fu">read_csv</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"data"</span>, <span class="st">"vius.csv"</span>))</span>
<span id="cb92-2"><a href="#cb92-2" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(vius<span class="sc">$</span>trucktype)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    1     2     3     4     5 
11654 11966 26424 27239 21399 </code></pre>
</div>
</div>
<p>Set the survey design.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a>vius.dsgn <span class="ot">&lt;-</span> <span class="fu">svydesign</span>(<span class="at">id =</span> <span class="sc">~</span><span class="dv">1</span>, </span>
<span id="cb94-2"><a href="#cb94-2" aria-hidden="true" tabindex="-1"></a>              <span class="at">strata =</span> <span class="sc">~</span>stratum, </span>
<span id="cb94-3"><a href="#cb94-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">weights =</span> <span class="sc">~</span>tabtrucks,</span>
<span id="cb94-4"><a href="#cb94-4" aria-hidden="true" tabindex="-1"></a>              <span class="at">data =</span> vius)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">This site is built with <span class="emoji" data-emoji="heart">❤️</span>, and <a href="https://quarto.org/">Quarto</a> by <a href="www.norcalbiostat.com">Robin Donatello</a>.</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>



</body></html>