<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.319">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="458 class">
<meta name="dcterms.date" content="2023-03-20">
<meta name="description" content="Selecting groups at . Lohr Ch 5.">

<title>Sampling Methods - Cluster Sampling</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Sampling Methods</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../weekly_details.html" rel="" target="">
 <span class="menu-text">Weekly Overview</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../notes.html" rel="" target="">
 <span class="menu-text">Notes</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../assignments.html" rel="" target="">
 <span class="menu-text">Assignments</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-hackmd" role="button" data-bs-toggle="dropdown" aria-expanded="false" rel="" target="">
 <span class="menu-text">HackMD</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-hackmd">    
        <li>
    <a class="dropdown-item" href="https://hackmd.io/@norcalbiostat/sampling_r_resources" rel="" target="">
 <span class="dropdown-text">R resources</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://hackmd.io/@norcalbiostat/458_intro_hackmd" rel="" target="">
 <span class="dropdown-text">What is HackMD</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://hackmd.io/@norcalbiostat/cn02-intro_sampling" rel="" target="">
 <span class="dropdown-text">Sampling Framework notes</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://hackmd.io/@norcalbiostat/cn03-statistical_foundations" rel="" target="">
 <span class="dropdown-text">Foundations of Estimation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://hackmd.io/@norcalbiostat/cn06_stratified" rel="" target="">
 <span class="dropdown-text">Stratified Sampling</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://hackmd.io/@norcalbiostat/cn07_cluster" rel="" target="">
 <span class="dropdown-text">Cluster Sampling</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://hackmd.io/@norcalbiostat/cn08_ratio" rel="" target="">
 <span class="dropdown-text">Ratio &amp; Regression Estimation</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../syllabus.html" rel="" target="">
 <span class="menu-text">Syllabus</span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#notation-formulas" id="toc-notation-formulas" class="nav-link" data-scroll-target="#notation-formulas">Notation &amp; Formulas</a>
  <ul class="collapse">
  <li><a href="#why-use-cluster-sampling" id="toc-why-use-cluster-sampling" class="nav-link" data-scroll-target="#why-use-cluster-sampling">Why use Cluster Sampling?</a></li>
  <li><a href="#when-clusters-are-ignored" id="toc-when-clusters-are-ignored" class="nav-link" data-scroll-target="#when-clusters-are-ignored">When clusters are Ignored</a>
  <ul class="collapse">
  <li><a href="#studies-in-education" id="toc-studies-in-education" class="nav-link" data-scroll-target="#studies-in-education">Studies in education</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#one-stage-clustering-sampling" id="toc-one-stage-clustering-sampling" class="nav-link" data-scroll-target="#one-stage-clustering-sampling">One-Stage Clustering Sampling</a>
  <ul class="collapse">
  <li><a href="#equal-size-clusters" id="toc-equal-size-clusters" class="nav-link" data-scroll-target="#equal-size-clusters">Equal size clusters</a></li>
  </ul></li>
  <li><a href="#two-stage-clustering-sampling" id="toc-two-stage-clustering-sampling" class="nav-link" data-scroll-target="#two-stage-clustering-sampling">Two-Stage Clustering Sampling</a>
  <ul class="collapse">
  <li><a href="#survey-weights" id="toc-survey-weights" class="nav-link" data-scroll-target="#survey-weights">Survey weights</a></li>
  <li><a href="#summary-of-one-vs-two-stage-clustering" id="toc-summary-of-one-vs-two-stage-clustering" class="nav-link" data-scroll-target="#summary-of-one-vs-two-stage-clustering">Summary of One vs Two Stage Clustering</a></li>
  </ul></li>
  <li><a href="#systematic-sampling" id="toc-systematic-sampling" class="nav-link" data-scroll-target="#systematic-sampling">Systematic Sampling</a>
  <ul class="collapse">
  <li><a href="#method" id="toc-method" class="nav-link" data-scroll-target="#method">Method</a></li>
  <li><a href="#attributes-to-note" id="toc-attributes-to-note" class="nav-link" data-scroll-target="#attributes-to-note">Attributes to Note</a></li>
  <li><a href="#order-matters" id="toc-order-matters" class="nav-link" data-scroll-target="#order-matters">Order matters</a></li>
  </ul></li>
  <li><a href="#clusters-of-equal-sizes-theory" id="toc-clusters-of-equal-sizes-theory" class="nav-link" data-scroll-target="#clusters-of-equal-sizes-theory">Clusters of Equal Sizes (Theory)</a>
  <ul class="collapse">
  <li><a href="#msb-mean-squared-between-clusters" id="toc-msb-mean-squared-between-clusters" class="nav-link" data-scroll-target="#msb-mean-squared-between-clusters">MSB (Mean Squared Between Clusters)</a></li>
  <li><a href="#msw-mean-squared-within-clusters" id="toc-msw-mean-squared-within-clusters" class="nav-link" data-scroll-target="#msw-mean-squared-within-clusters">MSW (Mean Squared Within Clusters)</a></li>
  <li><a href="#icc-intraclass-correlation-coefficient" id="toc-icc-intraclass-correlation-coefficient" class="nav-link" data-scroll-target="#icc-intraclass-correlation-coefficient">ICC (Intraclass Correlation Coefficient)</a></li>
  <li><a href="#r-squared" id="toc-r-squared" class="nav-link" data-scroll-target="#r-squared">R Squared</a></li>
  </ul></li>
  <li><a href="#designing-a-cluster-sample" id="toc-designing-a-cluster-sample" class="nav-link" data-scroll-target="#designing-a-cluster-sample">Designing a Cluster Sample</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Cluster Sampling</h1>
</div>

<div>
  <div class="description">
    Selecting groups at . Lohr Ch 5.
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>458 class </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">March 20, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(here); <span class="fu">library</span>(tidyverse);<span class="fu">library</span>(knitr)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sampling); <span class="fu">library</span>(survey)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>Let’s say we want to find the number of bicycles owned within a community of 10,000 households. We have several options for picking a sample:</p>
<ul>
<li>Obtaining a SRS of 400 households</li>
<li>Stratifying households into groups then choosing a SRS from these groups</li>
<li>Separate the population into blocks of 500 and then randomly select 20 of these blocks and survey every household that is part of the blocks chosen</li>
</ul>
<p>This last option is an example of <strong>cluster sampling</strong>. In cluster sampling, we have <strong>primary sampling units</strong>(psus), or clusters, which are represented by the blocks. We also have <strong>secondary sampling units</strong>(ssus) which are the households within the blocks. In an SRS, the units sampled are the observed elements, but in a cluster sample, the sampling units are our clusters. In a cluster sample, our universe is the population <span class="math inline">\(N\)</span> clusters.</p>
<p>Cluster of 400 households vs SRS of 400 households?</p>
<ul>
<li>The cluster sample would result in less precision because of our blocks. Some might be composed of mainly families(who are more likely to have bikes) while others are mainly older people.</li>
<li>In this case, clusters won’t be as representative of the population as a SRS would.</li>
<li>Can be cheaper and faster than other sampling methods</li>
</ul>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figs/fig5_1.jpg" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Textbook Figure 5.1. Contrasting stratified sampling with one-stage cluster sampling.</figcaption><p></p>
</figure>
</div>
</section>
<section id="notation-formulas" class="level1">
<h1>Notation &amp; Formulas</h1>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true">Pop psu level</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false">Pop ssu level</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-3" role="tab" aria-controls="tabset-1-3" aria-selected="false">Sample</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<table class="table">
<colgroup>
<col style="width: 15%">
<col style="width: 33%">
<col style="width: 51%">
</colgroup>
<thead>
<tr class="header">
<th>Symbol</th>
<th>Formula</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(y_{ij}\)</span></td>
<td></td>
<td>measurement for the <span class="math inline">\(j\)</span>th element in <span class="math inline">\(i\)</span>th psu</td>
</tr>
<tr class="even">
<td><span class="math inline">\(N\)</span></td>
<td></td>
<td>number of clusters (psus) in the population</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(M_{i}\)</span></td>
<td></td>
<td>number of ssus in psu <span class="math inline">\(i\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(M_{0}\)</span></td>
<td><span class="math inline">\(\sum_{i=1}^{N} M_{i}\)</span></td>
<td>total number of ssus in the population</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(t_{i}\)</span></td>
<td><span class="math inline">\(\sum_{j=1}^{M_{i}} y_{ij}\)</span></td>
<td>total in psu <span class="math inline">\(i\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(t\)</span></td>
<td><span class="math inline">\(\sum_{i=1}^{N} t_{i}= \sum_{i=1}^{N} \sum_{j=1}^{M_{i}} y_{ij}\)</span></td>
<td>population total</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(S_{t}^{2}\)</span></td>
<td><span class="math inline">\(\frac{1}{N-1} \sum_{i=1}^{N} (t_{i} - \frac{t}{N})^2\)</span></td>
<td>population variance of the psu totals</td>
</tr>
</tbody>
</table>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<table class="table">
<colgroup>
<col style="width: 26%">
<col style="width: 47%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th>Symbol</th>
<th>Formula</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\bar{y}_{\mu}\)</span></td>
<td><span class="math inline">\(\frac{1}{M_0} \sum_{i=1}^N \sum_{j=1}^{M_i} y_{ij}\)</span></td>
<td>population mean</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\bar{y}_{i\mu}\)</span></td>
<td><span class="math inline">\(\frac{1}{M_i} \sum_{j=1}^{M_i} y_{ij} = \frac{t_i}{M_i}\)</span></td>
<td>population mean in psu <span class="math inline">\(i\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(S^2\)</span></td>
<td><span class="math inline">\(\frac{1}{M_0-1} \sum_{i=1}^N \sum_{j=1}^{M_i} (y_{ij}-\bar{y}_{\mu})^2\)</span></td>
<td>population variance (per ssu)</td>
</tr>
<tr class="even">
<td><span class="math inline">\(S_{i}^{2}\)</span></td>
<td><span class="math inline">\(\frac{1}{M_i-1} \sum_{j=1}^{M_i} (y_{ij}-\bar{y}_{\mu})^2\)</span></td>
<td>population variance within psu <span class="math inline">\(i\)</span></td>
</tr>
</tbody>
</table>
</div>
<div id="tabset-1-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-3-tab">
<table class="table">
<colgroup>
<col style="width: 23%">
<col style="width: 38%">
<col style="width: 38%">
</colgroup>
<thead>
<tr class="header">
<th>Symbol</th>
<th>Formula</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(y_{ij}\)</span></td>
<td></td>
<td>Measurement for<span class="math inline">\(j\)</span>th element in <span class="math inline">\(i\)</span>ht psu</td>
</tr>
<tr class="even">
<td><span class="math inline">\(N\)</span></td>
<td></td>
<td>Number of clusters (psus) in the population</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(M_i\)</span></td>
<td></td>
<td>Number of ssus in psu <span class="math inline">\(i\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(M_{o}\)</span></td>
<td><span class="math inline">\(\sum_{i=1}^NM_i\)</span></td>
<td>Total number of psus in the popultion</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(t_i\)</span></td>
<td><span class="math inline">\(\sum_{j=1}^{M_i}y_{ij}\)</span></td>
<td>Total in psu <span class="math inline">\(i\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(t\)</span></td>
<td><span class="math inline">\(\sum_{i=1}^Nt_i = \sum_{i=1}^N\sum_{j=i}^{M_i}y_{ij}\)</span></td>
<td>Popultion Total</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(S_i^2\)</span></td>
<td><span class="math inline">\(\frac{1}{N-1} \sum_{i=1}^N(t_i-\frac{t}{N})^2\)</span></td>
<td>Popultion variance of the psu totals</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<section id="why-use-cluster-sampling" class="level2">
<h2 class="anchored" data-anchor-id="why-use-cluster-sampling">Why use Cluster Sampling?</h2>
<ul>
<li>Constructing a sample frame list may be expensive, difficult, or impossible.
<ul>
<li>Making a sampling frame of all honeybees in a region would be impossible-you cannot enumerate them, or even be sure how many there are (N)</li>
<li>Making a sampling frame of all trees in a region is possible, however it may be extremely time consuming, and therefore expensive.</li>
</ul></li>
<li>The population may be widely distributed geographically or appear in natural clusters.
<ul>
<li>Households or schools can appear in natural clusters</li>
<li>If your target population is nursing home residents in the US, it would be very hard to take an SRS of all nursing home residents, and then travel to each one individually. Taking a cluster sample of a few nursing homes and then taking observations from everyone in them would be less expensive and time consuming.</li>
</ul></li>
</ul>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>A cluster is similar to a stratum because it is grouping members of the population.</p>
<p>However, cluster sampling reduces precision compared to SRS whereas precision is increased with a stratified sample.</p>
</div>
</div>
<p>This is because members of the same cluster tend to be very similar, and sampling everyone in the cluster results in the same information being repeated rather than learning new information.</p>
<p>Most large surveys usually use cluster sampling, most likely because of the low costs and convenience compared to other sampling methods</p>
<p>To increase the precision of the clusters, survey conductors could group the population primary sampling units (the clusters) into stratas and select a probability sample of psus within each stratum.</p>
</section>
<section id="when-clusters-are-ignored" class="level2">
<h2 class="anchored" data-anchor-id="when-clusters-are-ignored">When clusters are Ignored</h2>
<p>Do not analyze cluster samples like you would analyze an SRS. Doing so can lead to statistics from the survey appearing more precise than they actually are.</p>
<section id="studies-in-education" class="level3 success">
<h3 class="anchored" data-anchor-id="studies-in-education">Studies in education</h3>
<p>Due to the natural clustering of students within a classroom, educational studies often involve cluster sampling.</p>
<p>Consider a study where a school (the population) is stratified by classroom. 32 professors (16 male and 16 female) were selected based on the subject they taught, years of experience, and tenure status. In this example, the classrooms are the clusters.</p>
</section>
<p>Questionnaires went out to all students in each of the selected classrooms. The researchers wanted to see if students evaluated male and female professors differently.</p>
<ul>
<li>The sample size in this study is <span class="math inline">\(n = 32\)</span>, the number of faculty studied
<ul>
<li>Note this is <strong>not</strong> the total number of students who returned the questionnaire.</li>
</ul></li>
<li>Because the students in each classroom are likely to have some agreement in the rating they assign to their professor, they can not be treated as independent.
<ul>
<li>If the students are treated as independent, the variance from the sample will be <em>smaller</em> than the real value and differences between clusters will be declared statistically significant more often than they should be.</li>
</ul></li>
</ul>
<hr>
</section>
</section>
<section id="one-stage-clustering-sampling" class="level1">
<h1>One-Stage Clustering Sampling</h1>
<section id="equal-size-clusters" class="level2">
<h2 class="anchored" data-anchor-id="equal-size-clusters">Equal size clusters</h2>
<ul>
<li>Each <em>psu</em> has the same number of elements; <span class="math inline">\(M_{i} = m_{i} = M\)</span>.</li>
<li>Often can be found in agriculture or industrial sampling.</li>
<li><span class="math inline">\(t_{i}\)</span> is the total for all elements in <em>psu</em> <span class="math inline">\(i\)</span>.</li>
<li><span class="math inline">\(t_{i}\)</span> is known for sampled households, since data is collected on both individuals. (E.g. <span class="math inline">\(Var(t_{i})=0\)</span>)</li>
</ul>
<p><span class="emoji" data-emoji="arrow_right">➡️</span> Treat the <em>psu</em> means or totals as observations, and ignore the individual elements. We now have an SRS of <span class="math inline">\(n\)</span> data points.</p>
<p>Thus we can use the same SRS formulas to estimate the total and mean, <strong>however</strong> this is an SRS of <span class="math inline">\(n\)</span> <em>psu</em>’s, not an SRS of <span class="math inline">\(nM\)</span> observational units. So the <span class="math inline">\(df\)</span> needed to create a Confidence Interval is <span class="math inline">\(n-1\)</span>.</p>
<p>To estimate the population total <span class="math inline">\(t\)</span> or average <span class="math inline">\(\mu\)</span>, we can use the following estimators and variances:</p>
<p><span class="math display">\[
\hat{t} = \frac{N}{n}\sum_{i \in S}t_{i} \qquad
s_{t}^{2} = \frac{1}{n-1}\sum_{i \in S}\Big(t_{i} - \frac{\hat{t}}{N}\Big)^2
\]</span></p>
<p>and <span class="math display">\[
\hat{\bar{y}} = \frac{\hat{t}}{NM} \qquad
V(\hat{\bar{y}}) = \Big(1-\frac{n}{N}\Big)\frac{s^{2}_t}{nM^2}
\]</span></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Estimate the income in a two person households
</div>
</div>
<div class="callout-body-container callout-body">
<p>Consider individual incomes (<span class="math inline">\(y_{ij}\)</span>) for each of <span class="math inline">\(j=1,2\)</span> persons in the 3 sampled households out of the 50 in the population.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>hhi <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">household =</span> <span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>), </span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">yi1 =</span> <span class="fu">c</span>(<span class="dv">37638</span>, <span class="dv">69012</span>, <span class="dv">30001</span>), </span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">yi2 =</span> <span class="fu">c</span>(<span class="dv">79999</span>, <span class="dv">86753</span>, <span class="dv">54321</span>)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(hhi, <span class="at">align =</span> <span class="st">'c'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: center;">household</th>
<th style="text-align: center;">yi1</th>
<th style="text-align: center;">yi2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;">37638</td>
<td style="text-align: center;">79999</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: center;">69012</td>
<td style="text-align: center;">86753</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: center;">30001</td>
<td style="text-align: center;">54321</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>
<p>First define our known values: N = 50, n = 3, M = 2.</p>
<p>The total household income <span class="math inline">\(t_i\)</span> is calculated as the sum of the individual incomes within each cluster <span class="math inline">\(\sum_j y_{ij}\)</span>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>hhi<span class="sc">$</span>ti <span class="ot">&lt;-</span> hhi<span class="sc">$</span>yi1 <span class="sc">+</span> hhi<span class="sc">$</span>yi2</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>hhi</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  household   yi1   yi2     ti
1         1 37638 79999 117637
2         2 69012 86753 155765
3         3 30001 54321  84322</code></pre>
</div>
</div>
<p>The estimated mean is</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>t.hat <span class="ot">&lt;-</span> (<span class="dv">50</span><span class="sc">/</span><span class="dv">3</span>)<span class="sc">*</span><span class="fu">sum</span>(hhi<span class="sc">$</span>ti)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>(ybar.hat <span class="ot">&lt;-</span> t.hat <span class="sc">/</span> (<span class="dv">50</span><span class="sc">*</span><span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 59620.67</code></pre>
</div>
</div>
<p>with variance</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>s2.t <span class="ot">&lt;-</span> (<span class="dv">1</span><span class="sc">/</span>(<span class="dv">3-1</span>))<span class="sc">*</span><span class="fu">sum</span>((hhi<span class="sc">$</span>ti <span class="sc">-</span> t.hat<span class="sc">/</span><span class="dv">50</span>)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>(var.ybar.hat <span class="ot">&lt;-</span> (<span class="dv">1</span> <span class="sc">-</span> <span class="dv">3</span><span class="sc">/</span><span class="dv">50</span>)<span class="sc">*</span>(s2.t<span class="sc">/</span>(<span class="dv">3</span><span class="sc">*</span><span class="dv">2</span><span class="sc">^</span><span class="dv">2</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 100106551</code></pre>
</div>
</div>
<p>Calculate CI.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>crit.t <span class="ot">&lt;-</span> <span class="fu">qt</span>(.<span class="dv">975</span>, <span class="dv">3-1</span>)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>ci.low.mu  <span class="ot">&lt;-</span> ybar.hat <span class="sc">-</span> crit.t<span class="sc">*</span><span class="fu">sqrt</span>(var.ybar.hat)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>ci.hi.mu   <span class="ot">&lt;-</span> ybar.hat <span class="sc">+</span> crit.t<span class="sc">*</span><span class="fu">sqrt</span>(var.ybar.hat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can be 95% confident that the average population income for a household of two people is contained in the interval ($16,571, $102,670.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Example: Average GPA in a dorm
</div>
</div>
<div class="callout-body-container callout-body">
<p>A student wants to estimate the average GPA in their dorm. Obtaining a listing of all students in the hall and conducting an SRS would take a lot of time. Instead, since each of the 100 suites in the hall have 4 students, the student randomly samples 5 suites and collects GPA data for each student in the suite.</p>
<p>Using functions from the <code>sampling</code> package, estimate the average GPA for all students living in that dorm, with a proper 95% CI. Interpret your interval.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>gpa <span class="ot">&lt;-</span> readr<span class="sc">::</span><span class="fu">read_csv</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"data"</span>, <span class="st">"gpa.csv"</span>))</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(gpa)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
  suite   gpa    wt
  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1     1  3.08    20
2     1  2.6     20
3     1  3.44    20
4     1  3.04    20
5     2  2.36    20
6     2  3.04    20</code></pre>
</div>
</div>
<p>The data was recorded in long format – this is the format needed for analysis. The table in the book is formatted for human eyeball consumption, not for analysis.</p>
</div>
</div>
<ol type="1">
<li>Set the survey design. Here we finally use the <code>id</code> argument to identify the variable containing the <em>psu</em>’s. Printing out the object <code>gpa.design</code> lets us confirm that it is being recognized as a 1 stage cluster design with 5 clusters.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>(gpa.design <span class="ot">&lt;-</span> <span class="fu">svydesign</span>(<span class="at">id =</span> <span class="sc">~</span>suite,</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>                        <span class="at">weights =</span> <span class="sc">~</span>wt,</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>                        <span class="at">fpc=</span><span class="sc">~</span><span class="fu">rep</span>(<span class="dv">100</span>,<span class="dv">20</span>),</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>                        <span class="at">data=</span>gpa) )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>1 - level Cluster Sampling design
With (5) clusters.
svydesign(id = ~suite, weights = ~wt, fpc = ~rep(100, 20), data = gpa)</code></pre>
</div>
</div>
<ol start="2" type="1">
<li>Call <code>surveymean</code> and CI.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>(dorm.gpa.mean <span class="ot">&lt;-</span> <span class="fu">svymean</span>(<span class="sc">~</span>gpa, gpa.design))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     mean     SE
gpa 2.826 0.1637</code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>(df <span class="ot">&lt;-</span> <span class="fu">degf</span>(gpa.design)) <span class="co"># Extract degrees of freedom</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4</code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(dorm.gpa.mean, <span class="at">level=</span>.<span class="dv">95</span>, <span class="at">df=</span><span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       2.5 %   97.5 %
gpa 2.371593 3.280407</code></pre>
</div>
</div>
<p>We can be 95% confident that the average GPA for students living in this dorm is contained in the interval 2.37 to 3.28.</p>
<div class="callout callout-style-default callout-warning no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="emoji" data-emoji="star">⭐</span> You try it. High school Algebra
</div>
</div>
<div class="callout-body-container callout-body">
<p>Consider a population of 187 high school algebra classes in a city. An investigator takes an SRS of classes, and gives each student in the sampled classes a test about function knowledge. The (hypothetical) data are given in the file <code>algebra.csv</code>.</p>
<ol type="a">
<li>Load in the data and look at the first few rows. Explain what the values in each column mean.</li>
<li>Plot the distribution of test score by class. Interpret your graph by comparing the medians, ranges, and variances across classes. What do you notice?</li>
<li>How many <em>psus</em> are there? What is the <em>psu</em> with the highest number of <em>ssus</em>? Which one has the least? You must answer this question using R functions such as<code>unique</code> or <code>table</code>. Don’t count this by hand (practice for when you have a billion rows)</li>
<li>Add variables containing the weights and the <code>fpc</code> to this data set. Assign the value of 187 to a new variable for the fpc.</li>
<li>Using the proper functions from the <code>survey</code> package, estimate the population average algebra score, with a 95% interval and interpret your interval. Be sure to NOT assume a Z-distribution for this confidence interval but use the <code>degf</code> function to get the proper degrees of freedom out of the survey design object and pass it to the <code>confint</code> function.</li>
</ol>
</div>
</div>
<div class="callout callout-style-simple callout-warning no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>yay.math <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"data/algebra.csv"</span>))</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(yay.math) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
  class    Mi score
  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1    23    20    57
2    23    20    90
3    23    20    56
4    23    20    57
5    23    20    46
6    23    20    55</code></pre>
</div>
</div>
<p><strong>a)</strong></p>
<ul>
<li><code>class</code>: Class number. This is a <code>psu</code>.</li>
<li><code>Mi</code>: Number of <code>ssus</code> in each <code>psu</code>.</li>
<li><code>score</code>: Test score for each <code>ssu</code></li>
</ul>
<p><strong>b)</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(yay.math, <span class="fu">aes</span>(<span class="at">y=</span>score, <span class="at">x=</span><span class="fu">as.factor</span>(class))) <span class="sc">+</span> <span class="fu">geom_boxplot</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="cn07-cluster_sampling_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The distribution of test scores are similar-ish. Most range between 50 and 75, with class number 51 having the highest median, but also nearly the lowest minimum. The variances of classes 39, 41, and 44 have the smaller variance compared to the other classes.</p>
<p><strong>c)</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(<span class="fu">unique</span>(yay.math<span class="sc">$</span>class))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 12</code></pre>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(yay.math<span class="sc">$</span>class)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 23  37  38  39  41  44  46  51  58  62 106 108 
 20  26  24  34  26  28  19  32  17  21  26  26 </code></pre>
</div>
</div>
<p>There are 12 different classes, with class sizes ranging from 17 in class number 58 to 34 in class number 39.</p>
<p><strong>d)</strong> Survey weights were not included, so those need to be added. For a single cluster sample, the weights are calculated as <span class="math inline">\(w_{ij} = \frac{N}{n}\)</span>, the number of clusters in the population divided by the number of clusters in the sample. Here this is 187/12.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>yay.math<span class="sc">$</span>wt <span class="ot">&lt;-</span> <span class="dv">187</span><span class="sc">/</span><span class="dv">12</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>yay.math<span class="sc">$</span>fpc <span class="ot">&lt;-</span> <span class="dv">187</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>yay.math.design <span class="ot">&lt;-</span> <span class="fu">svydesign</span>(<span class="at">id =</span> <span class="sc">~</span>class, <span class="at">weights =</span> <span class="sc">~</span>wt, </span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>                             <span class="at">fpc =</span> <span class="sc">~</span>fpc,  <span class="at">data =</span> yay.math)</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>yay.math.design</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>1 - level Cluster Sampling design
With (12) clusters.
svydesign(id = ~class, weights = ~wt, fpc = ~fpc, data = yay.math)</code></pre>
</div>
</div>
<p><strong>e)</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">svymean</span>(<span class="sc">~</span>score, yay.math.design)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        mean     SE
score 62.569 1.4916</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">svymean</span>(<span class="sc">~</span>score, yay.math.design) <span class="sc">%&gt;%</span> <span class="fu">confint</span>(<span class="at">df =</span> <span class="fu">degf</span>(yay.math.design))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         2.5 %  97.5 %
score 59.28562 65.8515</code></pre>
</div>
</div>
<p>The population average math score is 62.6 (95% CI 59.3 - 65.9).</p>
</div>
</div>
</div>
<hr>
</section>
</section>
<section id="two-stage-clustering-sampling" class="level1">
<h1>Two-Stage Clustering Sampling</h1>
<p>Sometimes measurements on individual ssus are not easy to obtain, or the ssus within a psu are so similar that collecting data on all of them is a waste of resources.</p>
<p>Two-stage clustering employes <strong>another</strong> SRS of ssus within each psu. Or, more formally;</p>
<ol type="1">
<li>Select an SRS of <span class="math inline">\(n\)</span> psus from the population of N psus.</li>
<li>Select an SRS of ssus from each selected psu, where <span class="math inline">\(m_{i}\)</span> is the number of ssus selected from the <span class="math inline">\(i^{th}\)</span> psu.</li>
</ol>
<p>The point estimates for parameters such as the total or mean will still be calculated the same, but the variance equations now need to take into consideration the variance of the SRS of psus, AND the variance of the SRS of the ssus. Another way to think about it is that we have within-psu and a between-psu components to the variance now.</p>
<p>This means we can use ANOVA to calculate and understand the ratio of the between and within variance components.</p>
<section id="survey-weights" class="level3">
<h3 class="anchored" data-anchor-id="survey-weights">Survey weights</h3>
<p>Since the two SRS’s are independent, we can calculate the inclusion probability as the multiplication of the inclusion probability at each stage.</p>
<ul>
<li>Stage 1: <span class="math inline">\(P\)</span>(<span class="math inline">\(i\)</span>th psu selected) = <span class="math inline">\(\frac{n}{N}\)</span>.</li>
<li>Stage 2: <span class="math inline">\(P\)</span>(<span class="math inline">\(j\)</span>th ssu selected | <span class="math inline">\(i\)</span>th psu selected) = <span class="math inline">\(\frac{m_i}{M_i}\)</span></li>
</ul>
<p>Since the weights are the reciprocal of the inclusion probability, <span class="math display">\[
w_{ij} = \frac{N}{n}\frac{M_{i}}{m_{i}}
\]</span></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Example: More estimation of math scores.
</div>
</div>
<div class="callout-body-container callout-body">
<p>The file <code>schools.csv</code> contains data from a two-stage sample of students from hypothetical classes. The final weights are provided in the variable <code>finalwt</code>.</p>
<ol type="a">
<li>Create side by side boxplots for the math score for sampled schools. Which do you think is larger, the within or between cluster variance?</li>
<li>Create an ANOVA table for this example. Is your interpretation from the graph upheld by this analysis?</li>
<li>Estimate with proper 95% CI the average math score for the population of students under consideration. <em>Do not include a value for the <code>fpc</code> in this example</em>.</li>
</ol>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>schools <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(here<span class="sc">::</span><span class="fu">here</span>(<span class="st">"data/schools.csv"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>a)</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(schools, <span class="fu">aes</span>(<span class="at">y=</span>math, <span class="at">x=</span><span class="fu">as.factor</span>(schoolid))) <span class="sc">+</span> </span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span> <span class="fu">geom_jitter</span>(<span class="at">width=</span>.<span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="cn07-cluster_sampling_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>There is so much overlap in the distributions of math score across the schools. I think the across cluster variance may be more than the within cluster variance. Except perhaps school 35 and 75. Scores from those schools seem to be more closer within their own school.</p>
<p><strong>b)</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">aov</span>(math <span class="sc">~</span> <span class="fu">as.factor</span>(schoolid), <span class="at">data =</span> schools) <span class="sc">%&gt;%</span> <span class="fu">summary</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                     Df Sum Sq Mean Sq F value   Pr(&gt;F)    
as.factor(schoolid)   9   7018   779.8   7.583 1.79e-09 ***
Residuals           190  19538   102.8                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>The within cluster variation (MSE = 102) is smaller than the between cluster variation (MSB = 779.8). This does not match my interpretation of the prior graph.</p>
<p><strong>c)</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>sch.dsgn <span class="ot">&lt;-</span> <span class="fu">svydesign</span>(<span class="at">id =</span> <span class="sc">~</span>schoolid, <span class="at">weights =</span> <span class="sc">~</span>finalwt, <span class="at">data =</span> schools)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="fu">svymean</span>(<span class="sc">~</span>math, sch.dsgn)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       mean     SE
math 33.123 1.7599</code></pre>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">svymean</span>(<span class="sc">~</span>math, sch.dsgn) <span class="sc">%&gt;%</span> <span class="fu">confint</span>(<span class="at">df =</span> <span class="fu">degf</span>(sch.dsgn))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        2.5 %  97.5 %
math 29.14179 37.1041</code></pre>
</div>
</div>
<p>The average math score in this example is 33.1 with 95% CI 29.1-37.1</p>
</section>
<section id="summary-of-one-vs-two-stage-clustering" class="level2">
<h2 class="anchored" data-anchor-id="summary-of-one-vs-two-stage-clustering">Summary of One vs Two Stage Clustering</h2>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figs/fig5_2.jpg" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Textbook Figure 5.2. Differences between one-stage and two-stage cluster sampling.</figcaption><p></p>
</figure>
</div>
<p><strong>One Stage Clustering</strong></p>
<ul>
<li>All you do is carry out an SRS on all available PSUs from your population of <span class="math inline">\(N\)</span> PSUs. Then subsequently establish a census.</li>
<li>This provides us the variance across clusters</li>
</ul>
<p><strong>Two Stage Clustering</strong></p>
<ul>
<li>In two stage clustering the only additional step is to take an SRS of size <span class="math inline">\(m_i\)</span> within each already sample <span class="math inline">\(i\)</span>th PSU.</li>
<li>This finds the variance within clusters</li>
</ul>
<p><strong>Unbiased Estimate for <span class="math inline">\(t\)</span></strong></p>
<p><span class="math display">\[t=w_{ij}\sum y_{ij}=\sum\frac{NM_i}{nm_i}y_{ij}\]</span></p>
<p>Note: The same formula is applicable to both one and two stage clustering because, if you think about it, one stage clustering is just a special case of two stage clustering. That being the case where <span class="math inline">\(M_i=m_i\)</span>.</p>
<hr>
</section>
</section>
<section id="systematic-sampling" class="level1">
<h1>Systematic Sampling</h1>
<p>Systematic Sampling is a special case of Cluster Sampling</p>
<section id="method" class="level2">
<h2 class="anchored" data-anchor-id="method">Method</h2>
<ul>
<li>Determine a desired sample size, X</li>
<li>Determine the number of elements in the target population</li>
<li>Chose a number of desired psus, Y</li>
<li>Now draw an element and every Xth elements afterwards
<ul>
<li>Do that Y times so that you are left with Y psus</li>
</ul></li>
<li>Then SRS one of the psus</li>
</ul>
</section>
<section id="attributes-to-note" class="level2">
<h2 class="anchored" data-anchor-id="attributes-to-note">Attributes to Note</h2>
<ul>
<li>Systematic sample is more precise than SRS when the variance within the PSUs are larger than the variance of the total population.</li>
<li>In systematic sampling, we usually only SRS one psu, meaning n=1, so we cannot find the variance of population estimates.</li>
<li>So, we need to identify the structure of the population of interest to estimate the variance</li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Example: Choosing a Systematic Sample
</div>
</div>
<div class="callout-body-container callout-body">
<p>Suppose we want to take a sample of 3 from a population of 12 that is numbered 1-12.</p>
<ul>
<li>Choose a random number between one and 4 and draw that element and also every fourth element after that.
<ul>
<li>Do that until all your suss have been grouped</li>
</ul></li>
<li>Now we have four <em>psus</em> each containing 3 <em>ssus</em></li>
<li>Take an SRS of one <em>psu</em> to use as your sample.</li>
</ul>
</div>
</div>
</section>
<section id="order-matters" class="level2">
<h2 class="anchored" data-anchor-id="order-matters">Order matters</h2>
<p>How does the order of the sampling frame influence estimates?</p>
<p><strong>The sampling frame is in random order</strong></p>
<ul>
<li>Systematic sampling is likely to produce a sample that behaves like an SRS.</li>
<li>Oftentimes, the ordering of the population is unrelated to the characteristic of interest.</li>
<li>We can use SRS results and formulas to calculate the variance of a systematic sample.</li>
</ul>
<p><strong>The sampling frame is increasing or decreasing in order</strong></p>
<ul>
<li>Systematic sampling is likely to be more precise than SRS.</li>
<li>Forces the sample values to be more spread out; an SRS could consist of mostly low or high values.</li>
<li>Can use SRS formulas to calculate SE, but it will likely be an overestimate.</li>
</ul>
<p><strong>The sampling frame has a periodic pattern</strong></p>
<ul>
<li>Less precise than SRS</li>
<li>Most dangerous when the population is cyclical or periodic order, and the sampling interval coincides with a multiple of the period</li>
</ul>
<p>If periodicity is a concern, using <strong>interpenetrating systematic samples</strong> may be beneficial.</p>
<ul>
<li>Take multiple systematic samples from the population, then use formulas for cluster sampling to estimate the desired point estimates.</li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Example: sampling toxic waste
</div>
</div>
<div class="callout-body-container callout-body">
<p>Many dumps and landfills contan hazardous waste that was sealed when it was deposited, however may have began leaking since it was dumped. Since we dont know where the waste was deposited, in order to know if there is any leakage of waste, a systematic sample can be used.</p>
<ol type="1">
<li>Choose a point in a random area, and construct a grid containing that point so that the grid points are equal distance away from each other</li>
<li>take soil samples from each to see if there are traces of hazardous waste</li>
</ol>
</div>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figs/toxic_waste.png" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Example of sampling Toxic Waste sites</figcaption><p></p>
</figure>
</div>
<p><strong>Pros and Cons of Systematic Sampling in this example</strong>: forces even coverage of the reason, and it is easy to implement in the field. If you have little knowledge about the exact location of what you are looking for.</p>
<p>As with any grid sample, you need to worry about whether or not the hazardous waste is reglarly placed so that the grid would miss all of it.</p>
<div class="callout callout-style-default callout-important no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Definition: Interpenetrating Sampling
</div>
</div>
<div class="callout-body-container callout-body">
<p>Modify a Systematic Sampling approach by</p>
<ol type="1">
<li>change the starting point and keep the interval,</li>
<li>change the interval and keep the starting point,</li>
<li>or change both</li>
</ol>
</div>
</div>
<ul>
<li>Used if we are concerned about periodicity</li>
<li>Any of these changes force more coverage of the total population vs a systematic sample</li>
<li>Instead of taking one systematic sample from our population, we take several</li>
<li>In this case, each systematic sample acts as a cluster</li>
<li>We can use formulas for cluster samples to estimate variance</li>
</ul>
<hr>
</section>
</section>
<section id="clusters-of-equal-sizes-theory" class="level1">
<h1>Clusters of Equal Sizes (Theory)</h1>
<p>This section compares the analysis of variance in cluster sampling compared to stratified and SRS.</p>
<ul>
<li>Cluster sampling almost always has less precision for the estimates than from an SRS with the same amount of elements!</li>
<li>In one-stage cluster sampling, the variability of an unbiased estimator depends on the between psu variability.</li>
<li>We can use an ANOVA table to explore the breakdown of the source of variance into between <em>psus</em> and within <em>psus.</em></li>
</ul>
<div class="callout callout-style-default callout-important no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
ANalysis Of VAriance
</div>
</div>
<div class="callout-body-container callout-body">
<p>Don’t recall how ANOVA works to break up the variance into components? See <a href="https://www.youtube.com/watch?v=W36DMVJ4Ibo&amp;list=PLkIselvEzpM5G3IO1tzQ-DUThsJKQzQCD">this great video</a> from the Open Intro Statistics author, Mine Cetinkaya-Rundel</p>
</div>
</div>
<section id="msb-mean-squared-between-clusters" class="level3">
<h3 class="anchored" data-anchor-id="msb-mean-squared-between-clusters">MSB (Mean Squared Between Clusters)</h3>
<ul>
<li>A measure of between cluster variability</li>
<li>In stratification, increase in MSB increases precision</li>
<li>In clustering, increase in MSB decreases precision
<ul>
<li>MSB is relatively large because it measures the cluster-to-cluster variability. Also, the MSB can be too large when unmeasured factors affect the overall mean for a cluster</li>
</ul></li>
</ul>
</section>
<section id="msw-mean-squared-within-clusters" class="level3">
<h3 class="anchored" data-anchor-id="msw-mean-squared-within-clusters">MSW (Mean Squared Within Clusters)</h3>
<ul>
<li>A measure of within cluster variability</li>
<li>When clusters are relatively homogeneous, the MSW will be small</li>
</ul>
<div class="callout callout-style-simple callout-note no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p>When MSB/MSW is large, precision decreases! Better off doing an SRS of the same size.</p>
</div>
</div>
</div>
</section>
<section id="icc-intraclass-correlation-coefficient" class="level2">
<h2 class="anchored" data-anchor-id="icc-intraclass-correlation-coefficient">ICC (Intraclass Correlation Coefficient)</h2>
<p>Let’s us know how similar elements are in the same cluster; a measure of homogeneity within the cluster</p>
<ul>
<li>With a positive ICC, elements within the same cluster are similar. A negative ICC indicates the elements within a cluster to not be similar; elements are dispersed more.
<ul>
<li>Cluster sampling is less efficient than SRS of elements</li>
</ul></li>
<li>With a negative ICC, then the elements within a cluster are dispersed more than a randomly chosen group</li>
<li>Naturally occurring clusters is the cause for an ICC to be positive, usually not negative</li>
</ul>
</section>
<section id="r-squared" class="level2">
<h2 class="anchored" data-anchor-id="r-squared">R Squared</h2>
<p>Adjusted <span class="math inline">\(R^2\)</span> is for an alternative measure of homogeneity in general populations.</p>
<ul>
<li><span class="math inline">\(R^2\)</span> can be used to measure homogeneity because its interpretation in linear regression</li>
<li>When the <em>psus</em> are homogeneous then the <em>psu</em> means will be highly variable relative to the variation within <em>psus</em>, and <span class="math inline">\(R^2\)</span> will be high.</li>
</ul>
<hr>
</section>
</section>
<section id="designing-a-cluster-sample" class="level1">
<h1>Designing a Cluster Sample</h1>
<p>A psu that is too large may eliminate the cost related benefits of clustering</p>
<ul>
<li>Step 1: What overall precision is needed?</li>
<li>Step 2: What size should the psus be?</li>
<li>Step 3: How many ssus should be sampled in each psu selected for the sample?</li>
<li>Step 4: How many psus should be sampled?</li>
</ul>
<p>Any survey design must know the answer to question 1, and to answer questions 2-4 the cost of sampling a psu for potential psus, the cost of sampling a ssu, and a measure of homogeneity (ICC) for potential sizes of psu must be known.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">This site is built with <span class="emoji" data-emoji="heart">❤️</span>, and <a href="https://quarto.org/">Quarto</a> by <a href="www.norcalbiostat.com">Robin Donatello</a> and the Spring 2023 MATH 458 class.</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>



</body></html>