{
  "hash": "671ec025e5928743b05c25976ced59a5",
  "result": {
    "markdown": "---\ntitle: \"Stratified Sampling\"\ndescription: \"A method to use additional information about the population in the survey design. Lohr Ch 3. \"\nauthor: DRAFT - 458 class\ndate: 3/20/23\nexecute: \n  error: true\n  warning: false\n  message: false\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(here); library(tidyverse);library(knitr)\nlibrary(sampling); library(survey)\n```\n:::\n\n\n# What is Stratified Sampling\n\n## Overview\n\n-   A sampling technique in which we divide the desired population into subgroups called *strata*\n-   Each individual is necessarily in a single strata; no overlap within strata\n-   All strata consist of the entire population\n-   An SRS is taken from each strata, then results can be pooled to make inferences about the entire population\n\n### Why Use A Stratified Sample?\n\n-   Protection from bad samples; less likely of drawing a non representative sample through pure chance\n-   Want data of known subgroups (i.e., if we are interested in people's heights, we know that men tend to be taller than women)\n-   Convenience / cost effectiveness -- At what point will this compromise the legitimacy of the study?\n-   Lowers variance when done properly; variance within each strata is likely lower than the population variance\n-   you do not have to sample the same fraction of observations in each stratum. If the variability is higher in a certain strata then you can try to reduce the variability of the estimated total by taking more observations from that stratum.\n\n::: {.callout-tip icon=\"true\"}\n### Motivating Example - Estimating the average number of farm acres.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nagpop <- read_csv(here(\"data\", \"agpop.csv\"))\n```\n:::\n\n\nIn Example 2.6 we took a SRS to find the average number of farm acres per county. Even though our methods of taking an SRS were correct, some areas of the country were over or underrepresented due to the variability in the size of farms in different regions in the country. An example of this would be that western states in the U.S tend to be larger, and therefore tend to have larger farms.\n:::\n\nTo try and fix this, we can use a stratified sample can give balance to the sample on the stratifying variable, which in this case would be region that the farms are located.\n\nTo begin, we can divide our data into four regions (these are the strata):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nunique(agpop$region) # the four regions and their names\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"W\"  \"S\"  \"NE\" \"NC\"\n```\n:::\n:::\n\n\nPreviously we sampled 10% of the population with an SRS, and so to be able to compare our results with our stratified sample, we should sample 10% of the population from each strata through four separate and independent SRS's.\n\nThe process to do this would be to take the four regions, number off the counties that are in the region, calculate what number of counties is 10% of the total number of counties in the region, and select that many numbers from the list of numbered counties.\n\n> *Details on how to do this in R is covered in a later section. For now we will use the `agstrat` dataset from the book as the stratified sample.*\n\n\n::: {.cell}\n\n```{.r .cell-code}\nagstrat <- read_csv(here(\"data\", \"agstrat.csv\"))\n```\n:::\n\n\n::: {.callout-tip icon=\"true\"}\n### Exploring the distribution of farm acreage in 1992 by region.\n\n\n::: {.cell .fig-cap-location-top}\n\n```{.r .cell-code}\nboxplot(acres92/10^6 ~ region, data = agstrat,\n        xlab = \"Region\", ylab = \"Millions of Acres\")\n```\n\n::: {.cell-output-display}\n![The thick line for each region is the median of the sample data from that region. The upper and lower horizontal lines of the boxes are the 25th and 75th percentiles.](cn06-stratified_sampling_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\nThe Northeast has the lowest median and the smallest variance. The West has the highest median and the highest mean and variance. The distribution of farm acreage appears to to be positively skewed in each region.\n:::\n\nThe summary statistics $\\bar{y}_{h}$ and $s^{2}_{h}$ can be calculated using R after grouping by the stratification variable.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable3.1 <- agstrat %>% \n   group_by(region) %>% \n   summarize(y.bar.h = mean(acres92),\n             s2.h    = var(acres92),\n             n.h     = n())\n\ncounties_in_pop <- table(agpop$region)\nnew_table3.1 <- cbind(table3.1, counties_in_pop)\nnew_table3.1 <- select(new_table3.1, -Var1) # drop the extra variable \ncolnames(new_table3.1) <- c(\"Region\", \"Sample Avg in Region\", \"Sample Variance in Region\", \n\"Number of Counties in Region\", \"Number of Counties in Population\")\n\nkable(new_table3.1)\n```\n\n::: {.cell-output-display}\n|Region | Sample Avg in Region| Sample Variance in Region| Number of Counties in Region| Number of Counties in Population|\n|:------|--------------------:|-------------------------:|----------------------------:|--------------------------------:|\n|NC     |            300504.16|               29618183543|                          103|                             1054|\n|NE     |             97629.81|                7647472708|                           21|                              220|\n|S      |            211315.04|               53587487856|                          135|                             1382|\n|W      |            662295.51|              396185950266|                           41|                              422|\n\n\n\nLohr Table 3.1. Summary statistics for each stratum\n:::\n:::\n\n\nThese summary statistics can be used to calculate estimates of the total number of farms acres, and estimated variance of the total within each of the four stratum (Table 3.2 below)\n\nBecause we took an SRS in each stratum, we can use the following equations to estimate population quantities for each stratum.\n\n$\\hat{\\tau_{h}} = N * \\bar{y}_{h} \\quad \\mbox{ and } \\quad \\hat{V}(\\hat{\\tau}_{h}) = N_{h}^{2} * \\hat{V}(\\bar{y}_{h})$\n\n-   We can estimate the total number of acres devoted to farming in the United States in 1992 by summing the estimated totals for each stratum.\n-   The variance of the total is the sum of the variances of the estimated stratum totals.\n\n> More information on how to do this in the next section.\n\n::: {.callout-warning icon=\"false\"}\n### :star: You try it.\n\nExplore the distribution of farm acreage in 1987 by region. Create a table of summary statistics and a boxplot. Discuss your findings.\n:::\n\n::: {.callout-warning icon=\"false\" collapse=\"true\" appearance=\"minimal\"}\n### Solution\n\n\n::: {.cell}\n\n```{.r .cell-code}\nagstrat %>%\n  group_by(region) %>%\n  summarize(y.bar = mean(farms87),\n            s2 = var(farms87),\n            n. =n())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 4 × 4\n  region y.bar      s2    n.\n  <chr>  <dbl>   <dbl> <int>\n1 NC      837. 156050.   103\n2 NE      605. 175660.    21\n3 S       610. 231169.   135\n4 W       615. 275507.    41\n```\n:::\n\n```{.r .cell-code}\nggplot(agstrat, aes(x = region, y = farms87, fill = region)) +\n  geom_boxplot() +\n  labs(title = \"Box Plot of Farm acreage in 1987 by Region\",\n       x = \"Region\",\n       y = \"Acreage\")\n```\n\n::: {.cell-output-display}\n![](cn06-stratified_sampling_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\nBoth the boxplot and the table suggest that, on average, farms in the north-central region have the most acreage (837 acres). The mean acreages in the North East, South, and West regions are similar, ranging from 605-615 acres. The variances for all four regions are large, suggesting the individual acreage of the farms varies greatly and is not precise. The results indicate that the quantity's mean value for area North Central is 837.0485 with a variance of 156503.3 and a sample size of 103. The mean value for area North East is 605.2381, with a variance of 175660.4 and a sample size of 21. With a sample size of 135 and a variance of 231169.2, the mean value for region South is 610.4889. For region West with a sample size of 41, the mean value is 614.7073 with a variance of 275506.9.\n:::\n\n## Gain from stratification\n\n-   Observations within strata are more similar to each other, than they are to the population as a whole\n-   reduction in variance in individual strata can lead to a reduced variance for the population estimate.\n\n::: callout-important\n### Definition: Relative gain from stratification\n\n$$\n\\frac{\\hat{Var_{strata}}}{\\hat{Var_{SRS}}}\n$$\n:::\n\nFrom the Farm example, this ratio was calculated to be 0.75. That means we would only need 0.75\\*300 = 225 observations from a stratified sample to obtain the same precision as from a SRS of 300.\n\n> By sampling within strata, we are \"borrowing\" information from other similar observations.\n\n::: {.callout-note icon=\"false\" collapse=\"true\" appearance=\"minimal\"}\n### Clean up\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrm(counties_in_pop, table3.1, new_table3.1)\n```\n:::\n\n:::\n\n# Theory of Stratified Sampling\n\n## Notation and Formulas used in Stratified Random Sampling\n\n-   To take a stratified random sample, we take a SRS from each stratum, so that $n_h$ units are sampled from the $N_h$ population units in stratum $h$.\n-   Statistics and sample sizes for stratum $h$ have subscript $h$ where $h=1 \\ldots H$ index strata\n-   When a statistic has the subscript $str$, that means that the statistic is the combined estimate across all stratas.\n    -   $\\bar{y}_{str}$ is a weighted average of the sample stratum means\n    -   $\\hat{p}_{str}$ estimated proportion of population units having a specified characteristic. *Recall a proportion is a mean of a variable that takes on the values 0 and 1.*\n-   $y_{hj}$ value of the $j$th unit in strata $h$\n-   $\\sum_{j=1}^{n_{h}}$ means to sum of *all* units in strata $h$\n-   $\\sum_{j}$ means to sum over the units that were sampled from in strata $h$\n-   $\\sum_{h}$ is shorthand for $\\sum_{H=1}^{h}$\n\n::: panel-tabset\n## Formulas\n\n| Measure                   | Population $(\\theta)$                                                  | Sample $(\\hat{\\theta})$                                     |\n|------------------|-----------------------------|-----------------------------|\n| Sample size in strata $h$ | $N_{h}$                                                                | $n_{h}$                                                     |\n| Overall sample size       | $N = \\sum^{H}_{h=1} N_{h}$                                             | $n = \\sum^{H}_{h=1} n_{h}$                                  |\n| Var(y) in strata $h$    | $\\sigma_{h}^2 = \\frac{1}{N_{h}-1}\\sum_{j=1}^{N_{h}}(y_{hj}-\\mu_{h})^2$ | $s_{h}^2 = \\frac{1}{n_{h}-1}\\sum_{j}(y_{hj}-\\bar{y}_{h})^2$ |\n| Total in strata $h$       | $\\tau_{h} = \\sum_{j=1}^{N_{h}} y_{hj}$                                 | $\\hat{\\tau}_{h} = N_{h}\\bar{y_h}$                           |                         |\n| Overall total             | $\\tau = \\sum_{h=1}^{H} \\tau_{h}$                                       | $\\hat{\\tau}_{str} = \\sum_{h=1}^{H}N_{h}\\bar{y}_{h}$         |\n| Mean in strata $h$        | $\\mu_{h} = \\frac{\\tau_{h}}{N_{h}}$                                     | $\\bar{y}_{h} = \\frac{1}{n_{h}}\\sum_{j} y_{hj}$              |\n| Overall mean              | $\\mu = \\frac{\\tau}{N}$                                                 | $\\bar{y}_{str} = \\sum_{h=1}^{H} \\frac{N_{h}}{N}\\bar{y}_{h}$ |\n| Proportion in strata $h$ | $p_{h} = \\mu_h$ | $\\bar{y}_h = \\hat{p}_h$ |\n| Variance of $p_{h}$ | $\\sigma_h^2=\\frac{N_h}{N_h-1} p_h(1-p_h)$ | $s_h^2=\\frac{n_h}{n_h-1} \\hat{p}_h(1-\\hat{p}_h)$ |\n| Overall proportion | $p_{str} = \\sum_{h=1}^{H} \\frac{N_h}{N} p_h$ | $\\hat{p}_{str} = \\sum_{h=1}^{H} \\frac{N_h}{N}\\hat{p}_h$  |\n\n## Explanations\n\n| Measure                   | Population $(\\theta)$                   | Sample $(\\hat{\\theta})$                      |\n|------------------|---------------------------|---------------------------|\n| Sample size in strata $h$ | number of population units in stratum h | sample size taken in stratum h               |\n| Overall sample size       | total population size, from all strata  | total sample size, from all strata           |\n| Total in strata $h$       | population total in strata h            | estimated population total in stratum h      |\n| Overall total             | population total                        | estimated population total                   |\n| Mean in strata $h$        | population mean in strata h             | sample mean in stratum h                     |\n| Overall mean              | population mean                         | weighted average of the sample stratum means |\n| Variance of the mean      | population variance in stratum h        | sample variance in stratum h                 |\n| Proportion in strata $h$  |                                         |                                              |\n| Variance of proportion    |                                         |                                              |\n| Overall proportion        |                                         |                                              |\n:::\n\nWith estimated variances; \n\n* Within strata total $\\hat{V}(\\hat{\\tau}_{h}) = (1-\\frac{n_h}{N_h})N^2 \\frac{s^2_h}{n_h}$  \n* Within strata mean  $\\hat{V}(\\bar{y}_{h}) = \\frac{1}{N^2}V(\\hat{\\tau}_{h})$\n* Overall population total $\\hat{V}(\\hat{\\tau}_{str}) = \\sum_{h=1}^H (1-\\frac{n_h}{N_h})N^2 \\frac{s^2_h}{n_h}$\n* Population proportion $\\hat{V}(\\hat{p}_{str}) = \\sum_{h=1}^H (1-\\frac{n_h}{N_h}) (\\frac{N_h}{N})^2 \\frac{\\hat{p}_h (1-\\hat{p}_h)}{n_h-1}$\n* Estimated total number of population units having a specified characteristic: $\\hat{t}_{\\it{str}} = \\sum_{h=1}^H N_h \\hat{p}_h$\n\n\n\n## Confidence Interval for Stratified Random Sample\n\nIf either the sample sizes within each stratum are large or the sampling design has a large number of strata, then the confidence interval for the population mean $\\bar{y}\\mu$ is:\n\n$$ \\bar{y}_{str}= \\pm z_{\\alpha /2 } SE (\\bar{y}_{str})$$\n\nHowever, most survey packages use a $t_{n-H}$ distribution instead of using the normal assumption.\n\n::: {.callout-tip icon=\"true\"}\n### Example: Estimate the total number of farm acres in 1992 (Table 3.2)\n\nThe best way to understand an equation, is to try to use it in a calculation.\n:::\n\n1.  Calculate summary statistics for each region. *This was seen earlier as `new_table3.1`*\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstrata.summary.stats <- agstrat %>% \n   group_by(region) %>% \n   summarize(y.bar.h = mean(acres92),\n             s2.h    = var(acres92),\n             n.h     = n()) \n```\n:::\n\n\n2.  Calculate Population region sizes, add this vector to the data frame created above.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(region.size <- agpop %>% group_by(region) %>% tally())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 4 × 2\n  region     n\n  <chr>  <int>\n1 NC      1054\n2 NE       220\n3 S       1382\n4 W        422\n```\n:::\n\n```{.r .cell-code}\nstrata.summary.stats$N.h <- region.size$n\nstrata.summary.stats\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 4 × 5\n  region y.bar.h          s2.h   n.h   N.h\n  <chr>    <dbl>         <dbl> <int> <int>\n1 NC     300504.  29618183543.   103  1054\n2 NE      97630.   7647472708.    21   220\n3 S      211315.  53587487856.   135  1382\n4 W      662296. 396185950266.    41   422\n```\n:::\n:::\n\n\n3.  Calculate the sample total $\\hat{\\tau}_{h} = N_{h}\\bar{y_h}$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstrata.summary.stats$tau.hat.h <- strata.summary.stats$y.bar.h * strata.summary.stats$N.h\nstrata.summary.stats\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 4 × 6\n  region y.bar.h          s2.h   n.h   N.h  tau.hat.h\n  <chr>    <dbl>         <dbl> <int> <int>      <dbl>\n1 NC     300504.  29618183543.   103  1054 316731380.\n2 NE      97630.   7647472708.    21   220  21478558.\n3 S      211315.  53587487856.   135  1382 292037391.\n4 W      662296. 396185950266.    41   422 279488706.\n```\n:::\n:::\n\n\n4.  Calculate the within-strata variance of this total $\\Big(1 - \\frac{n_{h}}{N_{h}}\\Big)N^{2}_{h}\\frac{s^{2}_{h}}{n_{h}}$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstrata.summary.stats <- strata.summary.stats %>%\n  mutate(var.tau.hat.h = \n           (1 - n.h/N.h)*(N.h^2)*(s2.h/n.h)\n  )\nstrata.summary.stats\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 4 × 7\n  region y.bar.h          s2.h   n.h   N.h  tau.hat.h var.tau.hat.h\n  <chr>    <dbl>         <dbl> <int> <int>      <dbl>         <dbl>\n1 NC     300504.  29618183543.   103  1054 316731380.       2.88e14\n2 NE      97630.   7647472708.    21   220  21478558.       1.59e13\n3 S      211315.  53587487856.   135  1382 292037391.       6.84e14\n4 W      662296. 396185950266.    41   422 279488706.       1.55e15\n```\n:::\n:::\n\n\n5.  Calculate the overall total $\\hat{\\tau}_{str}$ and variance $\\hat{V}\\big(\\hat{\\tau}_{str}\\big)$ by summing these values across the strata.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(tau.hat.str <- sum(strata.summary.stats$tau.hat.h))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 909736035\n```\n:::\n\n```{.r .cell-code}\n(V.tau.hat.str <- sum(strata.summary.stats$var.tau.hat.h))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 2.541899e+15\n```\n:::\n:::\n\n\nThe estimated total number of acres devoted to farming is 909,736,035, with standard error 50,417,248. These numbers match those found in Table 3.2.\n\n::: {.callout-warning icon=\"false\"}\n### :star: You try it\n\nSiniff and Skoog (1964) used stratified random sampling to estimate the size of a herd of Alaskan caribou in 1992. Using prior known caribou density estimates for the region, the researches divided the area into 6 strata, then within each strata they formed a grid where each cell was 4 sq miles. They then randomly sampled the grids within each strata. The summary information from each strata is contained in the table below.\n\n\n::: {.cell}\n::: {.cell-output-display}\n|Stratum | N.h| n.h| y.bar.h|   s2.h|\n|:-------|---:|---:|-------:|------:|\n|A       | 400|   8|    24.1|   5575|\n|B       |  30|  10|    25.6|   4064|\n|C       |  61|  37|   267.6| 347556|\n|D       |  18|   6|   179.0|  22798|\n|E       |  70|  39|   293.7| 123578|\n|F       | 120|  21|    33.2|   9795|\n:::\n:::\n\n\nUse this information and the equations from this chapter to calculate the estimated total number of caribou in this region in Alaska with a 95% CI.\n:::\n\n::: {.callout-warning icon=\"false\" collapse=\"true\" appearance=\"minimal\"}\n### Solution\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create data frame\ncaribou <- data.frame(\n  Stratum = c(\"A\", \"B\", \"C\", \"D\", \"E\", \"F\"), \n  N.h = c(400, 30, 61, 18, 70, 120), \n  n.h = c(98, 10, 37, 6, 39, 21), \n  y.bar.h = c(24.1, 25.6, 267.6, 179, 293.7, 33.2), \n  s2.h = c(5575, 4064, 347556, 22798, 123578, 9795))\n\n# within strata total\ncaribou$tau.hat.h <- caribou$y.bar.h *caribou$N.h\n\n# within strata variance\ncaribou <- caribou %>%\n  mutate(var.tau.hat.h = (1 - n.h/N.h)*(N.h^2)*(s2.h/n.h)\n  )\n\n# overall total and variance of the total\n(tau.hat.str <- sum(caribou$tau.hat.h))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 54496.6\n```\n:::\n\n```{.r .cell-code}\nV.tau.hat.str <- sum(caribou$var.tau.hat.h)\n\n# calculating at CI using a t_{n-H} distribution\nn.caribou <- sum(caribou$n.h)\nn.strata <- length(caribou$Stratum)\ndf <- n.caribou - n.strata\n\n(crit.value <- qt(.975, df))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.971603\n```\n:::\n\n```{.r .cell-code}\ns.error <- sqrt(var.tau.hat.str)\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in eval(expr, envir, enclos): object 'var.tau.hat.str' not found\n```\n:::\n\n```{.r .cell-code}\n(tau.hat.str - crit.value*s.error)\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in eval(expr, envir, enclos): object 's.error' not found\n```\n:::\n\n```{.r .cell-code}\n(tau.hat.str + crit.value*s.error)\n```\n\n::: {.cell-output .cell-output-error}\n```\nError in eval(expr, envir, enclos): object 's.error' not found\n```\n:::\n:::\n\n\n::: {.callout-tip icon=\"true\"}\n### missing\n\nCI and interpretation of CI\n:::\n\nThis CI only explains uncertainty due to sampling error, if researchers tend to miss animals, this CI will be low.\n:::\n\n::: {.callout-warning icon=\"false\"}\n### :star: You try it\n\nThe ACLS intends to use a stratified random sample to study publications and library use among members. They divide their data into discipline, making 7 stratas.\n\nUse the summary table below to estimate the the percentage and number of respondents that are female in those seven disciplines.\n\n\n::: {.cell}\n::: {.cell-output-display}\n| Membership | Valid.Returns | Female.members |\n|:----------:|:-------------:|:--------------:|\n|    9100    |      636      |      0.38      |\n|    1950    |      451      |      0.27      |\n|    5500    |      481      |      0.18      |\n|   10850    |      611      |      0.19      |\n|    2100    |      493      |      0.36      |\n|    5500    |      575      |      0.13      |\n|    9000    |      588      |      0.26      |\n:::\n:::\n\n:::\n\n::: {.callout-warning icon=\"false\" collapse=\"true\" appearance=\"minimal\"}\n### Solution\n\nFirst extract the table information into vectors.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nNh <- c(9100,1950,5500,10850,2100,5500,9000)\nnh <- c(636,451,481,611,493,575,588)\nph <- c(.38,.27,.18,.19,.36,.13,.26)\nN <- sum(Nh)\n```\n:::\n\n\nThen the overall estimated proportion of female members in the societies is calculated as\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(p.str = sum((Nh/N)*ph))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.2465227\n```\n:::\n:::\n\n\nwith variance\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum((1-(nh/Nh))*((Nh/N)^2)*((ph*(1-ph))/(nh-1)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 5.067478e-05\n```\n:::\n:::\n\n\nThe total number of female members in this society is calculated as\n\n\n::: {.cell}\n\n```{.r .cell-code}\nN*p.str\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 10847\n```\n:::\n:::\n\n\nThere are an estimated 10,847 female members.\n:::\n\n::: {.callout-note icon=\"false\" collapse=\"true\" appearance=\"minimal\"}\n### Clean up\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrm(list=ls()[!ls() %in% c(\"agpop\", \"agstrat\",\"caribou\")])\n```\n:::\n\n:::\n\n# Sampling Weights\n\n## How are weights calculated?\n\nSampling weights in the context of Stratified Sampling function almost identically as they did in SRS.\n\nFor any unit $j$ in a stratum $h$, a sampling weight($w_{hj}$) is still the inverse of an inclusion probability($\\pi_{hj}$). However, because the population of a stratum, $N_h$, and the size of a sample of a stratum, $n_h$, don't have to be constant within a population of $H$ strata, each stratum will have different sampling weights.\n\n$w_{hj}= \\frac{1}{\\pi_{hj}}=\\frac{N_h}{n_h}$\n\n## How are weights used?\n\nThe weights are directly applied to the values of $y$ before being used in any calculations.\n\n$$\\hat{t}_{str}= \\sum_{h=1}^H\\sum_{j\\in S_h} w_{hj}y_{hj}$$\n\nis the estimator of the total population using a stratified sample, and\n\n$$\\bar{y}_{str}= \\frac{\\hat{t}_{str}}{\\sum_{h=1}^H\\sum_{j\\in S_h} w_{hj}}=\n\\frac{\\sum_{h=1}^H\\sum_{j\\in S_h} w_{hj}y_{hj}}{\\sum_{h=1}^H\\sum_{j\\in S_h} w_{hj}}$$\n\nis the estimate for a population mean using stratified sampling.\n\n::: {.callout-tip icon=\"true\"}\n### Example: Re-Estimate the total number of farm acres in 1992 using sample weights\n\nNote, this agriculture example was designed so that each county in the US had approximately the same probability of appearing in the sample.\n:::\n\n1.  Calculate stratum weights. Sometimes this is given to you, othertimes you have to calculate it.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstrat.weights <- data.frame(\n  region = table(agpop$region) %>% names(),\n  N.h = table(agpop$region) %>% as.vector(), \n  n.h = table(agstrat$region) %>% as.vector()\n)\nstrat.weights$wt <- strat.weights$N.h / strat.weights$n.h\nstrat.weights\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  region  N.h n.h       wt\n1     NC 1054 103 10.23301\n2     NE  220  21 10.47619\n3      S 1382 135 10.23704\n4      W  422  41 10.29268\n```\n:::\n:::\n\n\n2.  Merge those weights back onto the sample data, joining by region.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nagstrat <- agstrat %>% left_join(strat.weights)\ntable(agstrat$wt)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n10.2330097087379  10.237037037037 10.2926829268293 10.4761904761905 \n             103              135               41               21 \n```\n:::\n:::\n\n\nThis last table is used to confirm that the number of weighting values equals the strata sample sizes.\n\n3.  Calculate the weighted values $w_{hj}y_{hj}$. The weights need to be applied to the individual data points, $y_{jh}$, then all the above calculations can occur again.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nagstrat$wtd.acres92 <- agstrat$acres92 * agstrat$wt \n```\n:::\n\n\n4.  Calculate the weighted totals and variances within strata. Include the population and sample sizes within each strata in the `group_by` statement so it can remain on the grouped dataset for later use.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(wt.str.sum.stats <- agstrat %>%\n   group_by(region, N.h, n.h) %>% \n   summarize(y.bar.h = sum(wtd.acres92)/n.h,  \n             s2.h    = (1/(n.h-1))*sum((wtd.acres92-y.bar.h)^2)\n             ) %>%\n   unique() # this removes duplicate rows created in the variance function\n )\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 4 × 5\n# Groups:   region, N.h, n.h [4]\n  region   N.h   n.h  y.bar.h    s2.h\n  <chr>  <int> <int>    <dbl>   <dbl>\n1 NC      1054   103 3075062. 3.10e12\n2 NE       220    21 1022788. 8.39e11\n3 S       1382   135 2163240. 5.62e12\n4 W        422    41 6816798. 4.20e13\n```\n:::\n:::\n\n\n5.  Calculate within strata totals and variances $\\hat{\\tau}_{h}$ and $\\hat{V}(\\hat{\\tau}_{h})$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(wt.str.sum.stats <- wt.str.sum.stats %>% \n    mutate(tau.hat.h = y.bar.h * N.h , \n           var.tau.hat.h = (1 - n.h/N.h)*(N.h^2)*(s2.h/n.h)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 4 × 7\n# Groups:   region, N.h, n.h [4]\n  region   N.h   n.h  y.bar.h    s2.h   tau.hat.h var.tau.hat.h\n  <chr>  <int> <int>    <dbl>   <dbl>       <dbl>         <dbl>\n1 NC      1054   103 3075062. 3.10e12 3241115284.       3.02e16\n2 NE       220    21 1022788. 8.39e11  225013466.       1.75e15\n3 S       1382   135 2163240. 5.62e12 2989597592.       7.17e16\n4 W        422    41 6816798. 4.20e13 2876688634.       1.65e17\n```\n:::\n:::\n\n\n6.  Calculate the overall total $\\hat{\\tau}_{str}$ and variance $\\hat{V}\\big(\\hat{\\tau}_{str}\\big)$ by summing these values across the strata.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(tau.hat.str <- sum(wt.str.sum.stats$tau.hat.h))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 9332414976\n```\n:::\n\n```{.r .cell-code}\n(V.tau.hat.str <- sum(wt.str.sum.stats$var.tau.hat.h))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 2.682133e+17\n```\n:::\n:::\n\n\n> Note. This value for `tau.hat.str` does not match what the book says. Not sure where the error is at.\n\n::: {.callout-warning icon=\"true\"}\n### :star: You try it Caribou weights\n\nIn the caribou example, strata A had N=400 and n=98, so the sampling weight is 400/98 or 4.08.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncaribou$w.hj <- caribou$N.h/ caribou$n.h\ncaribou %>% select(Stratum:n.h, w.hj)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  Stratum N.h n.h     w.hj\n1       A 400  98 4.081633\n2       B  30  10 3.000000\n3       C  61  37 1.648649\n4       D  18   6 3.000000\n5       E  70  39 1.794872\n6       F 120  21 5.714286\n```\n:::\n:::\n\n:::\n\nNote: We cannot re-estimate the total number of caribou using the information provided because we are given the summary statistics $\\bar{Y}_h$, not the raw data $y_{hj}$. To re-estimate the total number of caribou we would need to multiply the weights $w_{h}$ to $y_{hj}$.\n\n::: {.callout-note icon=\"false\" collapse=\"true\" appearance=\"minimal\"}\n### Clean up\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrm(list=ls()[!ls() %in% c(\"agpop\", \"agstrat\",\"caribou\")])\n```\n:::\n\n:::\n\n------------------------------------------------------------------------\n\n# Allocation Methods\n\nDesigning the survey is the most important part of using a survey in research. If the survey is badly designed, then no amount of analysis will yield the needed information.\n\nSimple random sample was easy - you just need to figure out the end sample size. For stratified sampling, we need to define the strata, and the sample size within each strata.\n\n#### Method 1: Proportional Allocation\n\nThe number of sampling unit in a stratum is proportional to the population of each stratum.\n\n-   Probability selection (n/N) the same for each stratum (n being the number of sampling units in the stratum and N being the population of the stratum)\n-   Weight of each sample will be the same\n-   Stratified sampling estimate of the population mean is the average of all observations\n-   Self-weighting: every unit in sample carries the same weight\n-   When the strata are large enough, $Var(\\bar{y}_{str})$ will almost always be less than the population variance of $Var(\\bar{y}_{srs})$ of the same sample size\n-   The more the means of the strata differ, the more precision you will gain from using proportional allocation.\n\n#### Method 2: Optimal Allocation\n\nAllocation of sampling units to strata so that the variance of the estimator is minimized for a given total cost.\n\n-   Disproportional allocation: Allocation of sampling units to strata so that the sampling fractions \\$\\frac{n_h}{N_h} are unequal\n\n#### Method 3: Allocation for Specified Precision within Strata\n\n-   Sometimes we are less interested in estimating the overall population values, and more interested in comparing the totals or means across stratum\n-   In this case we would need to determine the sample size for each stratum that corresponds to a specific level of precision.\n\n## Which allocation to use?\n\n------------------------------------------------------------------------\n\n## Summary\n\n-   This section setup the motivation for why using the stratified sampling method may be beneficial.\n-   Once SRS's are taken from each strata, the results can be pooled to make inferences about the entire population (the ultimate goal).\n-   Don't have to sample the same % from each strata\n-   Could see a greater reduction in variance of the overall estimate with an increased sampling fraction from strata with high variance.\n\n------------------------------------------------------------------------\n\n# Using R\n\n## Selecting a Stratified Random Sample\n\n### Using the `strata` function from the `sampling` package\n\n1.  Sort the data by the stratification variable\n\n\n::: {.cell}\n\n```{.r .cell-code}\nagpop.sorted <- agpop %>% arrange(region)\n```\n:::\n\n\n2.  Specify the desired within-strata sample sizes $n_{k}$.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn.k <- c(103, 21, 135, 41)\n```\n:::\n\n\n3.  Create the sampling index of records to select using the `strata` function with arguments specifying the strata names, strata size, and sampling method within strata.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstrat.idx <- sampling::strata(data = agpop.sorted, stratanames = \"region\", \n                    size = n.k, method = \"srswor\")\n```\n:::\n\n\n:warning: Package conflicts can occur with the `strata` function. If it is not working for you, use the `sampling::strata` method of calling the function to ensure you are using the correct version of the `strata` function from the `sampling` package.\n\n4.  Extract the data records that correspond to the sampling index.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nag.str <- getdata(agpop.sorted, strat.idx)\nhead(ag.str)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n              county state acres92 acres87 acres82 farms92 farms87 farms82\n4   APPANOOSE COUNTY    IA  238609  244661  236501     827     891     900\n7  BLACK HAWK COUNTY    IA  299502  305516  308845    1111    1269    1352\n31    DUBUQUE COUNTY    IA  343870  334112  338912    1653    1689    1708\n52    JOHNSON COUNTY    IA  284537  305634  328240    1242    1356    1508\n60       LYON COUNTY    IA  347599  342938  357493    1194    1234    1391\n61    MADISON COUNTY    IA  305685  293643  313648    1026    1059    1154\n   largef92 largef87 largef82 smallf92 smallf87 smallf82 region ID_unit\n4        28       33       23       25       39       36     NC       4\n7        49       34       27      116      152      154     NC       7\n31       13       10        8      107      128       88     NC      31\n52       27       31       26       74      104       99     NC      52\n60       32       24       15      128      125      127     NC      60\n61       47       44       39       47       75       81     NC      61\n         Prob Stratum\n4  0.09772296       1\n7  0.09772296       1\n31 0.09772296       1\n52 0.09772296       1\n60 0.09772296       1\n61 0.09772296       1\n```\n:::\n:::\n\n\n5.  Calculate the sampling weights using the inclusion probabilities (these were created as the variable `Prob` when you used the `strata` function)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nag.str$wt <- 1/ag.str$Prob\nhead(ag.str)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n              county state acres92 acres87 acres82 farms92 farms87 farms82\n4   APPANOOSE COUNTY    IA  238609  244661  236501     827     891     900\n7  BLACK HAWK COUNTY    IA  299502  305516  308845    1111    1269    1352\n31    DUBUQUE COUNTY    IA  343870  334112  338912    1653    1689    1708\n52    JOHNSON COUNTY    IA  284537  305634  328240    1242    1356    1508\n60       LYON COUNTY    IA  347599  342938  357493    1194    1234    1391\n61    MADISON COUNTY    IA  305685  293643  313648    1026    1059    1154\n   largef92 largef87 largef82 smallf92 smallf87 smallf82 region ID_unit\n4        28       33       23       25       39       36     NC       4\n7        49       34       27      116      152      154     NC       7\n31       13       10        8      107      128       88     NC      31\n52       27       31       26       74      104       99     NC      52\n60       32       24       15      128      125      127     NC      60\n61       47       44       39       47       75       81     NC      61\n         Prob Stratum       wt\n4  0.09772296       1 10.23301\n7  0.09772296       1 10.23301\n31 0.09772296       1 10.23301\n52 0.09772296       1 10.23301\n60 0.09772296       1 10.23301\n61 0.09772296       1 10.23301\n```\n:::\n:::\n\n\n5b. Check that the sampling weights sum to the stratum population sizes.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nag.str %>% group_by(region) %>% summarize(sum.wts = sum(wt))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 4 × 2\n  region sum.wts\n  <chr>    <dbl>\n1 NC        1054\n2 NE         220\n3 S         1382\n4 W          422\n```\n:::\n\n```{.r .cell-code}\ntable(agpop.sorted$region)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  NC   NE    S    W \n1054  220 1382  422 \n```\n:::\n:::\n\n\n::: callout-important\n### Warning\n\nIf the weights do not sum to the stratum population sizes, you have made a mistake somewhere in the calculations for the weights or strata sizes.\n:::\n\n::: {.callout-note icon=\"false\" collapse=\"true\" appearance=\"minimal\"}\n### Clean up\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrm(list=ls()[!ls() %in% c(\"agpop\", \"agstrat\",\"caribou\", \"agpop.sorted\", \"N.k\", \"n.k\", \"ag.str\")])\n```\n:::\n\n:::\n\n------------------------------------------------------------------------\n\n## Computing Statistics from a Stratified Random Sample\n\n### 1. Setup the information for the survey design.\n\n#### a. Specify weights\n\nWe created the weights in the dataset in the the last step.\n\n#### b. Specify fpc\n\nWe need to create a vector of fpc's that are equal to the strata population size. In a SRS, we used `fpc = rep(N,n)`. This create a vector that contains the value `N`, repeated `n` times. In this case, we need to match the strata population size to each record from that strata.\n\nOption 1: Create a vector that repeats the values in the vector `N.k`, each `n.k` times.\n\n\n::: {.cell}\n\n```{.r .cell-code}\noption1.fpc <- rep(N.k, n.k)\n```\n:::\n\n\n::: {.callout-tip icon=\"false\" collapse=\"true\" appearance=\"minimal\"}\n**Example on how to use the `rep` function**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nex.N.k <- c(10,25,50) # example population sizes\nex.n.k <- c(2,5,10)   # example strata sizes\nrep(ex.N.k, ex.n.k)   \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] 10 10 25 25 25 25 25 50 50 50 50 50 50 50 50 50 50\n```\n:::\n:::\n\n\nThe pop size for stratum 1 is repeated twice (the size of the sample from that stratum), the pop size for stratum 2 is repeated 5 times (the sample size for stat stratum) etc.\n:::\n\nOption 2: Merge the pop sizes onto the sample data using `region` as a joining key\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(pop.strata.sizes <- table(agpop.sorted$region) %>% data.frame())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  Var1 Freq\n1   NC 1054\n2   NE  220\n3    S 1382\n4    W  422\n```\n:::\n\n```{.r .cell-code}\npop.strata.sizes <- rename(pop.strata.sizes, region = Var1, popsize = Freq)\nag.str.opt2 <- ag.str %>% left_join(pop.strata.sizes)\n```\n:::\n\n\n### 2. Call `svydesign`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nagpop.str.dsgn <- svydesign(id = ~1, strata = ~region, weights = ~wt, \n                            fpc = ~popsize, \n                            # fpc = option1.fpc # This would be Option 1\n                            data= ag.str.opt2)\n```\n:::\n\n\n### 3. Calculate total, SE and CI\n\nNote the degrees of freedom for a CI under a stratified sample is $n-H$, which can be extracted from the `svydesign` object using the `degf` function.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(str.total <- svytotal(~acres92, agpop.str.dsgn))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n            total       SE\nacres92 914183605 65768044\n```\n:::\n\n```{.r .cell-code}\nconfint(str.total, level = .95, df = degf(agpop.str.dsgn))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n            2.5 %     97.5 %\nacres92 784751390 1043615820\n```\n:::\n:::\n\n\n::: {.callout-tip icon=\"true\"}\n### Example: Farmland in 1992\n\nThe book's provided `agstrat` data set is a stratified random sample with proportional allocation. The weights are contained in a variable called `strwt`. Let's re-estimate the total amount of farmland using the sampling package.\n:::\n\n1.  Calculate the vector of population sizes for the fpc using Option 2 above.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nagstrat <- agstrat %>% left_join(pop.strata.sizes)\ntable(agstrat$popsize) # confirm\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n 220  422 1054 1382 \n  21   41  103  135 \n```\n:::\n:::\n\n\n2.  Define the survey design\n\n\n::: {.cell}\n\n```{.r .cell-code}\nagstrat.dsgn <- svydesign(id = ~1, strata = ~region, \n                          weights = ~strwt, \n                          fpc = ~popsize, \n                          data= agstrat)\n```\n:::\n\n\n3.  calculate the stratified total with CI.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(str.total <- svytotal(~acres92, agstrat.dsgn))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n            total       SE\nacres92 909736036 50417248\n```\n:::\n\n```{.r .cell-code}\nconfint(str.total, level = .95, df = degf(agstrat.dsgn))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n            2.5 %     97.5 %\nacres92 810514350 1008957721\n```\n:::\n:::\n\n\n### Calculating stratum means and variances\n\nInstead of using the formulas as shown in Ch 3.3, we can use the `svyby` function.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nregional.totals <- svyby(~acres92, by=~region, agstrat.dsgn, \n                         svytotal, keep.var = TRUE)\nkable(regional.totals)\n```\n\n::: {.cell-output-display}\n|   |region |   acres92|       se|\n|:--|:------|---------:|--------:|\n|NC |NC     | 316731380| 16977399|\n|NE |NE     |  21478558|  3992889|\n|S  |S      | 292037392| 26154840|\n|W  |W      | 279488706| 39416342|\n:::\n:::\n\n\nConfirm the overall total $\\hat{\\tau}_{str}$ by summing these values across the strata.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(regional.totals$acres92)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 909736036\n```\n:::\n:::\n",
    "supporting": [
      "cn06-stratified_sampling_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}