{
  "hash": "379cc99b93f5e708a6f3f991febb41a1",
  "result": {
    "engine": "knitr",
    "markdown": "---\nformat: html\ntitle: \"Homework 03: Simple Random Sampling\"\nsubtitle: \"\"\ndate: 02/24/25\ncategories: Homework\n---\n\n\n\nThis assignment will use statewide open source data on Covid-19 hospitalizations. \n\n1. Go go the CA Open data portal: https://data.ca.gov/\n2. At the top, click on \"Datasets\"\n3. On the left, click on \"CSV\" \n4. Download the COVID-19 Hospital data (data dictionary and data set)\n\nBe sure to read the codebook to make sure you understand what data was collected, the time frame, and exactly what the variables mean. Your answers must be in context of the data. \n\n1. Generate two random samples without replacement. One between 10% and 30% of the data set size, and one between 50 and 70%. The exact numbers are your choice. Set a seed to ensure reproducibility.\n\n\n2. Choose a numeric variable. For both samples estimate the total, mean, and proportions of variables of your choice with 95% confidence intervals. Be sure to adjust for your sample weights and fpc. Use the functions from the `survey` package to do these calculations. Interpret each estimate and interval in context of the problem. \n\n\n3. Using a summary table similar to the one from the notes, calculate and report the bias for each sample. What effect did the sample size have on your estimates or the variability of the estimates? \n\n\n\n### 2. Conduct your own survey. \n\nTake a small SRS of something you are interested in. The data collection for this exercise should not take a great deal of effort, as you are surrounded by things waiting to be sampled. Some examples: proportion of web pages that result from an internet search about a topic, average weights of 1-pound bags of carrots at the supermarket, or the average cost of a used dining room table from an online classified advertisement site.\n\na) Explain what it is you decide to measure. Be explicit about what parameter you are trying to estimate. \nb) Define the following terms for your sample: target population, sampled population, sampling frame, sampling unit, observational unit\nc) Describe how you created your sampling frame and show how you generated the randomly sampled numbers.\nd) Collect your data, do your measurements, and create a data frame with appropriate weights. \ne) Using the `svydesign` and appropriate `svy*` functions, calculate a point estimate and confidence interval for the parameter of interest.\nf) Report your results in a full complete english sentence with point estimate and CI. \n\n:::{.callout-tip}\n#### Dr. D's book example\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(survey)\n```\n:::\n\n\na) \nI would like to estimate the average number of pages in books in my office. \n\nb) \n\n* My **target population** is all books in my office. \n* The **sampled population** will be the books on the top shelf in my office.\n* My **sampling frame** is a numbered list of books on the top shelf in my office\n* A **sampling unit** is a number off the list that describes the position of the book starting on the right. \n* My **observational unit** is a book. \n\nc) \nI have 26 books on my top shelf. I will take a random sample of 5 numbers between 1 and 26 and use that result to choose those books to measure. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(202)\nsample(1:26, 5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 16 14  8 24  6\n```\n\n\n:::\n:::\n\n\nCounting from the right, I will choose the books numbered listed above. \n\nd) \n\n::: {.cell}\n\n```{.r .cell-code}\nbooks <- data.frame(\n  npages = c(601, 452, 259, 418, 418),\n  wt = 26/5\n)\n```\n:::\n\n\ne) \nCreate a sampling design. \n\n::: {.cell}\n\n```{.r .cell-code}\nbook.design <- svydesign(id = ~1, \n                         wt = ~wt, \n                         fpc = rep(26,5),\n                         data = books)\n```\n:::\n\n\nCalculate the estimated total number of pages of books in my office: \n\n\n::: {.cell}\n\n```{.r .cell-code}\nsvymean(~npages, book.design)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        mean     SE\nnpages 429.6 48.917\n```\n\n\n:::\n\n```{.r .cell-code}\nsvymean(~npages, book.design) |> confint()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          2.5 %   97.5 %\nnpages 333.7235 525.4765\n```\n\n\n:::\n:::\n\n\nf) \n\nOn average, books in my office are 430 (95% CI 333, 525) pages long. \n:::\n\n\n\n",
    "supporting": [
      "hw03-SRS_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}