---
format: html
title: "Homework 01: Sampling Framework"
date: "01/27/25"
categories: Homework
subtitle: "Chapter 1 material"
---


# Part I. Key Terms

Choose 2 items from Exercises 1–31 in the textbook to answer. Include the question text in your assignment. 


# Part II. Survey tool evaluation.

Many universities ask students to fill out a course evaluation at the end of the term. Chico State has 5 forms that are approved for use in different departments. You can find the list and forms [at this link](https://www.csuchico.edu/ir/sfot/forms.shtml).


1. What procedure is used to distribute and collect these surveys? What are some possible sources of selection bias?
2. Pick one(1) of the forms and evaluate the questions on this survey against each of the guidelines presented in the textbook chapter 1.5. 
3. Explain why you think the specific student evaluation that you chose does, or does not, give an accurate measurement of student satisfaction with the course.
4. Now consider all five forms. If you only had to give one, which one would you choose and why? Be prepared to defend your answer in class. 
