---
format: html
title: "Homework 02: Simple Random Sampling"
subtitle: ""
date: 02/24/23
categories: Homework
---


### 1. Estimating crime rates. 

The Chicago database of crimes known to police between 2001 and 2019 at https://data.cityofchicago.org/ contained 7,048,107 records. To reduce the size of the data for performing analyses, an SRS of 5,000 records was drawn from the database and saved in file `crimes.csv`. 

a. What is the sampling weight for each record in the sample?

b. What is the estimated percentage of crimes in which an arrest was made? Give a 95% CI.

c. Estimate the total number of burglaries known to police between 2001 and 2019 (use variable `crimetype` to identify the burglaries), along with a 95% CI


### 2. Conduct your own survey. 
Take a small SRS of something you are interested in. Explain what it is you decide to study and carefully describe how you chose your SRS (give the random numbers generated and explain how you translated them into observations), report your data, and give a point estimate and the SE for the quantity or quantities of interest.

The data collection for this exercise should not take a great deal of effort, as you are surrounded by things waiting to be sampled. Some examples: web pages that result from an internet search about a topic, actual weights of 1-pound bags of carrots at the supermarket, or the cost of a used dining room table from an online classified advertisement site.
