---
title: "Worksheet 2"
categories: Worksheet
date: 2/10/23
---

Sometimes we may need to choose between two sampling plans by comparing measures such as variance, bias and accuracy. Here we are interested in estimating $\mu$, the population mean.

For purposes of studying sampling distributions, assume that all population values are known: $y_1 = 98, y_2 = 109, y_3 = 154, y_4=133, y_5 = 190, y_6 = 175$. Out of the $N=6$ total possible values to sample from, we will choose $n=3$. 

**Plan 1**: The following eight possible samples may be chosen with equal probability: {1,3,5}, {1,3,6}, {1,4,5}, {1,4,6}, {2,3,5}, {2,3,6}, {2,4,5}, {2,4,6}

**Plan 2**: The following three samples may be chosen: {1,4,6}, {2,3,6}, {1,3,5} with respective probabilities $\delta$ = (.25, .5, .25). 

Answer the following questions: 

**a) What is the value of $\mu$? **


**b) For each sampling plan, find: i)$E[\bar{y}]$, ii) $V[\bar{y}]$, iii)$\mbox{Bias}(\bar{y})$, iv) $MSE(\bar{y})$, where $\bar{y}$ is the mean of sample values.**


**c) Which sampling plan do you think is better, and why?**



