---
title: "Welcome to MATH 458"
subtitle: "Sampling Methods"
description: "Course Overview slides"
date: "2025-01-22"
author: "Robin Donatello"
format: 
  revealjs:
    theme: blood
    transition: fade
    slide-number: true
---

# Meet your instructor {background-image="../figs/Zombatar.jpg" background-size="250px" background-position="95% 15%"}

## Dr. Robin Donatello (she/her) {.smaller}

You can address me as "Robin", "Dr. D", or some other respectful title that you feel comfortable with. 

I have a Doctorate in Public Health (DrPH) Biostatistics from UCLA, but I'm a Chico alum. I double majored in Statistics & Biology, with minor in Chemistry, and a first generation college student who started at Butte College.

My campus life consists of training the next generation of Scientists how to harness the power of Statistics and Data in a responsible and ethical manner, leading the Data Science Initiative (DSI) provide training and experiences for students and faculty, and providing analytical support and statistical consulting for many projects on and off campus.

When I'm not on campus, typically I'm growing food for my family, out adventuring with my dogs, or getting some game time in. You can learn more about the projects i'm involved in on my [website](http://www.norcalbiostat.com/).

## Your turn

* Turn to your neighbor and introduce yourself. 
* You'll post an introduction in Discord this week so everyone will get to know everyone else. 

# Code of Conduct

## Everyone is welcome here

It is my intent that students from all diverse backgrounds and perspectives be well-served by this course, that students' learning needs be addressed both in and out of class, and that the diversity that the students bring to this class be viewed as a resource, strength and benefit. 

It is my intent to present materials and activities that are respectful of diversity: gender identity, sexuality, disability, age, socioeconomic status, ethnicity, race, nationality, religion, and culture. 

## Supportive Learning Environment

I would like to create a learning environment that supports a diversity of thoughts, perspectives and experiences, and honors your identities (including race, gender, class, sexuality, religion, ability, etc.) 

## To help accomplish this:

* Let me know if you have a name and/or set of pronouns that differ from those that appear in your official Chico records. 
* Help me pronounce your name as accurately as possible. Corrections are welcome. 
* If you feel like your performance in the class is being impacted by your experiences outside of class, please don't hesitate to come and talk with me. I want to be a resource for you.

## Mitigating our risk of COVID-19 {.smaller}

* This is still a real thing, but we all have different levels of risk we are willing to take ourselves, and different risk management strategies. 
* I personally am working on reducing my mask wearing to re-challenge my immune system, but I also have immunocompromised elderly mother at home. Always a balance. 
* Masks will ALWAYS be welcome and respected in this classroom. No questions.
* I am likely to request masks be worn in my office. 
* Please keep up to date with available booster shots. You can't learn if you're ill. 
* If you have COVID symptoms, :stop_sign: Do not come to class. I'll turn on Zoom for the day so you can participate.
* If you are just generally feeling unwell, please use a mask. I will always have some on hand. 


# Disclaimer {.smaller}

* This is my first time teaching this class. Last I worked with this material I was in your shoes (Undergrad, Senior, 2004ish)
* I've also been sick for most of winter break :mask:
* I have all the materials from another instructor, and a highly recommended book. So for much of the class we will be learning the material together. 
* That's the main thing that makes me a different learner from you. Some of you have better working knowledge of pure and applied mathematical topics than I do. I just have more practice applying, and learning new statistics than you do. 
* So this is all to say that this won't be a passive class where I'm up here telling you how it is. 
* And I can't give you a solid schedule of topics & calendar of due dates because i'm not sure how long it'll take for us to cover each topic. 

# What is this class about? 

## Course Description

The theory and application of survey sampling techniques. Topics include simple random sampling, stratified sampling, systematic sampling, and cluster sampling. Appropriate for mathematics, computer science, psychology, social science, agriculture, biology, and other majors.

By "survey" we do not strictly mean a self report survey such as the Student Feedback on Teaching. The concept is much broader. 

## Motivating Example

Go to Canvas, week 0 module and read through the motivating example. Then respond to this thread by writing a few sentence summary of the example and  include your take away message. 


Read through all posts later this week to see how similar, or different their messages are from yours. We all come to this class from different backgrounds and perspectives, and so will see things differently. You are welcome and encouraged to respond to other's posts. 

## Learning goals {.smaller}

1. Define principal concepts, advantages and disadvantages of sampling.
2. Categorize, define, compare between, and implement various sampling methods such as Simple Random Sampling, Stratified Sampling, and Cluster Sampling. 
3. Formulate and calculate appropriate estimators and confidence intervals for population parameters under various sampling frameworks. 
4. Estimate the convenient or optimal sample size for various sampling methods.
5. Design, conduct, and analyze your own data collection mini-study 
6. Bonus: You'll get *really* good at writing R functions. 

# How are we going to work together? 

## A variety of learning and working tools

* Many of you have had me as an instructor in the past, so some of this won't be new. 
* I use a combination of tools that are most appropriate for the task or outcome at hand.
* Homework 0 provides a checklist for getting connected and testing out your tools.

## Class website

<div style="text-align:center">https://sampling-458.netlify.app/

-   Bookmark this page. You will be here a lot. Going through Canvas each time is a waste of your time and clicks. 
-   Contains a weekly overview, lecture notes, homework files, relevant links. 
-   Sometimes links will be broken. Typo's happen. Notify me via Discord and I'll get to it asap.

## Textbook

- [Sampling, 3rd Edition. Sharon Lohr](https://www.sharonlohr.com/sampling-design-and-analysis-3e)
- Download the R companion for the book from this site as well. I anticipate it'll be useful.  

## Canvas

* Canvas is new to me, and it seems reasonable for organizing due dates & submissions so we'll try that out
* It'll be your gradebook as well. 
* Content is organized into Modules, with flow and due dates
* I will also put links to files that you need to download here. 

> I reserve the right to adjust where links and content are contained throughout the semseter if I find Canvas not to be the right tool at this time for me (or perhaps it will work better?)


## Discord

-   Used for outside class discussions, meme sharing, homework help and general chatter.
-   I will not answer most class-content based questions through email.
-   Download either the phone app or the desktop app (I use both). This is mandatory.
    -   Do not rely on remembering to log in via the web browser. You will miss important notifications.

## Learning Content {.smaller}

* HTML based notes that to start out with are semi-complete. [Example](https://sampling-458.netlify.app/notes/cn01-intro_simulation.html)
* During class we will work together through examples, you will work together on "you try it" practice problems, and answer questions
* You will have a version of these notes that have blank spots for you to fill in, or answer questions
    - You will compile these notes to PDF and submit them through Canvas a few days after we complete a section 
* I will update the online posted notes with our collaborative solutions to the "you try it" problems.
* As the term progresses, you will be creating sections of these notes (that will be posted) and "teaching" the rest of the class your topic. 

## Hack MD

- Account setup instructions part of HW0
- Interactive markdown based collaborative notes
- I will give you a file for the first set of 'blank' notes.
- Afterward you will be responsible for copying them (and sometimes filling out sections) of the notes directly in HackMD. 


## R + R Studio 

* We will be using the R programming language, along with Rstudio the Integrated Development Environment. More info on how to download and update your system can be found in Hw0. 
* New to R? I recommend you also enroll in Math 130 ASAP. This semester it is asynchronous online. This is a 5 week primer to get you from zero to basic ability to import, visualize and manage data. 
    - Just need a refresher/jump start? Everything is online [https://norcalbiostat.github.io/MATH130/](https://norcalbiostat.github.io/MATH130/)

## Graded Content 

* Worksheets, homework assignments, notes, exams, and a project. 
* Details in the [Syllabus](https://sampling-458.netlify.app/syllabus.html#assignments-graded-items). 

# What questions do you have for me? 

# Let's get started. 

Go to the course website --> weekly overview --> week 1. 