---
title: "Formulas and Definitions"
description: "Equations and R code"
date: "2023-01-20"
---

# Parameters and Statistics

| Measure        | Population $(\theta)$                             | Sample $(\hat{\theta})$                            |
|------------------|--------------------------|---------------------------|
| Total          | $\tau = \sum_{i=1}^N y_{i}$                       | $\hat{\tau} = \sum_{i=1}^n y_{i}$                  |
| Mean           | $\mu = \frac{1}{N}\sum_{i=1}^N y_{i}$             | $\bar{y} = \frac{1}{n}\sum_{i=1}^n y_{i}$          |
| Variance       | $\sigma^2 = \frac{1}{N}\sum_{i=1}^{N}(y_i-\mu)^2$ | $s^2 = \frac{1}{n-1}\sum_{i=1}^{n}(y_i-\bar{y})^2$ |
| Proportion$^*$ | $p = \mu$                                         | $\hat{p} = \bar{y}$                                |

-   $N$ = total population size

-   $y_{i}$ = Value of measurement $y$ on unit $i$

-   $^*$For proportions $y_{i}$ is a binary indicator of success. $y \in {[0,1]}$. I.e. $I(y_{i}=1)$.

## Expected Value and Variance of estimates

$$E(\hat{\theta}) = \sum\hat{\theta}*p(\hat{\theta}) \qquad \qquad V(\hat{\theta}) = \sum [\hat{\theta} - E(\hat{\theta})]^2*p(\hat{\theta})$$

-   Sums are over all possible values of $\hat{\theta}$.
-   $p(\hat{\theta})$ is the probability of $\hat{\theta}$ occurring.
    -   This is similar to what we're calling $\delta_{i}$, the probability that population unit $i$ appears in the sample. The book uses the symbol $\pi_{i}$

----

# Weighted Estimators for Probability sampling designs

These weighted estimators are used in all probability sampling designs. Weights $w$ are applied directly to the data value $y$ before use in any formulas. 


|         Population size         |                  Total                  |                  Mean                  |
|:-----------------------:|:-------------------:|:-------------------------:|
| $\hat{N} = \sum_{i \in S}w_{i}$ | $\hat{\tau} = \sum_{i \in S}w_{i}y_{i}$ | $\bar{y} = \frac{\hat{\tau}}{\hat{N}}$ |


----

# Estimators under different Sampling Designs

## Simple Random Sample

| Measure    | Unbiased Estimate $(\hat{\theta})$         | Estimated variance of $(\hat{\theta})$                             |
|------------------|---------------------|---------------------------------|
| Mean       | $\bar{y} = \frac{1}{n}\sum_{i\in S} y_{i}$ | $\hat{V}(\bar{y}) = (1-\frac{n}{N})\frac{s^{2}}{n}$                |
| Total      | $\hat{\tau} = N\bar{y}$                    | $\hat{V}(\hat{\tau}) = N^{2}\hat{V}(\bar{y})$                      |
| Proportion | $\hat{p} = \bar{y}$                        | $\hat{V}(\hat{p}) = (1-\frac{n}{N})\frac{\hat{p}(1-\hat{p})}{n-1}$ |

-   $i \in S$ : Unit $i$ is an element in the sample $S$
-   $(1-\frac{n}{N})$: Finite population correction (fpc)


## Stratified Random Sample


| Measure                   | Population $(\theta)$                                                  | Sample $(\hat{\theta})$                                     |
|------------------|-----------------------------|-----------------------------|
| Sample size in strata $h$ | $N_{h}$                                                                | $n_{h}$                                                     |
| Overall sample size       | $N = \sum_{h} N_{h}$                                             | $n = \sum_{h} n_{h}$                                  |
| Total in strata $h$       | $\tau_{h} = \sum_{j=1}^{N_{h}} y_{hj}$                                 | $\hat{\tau}_{h} = N_{h}\bar{y_h}$                           |
| Overall total             | $\tau = \sum_{h} \tau_{h}$                                       | $\hat{\tau}_{str} = \sum_{h}N_{h}\bar{y}_{h}$         |
| Mean in strata $h$        | $\mu_{h} = \frac{\tau_{h}}{N_{h}}$                                     | $\bar{y}_{h} = \frac{1}{n_{h}}\sum_{j} y_{hj}$              |
| Overall mean              | $\mu = \frac{\tau}{N}$                                                 | $\bar{y}_{str} = \sum_{h} \frac{N_{h}}{N}\bar{y}_{h}$ |
| Variance of the mean     | $\sigma_{h}^2 = \frac{1}{N_{h}-1}\sum_{j=1}^{N_{h}}(y_{hj}-\mu_{h})^2$ | $s_{h}^2 = \frac{1}{n_{h}-1}\sum_{j}(y_{hj}-\bar{y}_{h})^2$ |
| Proportion in strata| $p_{h} = \mu_h$ | $\bar{y}_h = \hat{p}_h$ |
| Variance of $p_{h}$ | $\sigma_h^2=\frac{N_h}{N_h-1} p_h(1-p_h)$ | $s_h^2=\frac{n_h}{n_h-1} \hat{p}_h(1-\hat{p}_h)$ |
| Overall proportion | $p = \sum_{h} \frac{N_h}{N} p_h$ | $\hat{p}_{str} = \sum_{h} \frac{N_h}{N}\hat{p}_h$  |


Misc additional equations; 

* Estimated variance of population total $\hat{V}(\hat{\tau}_{str}) = \sum_{h} (1-\frac{n_h}{N_h})N^2 \frac{s^2_h}{n_h}$
* Estimated variance of population proportion $\hat{V}(\hat{p}_{str}) = \sum_{h} (1-\frac{n_h}{N_h}) (\frac{N_h}{N})^2 \frac{\hat{p}_h (1-\hat{p}_h)}{n_h-1}$
* Estimated total number of population units having a specified characteristic: $\hat{t}_{str} = \sum_{h} N_h \hat{p}_h$, with variance $N^2\hat{V}(\hat{p}_{str})$. 

----

# R commands 

This is a quick reference list. See the R companion for the textbook, the `survey` package help file or vignette for more information. 

## Specify survey design `svydesign`

* Function call: `svydesign(id = , weights=,  fpc= , data = )`
* `id` = variable that identifies clusters 
* `weights` = variable that holds the sampling weights
* `fpc` = finite population correction. Typically defined in the function call. 

Argument details: 

* SRS page R companion pg21
* Stratified Random Sample R companion pg34


## Summary Statistics

* **mean**: `svymean(~x, design)`
* **total**: `svytotal(~x, design)`
* **proportion**: Use `svytotal` and divide by `N`
* **CI for the mean or total**: Use `confint()` after calculating the point estimate
* **CI for proportion**: `svyciprop(~x, design)` Will also print out $\hat{p}$



## Analysis


http://r-survey.r-forge.r-project.org/survey/example-regression.html

* Linear Regression: y~x
* T-Test: y ~x where x is binary
* ANOVA: y~x where x is categorical

[Play the game: Is this fancy analysis "Just" a linear model?](https://twitter.com/WomenInStat/status/1286420597505892352) 


## Other R help References

-   [`survey` package vignette](http://r-survey.r-forge.r-project.org/survey/)
-   [The Epidemiologist R handbook](https://epirhandbook.com/en/survey-analysis.html)

