---
title: "Formulas and Definitions"
---

# Expected Value and Variance

$$E(\hat{\theta}) = \sum\hat{\theta}*p(\hat{\theta}) \qquad \qquad V(\hat{\theta}) = \sum [\hat{\theta} - E(\hat{\theta})]^2*p(\hat{\theta})$$

* Estimates $\theta$ are calculated on the sampling distribution
* The sums are over all possible values of $\theta$ in the sampling design. 

# Parameters and Statistics

| Measure        | Population                                        | Sample                                             |
|------------------|---------------------------|---------------------------|
| Total          | $\tau = \sum_{i=1}^N y_{i}$                       | $\hat{\tau} = \sum_{i=1}^n y_{i}$                  |
| Mean           | $\mu = \frac{1}{N}\sum_{i=1}^N y_{i}$             | $\bar{y} = \frac{1}{n}\sum_{i=1}^n y_{i}$          |
| Variance       | $\sigma^2 = \frac{1}{N}\sum_{i=1}^{N}(y_i-\mu)^2$ | $s^2 = \frac{1}{n-1}\sum_{i=1}^{n}(y_i-\bar{y})^2$ |
| Proportion$^*$ | $p = \mu$                                         | $\hat{p} = \bar{y}$                                |

-   $N$ = total population size

-   $y_{i}$ = Value of measurement $y$ on unit $i$

-   $p(y)$ probability of observing value $y$

-   For all proportion calculations it is assumed that $y_{i}$ is a binary indicator of success. $y \in {[0,1]}$

# Simple Random Sample

| Measure    | Unbiased Estimate $(\hat{\theta})$         | Estimated variance of $(\hat{\theta})$                             |
|---------------|-------------------------|-----------------------------|
| Mean       | $\bar{y} = \frac{1}{n}\sum_{i\in S} y_{i}$ | $\hat{V}(\bar{y}) = (1-\frac{n}{N})\frac{s^{2}}{n}$                |
| Total      | $\hat{\tau} = N\bar{y}$                    | $\hat{V}(\hat{\tau}) = N^{2}\hat{V}(\bar{y})$                      |
| Proportion | $\hat{p} = \bar{y}$                        | $\hat{V}(\hat{p}) = (1-\frac{n}{N})\frac{\hat{p}(1-\hat{p})}{n-1}$ |

-   $i \in S$ : Unit $i$ is an element in the sample $S$
-   $(1-\frac{n}{N})$: Finite population correction (fpc)
